Repository uzh-bf/klicker-uzh, pull requests merged in 2018-02, with the labels that each got.

#336 Update dependency jest to v22.2.2
  package.json
  yarn.lock
Labels: dependencies

#337 Update dependency elastic-apm-node to v1.0.1
  package.json
  yarn.lock
Labels: dependencies

#338 Update dependency helmet to v3.11.0
  package.json
  yarn.lock
Labels: dependencies

#339 Update dependency raven-js to v3.22.2
  package.json
  yarn.lock
Labels: dependencies

#340 Update dependency webpack to v3.11.0
  package.json
  yarn.lock
Labels: dependencies

#341 Renovate storybook packages
  package.json
  yarn.lock
Labels: dependencies

#342 General improvements
  src/components/__snapshots__/storyshots.test.js.snap
  src/components/common/ListWithHeader.js
  src/components/common/common.stories.js
  src/components/common/navbar/AccountArea.js
  src/components/common/navbar/Navbar.js
  src/components/common/navbar/SearchArea.js
  src/components/common/navbar/SessionArea.js
  src/components/forms/LoginForm.js
  src/components/forms/RegistrationForm.js
  src/components/forms/SessionCreationForm.js
  src/components/questions/Question.js
  src/components/questions/QuestionBlock.js
  src/components/questions/QuestionDetails.js
  src/components/questions/QuestionList.js
  src/components/questions/TagList.js
  src/components/sessions/Session.js
  src/components/sessions/SessionList.js
  src/components/sessions/SessionTimeline.js
  src/lang/de.json
  src/lang/en.json
  src/lib/utils/filters.js
  src/pages/questions/index.js
  src/pages/sessions/running.js
  src/pages/user/login.js
  src/pages/user/registration.js
Labels: enhancement, feature

#288 Update dependency graphql to v0.13.0
  package.json
  yarn.lock
Labels: dependencies, waiting

#343 Update dependency elastic-apm-node to v1.0.3
  package.json
  yarn.lock
Labels: dependencies

#344 Renovate monitoring packages
  package.json
  yarn.lock
Labels: dependencies

#346 Update dependency prettier-eslint-cli to v4.7.1
  package.json
  yarn.lock
Labels: dependencies

#347 Update Dockerfile node image 8-alpine digest (b0f4ff)
  Dockerfile
Labels: dependencies

#345 Update dependency jest to v22.3.0
  package.json
  yarn.lock
Labels: dependencies

#351 Confusion Barometer
  src/components/__snapshots__/storyshots.test.js.snap
  src/components/common/navbar/SessionArea.js
  src/components/confusion/ConfusionBarometer.js
  src/components/confusion/ConfusionSection.js
  src/components/feedbacks/FeedbackChannel.js
  src/components/questions/creation/ContentInput.js
  src/components/sessions/SessionTimeline.js
  src/lang/de.json
  src/pages/join.js
  src/pages/sessions/running.js
Labels: feature

#350 Session creation
  src/components/layouts/TeacherLayout.js
  src/pages/questions/index.js
  src/pages/sessions/index.js
Labels: enhancement, feature

#353 Pin dependency d3 to v4.13.0
  package.json
  yarn.lock
Labels: dependencies

#361 Update dependency validator to v9.4.1
  package.json
  yarn.lock
Labels: dependencies

#360 Update dependency react-redux to v5.0.7
  package.json
  yarn.lock
Labels: dependencies

#359 Update dependency react-autosuggest to v9.3.4
  package.json
  yarn.lock
Labels: dependencies

#358 Update dependency prosemirror-view to v1.0.11
  package.json
  yarn.lock
Labels: dependencies

#357 Update dependency griddle-react to v1.11.2
  package.json
  yarn.lock
Labels: dependencies

#355 Update dependency compression to v1.7.2
  package.json
  yarn.lock
Labels: dependencies

#354 Update dependency babel-plugin-inline-import-graphql-ast to v2.2.0
  package.json
  yarn.lock
Labels: dependencies

#362 Update dependency cypress to v2.0.2
  package.json
  yarn.lock
Labels: dependencies

#364 Update dependency lint-staged to v6.1.1
  package.json
  yarn.lock
Labels: dependencies

#356 Update dependency graphql to v0.13.1
  package.json
  yarn.lock
Labels: dependencies

#363 Update dependency eslint to v4.18.0
  package.json
  yarn.lock
Labels: dependencies

#365 Update dependency nodemon to v1.15.0
  package.json
  yarn.lock
Labels: dependencies

#366 Attempted fix for viewport height
  src/components/layouts/CommonLayout.js
  src/components/layouts/StudentLayout.js
  src/pages/__snapshots__/index.test.js.snap
  src/pages/user/__snapshots__/login.test.js.snap
  src/pages/user/__snapshots__/requestPassword.test.js.snap
  src/pages/user/__snapshots__/resetPassword.test.js.snap
Labels: enhancement

#367 Small fixes
  src/components/__snapshots__/storyshots.test.js.snap
  src/components/evaluation/EvaluationListItem.js
  src/components/evaluation/Possibilities.js
  src/components/evaluation/Statistics.js
  src/components/evaluation/charts/BarChart.js
  src/components/evaluation/charts/PieChart.js
  src/components/layouts/EvaluationLayout.js
  src/pages/sessions/evaluation.js
Labels: enhancement

#225 [WIP] Question List Sorting
  package.json
  src/components/__snapshots__/storyshots.test.js.snap
  src/components/common/Loading.js
  src/components/common/navbar/AccountArea.js
  src/components/common/navbar/Navbar.js
  src/components/common/navbar/SearchArea.js
  src/components/common/navbar/SessionArea.js
  src/components/layouts/TeacherLayout.js
  src/components/questions/QuestionList.js
  src/components/questions/TagList.js
  src/components/sessions/SessionList.js
  src/constants.js
  src/lib/index.js
  src/lib/initLogging.js
  src/lib/utils/filters.js
  src/lib/utils/filters.test.js
  src/lib/withData.js
  src/lib/withDnD.js
  src/lib/withLogging.js
  src/lib/withSortingAndFiltering.js
  src/pages/index.js
  src/pages/join.js
  src/pages/questions/create.js
  src/pages/questions/details.js
  src/pages/questions/index.js
  src/pages/sessions/evaluation.js
  src/pages/sessions/index.js
  src/pages/sessions/running.js
  src/pages/user/login.js
  src/pages/user/registration.js
  src/pages/user/requestPassword.js
  src/pages/user/resetPassword.js
  yarn.lock
Labels: feature

#369 General improvements
  package.json
  src/components/__snapshots__/storyshots.test.js.snap
  src/components/common/navbar/Navbar.js
  src/components/confusion/ConfusionBarometer.js
  src/components/confusion/ConfusionSection.js
  src/components/questions/Question.js
  src/components/questions/QuestionList.js
  src/constants.js
  src/lib/index.js
  src/lib/utils/analytics.js
  src/lib/withLogging.js
  src/pages/__snapshots__/index.test.js.snap
  src/pages/index.js
  src/pages/questions/index.js
  yarn.lock
Labels: feature

#370 Pin Dependencies
  package.json
  yarn.lock
Labels: dependencies

#371 Update dependency logrocket to v0.6.7
  package.json
  yarn.lock
Labels: dependencies

#372 Update dependency qrcode.react to v0.8.0
  package.json
  yarn.lock
Labels: dependencies

#374 Update dependency babel-eslint to v8.2.2
  package.json
  yarn.lock
Labels: dependencies

#376 Renovate eslint packages
  package.json
  yarn.lock
Labels: dependencies

#377 Update dependency jest to v22.4.0
  package.json
  yarn.lock
Labels: dependencies

#379 Update dependency nodemon to v1.15.1
  package.json
  yarn.lock
Labels: dependencies

#380 Update dependency semantic-ui-css to v2.3.0
  package.json
  yarn.lock
Labels: dependencies

#378 Update dependency lint-staged to v7
  package.json
  yarn.lock
Labels: dependencies

#375 Update dependency cypress to v2.0.3
  package.json
  yarn.lock
Labels: dependencies

#381 Renovate storybook packages
  package.json
  yarn.lock
Labels: dependencies

#382 Optimize queries and structure of question pool page
  src/components/questions/TagList.js
  src/graphql/index.js
  src/graphql/queries/QuestionPoolQuery.graphql
  src/pages/questions/index.js
Labels: enhancement

#391 Update Dockerfile node image 8-alpine digest (eae6c7)
  Dockerfile
Labels: dependencies

#383 Update dependency react-perf-devtool to v3.0.5
  package.json
  yarn.lock
Labels: dependencies

#384 Update dependency semantic-ui-react to v0.78.3
  package.json
  yarn.lock
Labels: dependencies

#387 Update dependency cypress to v2.0.4
  package.json
  yarn.lock
Labels: dependencies

#389 Update dependency webpack-bundle-analyzer to v2.11.0
  package.json
  yarn.lock
Labels: dependencies

#388 Update dependency jest to v22.4.2
  package.json
  yarn.lock
Labels: dependencies

#385 Update dependency styled-jsx-plugin-sass to v0.2.3
  package.json
  yarn.lock
Labels: dependencies

#392 Apollo Client 2.0 and Formik Forms
  .babelrc
  .storybook/utils.js
  package.json
  src/components/__snapshots__/storyshots.test.js.snap
  src/components/common/ListWithHeader.js
  src/components/forms/LoginForm.js
  src/components/forms/PasswordRequestForm.js
  src/components/forms/PasswordResetForm.js
  src/components/forms/QuestionCreationForm.js
  src/components/forms/QuestionEditForm.js
  src/components/forms/RegistrationForm.js
  src/components/forms/SessionCreationForm.js
  src/components/forms/components/FormWithLinks.js
  src/components/forms/components/FormikInput.js
  src/components/forms/components/index.js
  src/components/forms/forms.stories.js
  src/components/forms/index.js
  src/components/questionTypes/FREE/FREECreationOptions.js
  src/components/questionTypes/SC/SCCreationOptions.js
  src/components/questionTypes/TypeChooser.js
  src/components/questions/creation/ContentInput.js
  src/components/questions/creation/TagInput.js
  src/components/questions/creation/TitleInput.js
  src/components/questions/index.js
  src/components/sessions/creation/SessionTimelineInput.js
  src/graphql/index.js
  src/graphql/queryMap.json
  src/lib/index.js
  src/lib/initApollo.js
  src/lib/initRedux.js
  src/lib/withData.js
  src/next.config.js
  src/pages/__snapshots__/index.test.js.snap
  src/pages/__snapshots__/join.test.js.snap
  src/pages/index.test.js
  src/pages/join.test.js
  src/pages/questions/__snapshots__/index.test.js.snap
  src/pages/questions/create.js
  src/pages/questions/create.test.js
  src/pages/questions/details.js
  src/pages/questions/details.test.js
  src/pages/questions/index.js
  src/pages/questions/index.test.js
  src/pages/sessions/__snapshots__/index.test.js.snap
  src/pages/sessions/__snapshots__/running.test.js.snap
  src/pages/sessions/evaluation.test.js
  src/pages/sessions/index.test.js
  src/pages/sessions/running.test.js
  src/pages/user/__snapshots__/login.test.js.snap
  src/pages/user/__snapshots__/registration.test.js.snap
  src/pages/user/__snapshots__/requestPassword.test.js.snap
  src/pages/user/__snapshots__/resetPassword.test.js.snap
  src/pages/user/login.test.js
  src/pages/user/registration.test.js
  src/pages/user/requestPassword.test.js
  src/pages/user/resetPassword.test.js
  src/redux/index.js
  yarn.lock
Labels: enhancement, feature

#393 General improvements
  .babelrc
  src/components/__snapshots__/storyshots.test.js.snap
  src/components/common/navbar/SessionArea.js
  src/components/forms/LoginForm.js
  src/components/forms/PasswordRequestForm.js
  src/components/forms/PasswordResetForm.js
  src/components/forms/QuestionCreationForm.js
  src/components/forms/QuestionEditForm.js
  src/components/forms/RegistrationForm.js
  src/components/forms/components/FormWithLinks.js
  src/components/layouts/CommonLayout.js
  src/components/layouts/EvaluationLayout.js
  src/components/layouts/StudentLayout.js
  src/components/layouts/TeacherLayout.js
  src/components/questionTypes/TypeChooser.js
  src/components/questions/QuestionSingle.js
  src/components/questions/QuestionTags.js
  src/components/questions/TagList.js
  src/components/sessions/creation/SessionTimelineInput.js
  src/lang/de.json
  src/lang/en.json
  src/lib/initApollo.js
  src/pages/questions/details.js
Labels: enhancement, feature
