Repository uzh-bf/klicker-uzh, pull requests merged in 2018-05, with the labels that each got.

#499 Pin Dependencies
  package.json
  yarn.lock
Labels: dependencies

#500 Update dependency graphql-tag to v2.9.2
  package.json
  yarn.lock
Labels: dependencies

#502 Update dependency babel-eslint to v8.2.3
  package.json
  yarn.lock
Labels: dependencies

#503 Update dependency semantic-ui-react to v0.80.0
  package.json
  yarn.lock
Labels: dependencies

#504 General Improvements
  package.json
  src/_theme.scss
  src/components/__snapshots__/storyshots.test.js.snap
  src/components/common/navbar/Navbar.js
  src/components/evaluation/Chart.js
  src/components/evaluation/EvaluationListItem.js
  src/components/evaluation/Possibilities.js
  src/components/evaluation/charts/TableChart.js
  src/components/evaluation/evaluation.stories.js
  src/components/layouts/EvaluationLayout.js
  src/components/questionTypes/FREE/FREECreationOptions.js
  src/constants.js
  src/lib/utils/charts.js
  src/pages/join.js
  src/pages/sessions/evaluation.js
  yarn.lock
Labels: enhancement, feature

#501 Update dependency lodash to v4.17.10
  package.json
  yarn.lock
Labels: bug, dependencies, waiting

#505 Remove react-helmet
  package.json
  src/components/common/navbar/SessionArea.js
  src/components/confusion/ConfusionSlider.js
  src/components/layouts/CommonLayout.js
  src/components/questionTypes/FREE/FREEAnswerOptions.js
  src/lib/utils/__snapshots__/css.test.js.snap
  src/lib/utils/css.js
  src/pages/_document.js
  yarn.lock
Labels: dependencies, enhancement

#506 Update dependency babel-plugin-transform-inline-environment-variables to v0.4.1
  package.json
  yarn.lock
Labels: dependencies

#507 Update dependency griddle-react to v1.13.1
  package.json
  yarn.lock
Labels: dependencies

#488 Update dependency fingerprintjs2 to v1.8.0
  package.json
  src/components/storyshots.test.js
  yarn.lock
Labels: dependencies

#510 Update dependency react-perf-devtool to v3.0.6
  package.json
  yarn.lock
Labels: dependencies

#511 Update dependency react-tooltip to v3.5.1
  package.json
  yarn.lock
Labels: dependencies

#512 Update dependency lint-staged to v7.1.0
  package.json
  yarn.lock
Labels: dependencies

#516 Remove validator library
  package.json
  src/components/forms/QuestionCreationForm.js
  src/components/forms/QuestionEditForm.js
  yarn.lock
Labels: dependencies, enhancement

#517 Pin dependency file-loader to v1.1.11
  package.json
  yarn.lock
Labels: dependencies

#481 Rich-Text for Question Content
  .eslintrc
  package.json
  renovate.json
  src/components/common/navbar/Navbar.js
  src/components/forms/QuestionCreationForm.js
  src/components/forms/QuestionEditForm.js
  src/components/questionTypes/FREE/FREECreationPreview.js
  src/components/questionTypes/QuestionDescription.js
  src/components/questionTypes/SC/SCCreationPreview.js
  src/components/questionTypes/index.js
  src/components/questions/creation/ContentInput.js
  src/components/questions/creation/TagInput.js
  src/components/sessions/join/QuestionArea.js
  src/graphql/mutations/CreateQuestionMutation.graphql
  src/graphql/mutations/ModifyQuestionMutation.graphql
  src/graphql/queries/JoinSessionQuery.graphql
  src/graphql/queries/QuestionDetailsQuery.graphql
  src/lib/index.js
  src/lib/utils/__snapshots__/html.test.js.snap
  src/lib/utils/html.js
  src/lib/utils/html.test.js
  src/pages/index.js
  src/pages/qr.js
  src/pages/questions/create.js
  src/pages/questions/details.js
  src/pages/sessions/evaluation.js
  src/pages/user/requestPassword.js
  yarn.lock
Labels: feature

#524 Public Registration
  src/components/forms/RegistrationForm.js
  src/graphql/mutations/RegistrationMutation.graphql
  src/pages/index.js
  src/pages/user/login.js
  src/pages/user/registration.js
Labels: feature

#522 Subscriptions
  .env
  .env.prod
  package.json
  src/components/confusion/ConfusionBarometer.js
  src/components/feedbacks/Feedback.js
  src/components/feedbacks/FeedbackChannel.js
  src/graphql/index.js
  src/graphql/subscriptions/ConfusionAddedSubscription.graphql
  src/graphql/subscriptions/FeedbackAddedSubscription.graphql
  src/lib/index.js
  src/lib/initApollo.js
  src/lib/withApolloClient.js
  src/lib/withData.js
  src/lib/withStorage.js
  src/pages/_app.js
  src/pages/join.js
  src/pages/qr.js
  src/pages/questions/create.js
  src/pages/questions/details.js
  src/pages/questions/index.js
  src/pages/sessions/evaluation.js
  src/pages/sessions/index.js
  src/pages/sessions/running.js
  src/pages/user/login.js
  src/pages/user/registration.js
  src/pages/user/requestPassword.js
  src/pages/user/resetPassword.js
  yarn.lock
Labels: feature

#529 Update dependency webpack to v3.12.0
  package.json
  yarn.lock
Labels: dependencies

#531 Pausing Sessions
  src/_theme.scss
  src/components/common/navbar/Navbar.js
  src/components/layouts/CommonLayout.js
  src/components/sessions/SessionList.js
  src/components/sessions/SessionTimeline.js
  src/constants.js
  src/graphql/index.js
  src/graphql/mutations/PauseSessionMutation.graphql
  src/graphql/mutations/StartSessionMutation.graphql
  src/lang/de.json
  src/lang/en.json
  src/pages/sessions/index.js
  src/pages/sessions/running.js
Labels: feature

#536 Update dependency yup to v0.25.0
  package.json
  yarn.lock
Labels: dependencies

#535 Update dependency webpack-bundle-analyzer to v2.12.0
  package.json
  yarn.lock
Labels: dependencies

#534 Update dependency react-tooltip to v3.6.0
  package.json
  yarn.lock
Labels: dependencies

#533 Update dependency react-ga to v2.5.2
  package.json
  yarn.lock
Labels: dependencies

#532 Update dependency elastic-apm-node to v1.5.4
  package.json
  yarn.lock
Labels: dependencies

#555 Update react packages to v16.4.0
  package.json
  yarn.lock
Labels: dependencies

#556 Update dependency elastic-apm-node to v1.6.0
  package.json
  yarn.lock
Labels: dependencies

#554 Update dependency prettier to v1.13.0
  package.json
  src/lib/utils/charts.js
  src/lib/utils/math.js
  src/pages/questions/create.js
  src/pages/questions/details.js
  src/pages/user/requestPassword.js
  yarn.lock
Labels: dependencies

#553 Update dependency react-ga to v2.5.3
  package.json
  yarn.lock
Labels: dependencies

#550 Update dependency cross-env to v5.1.6
  package.json
  yarn.lock
Labels: dependencies

#549 Update storybook packages to v3.4.6
  package.json
  yarn.lock
Labels: dependencies

#547 Update dependency react-sortable-hoc to v0.8.0
  package.json
  yarn.lock
Labels: dependencies

#544 Update dependency recompose to v0.27.1
  package.json
  yarn.lock
Labels: dependencies

#543 Update dependency react-perf-devtool to v3.0.7
  package.json
  yarn.lock
Labels: dependencies

#542 Update dependency next to v6.0.3
  package.json
  yarn.lock
Labels: dependencies

#540 Update dependency helmet to v3.12.1
  package.json
  yarn.lock
Labels: dependencies

#539 Update node Docker image 8-alpine digest (015d89)
  Dockerfile
Labels: dependencies

#557 Update babel packages
  package.json
  yarn.lock
Labels: dependencies

#545 Update monitoring
  package.json
  yarn.lock
Labels: dependencies

#541 Update dependency lint-staged to v7.1.2
  package.json
  yarn.lock
Labels: dependencies

#528 Update eslint
  package.json
  src/components/evaluation/charts/TableChart.js
  yarn.lock
Labels: dependencies

#558 Update node:8-alpine Docker digest to 421ce1
  Dockerfile
Labels: dependencies

#548 Update dependency webpack-bundle-analyzer to v2.13.1
  package.json
  yarn.lock
Labels: dependencies

#546 Update dependency jest to v23
  package.json
  renovate.json
  yarn.lock
Labels: dependencies

#551 Update dependency nodemon to v1.17.5
  package.json
  yarn.lock
Labels: dependencies

#560 Pin dependency draft-js-mathjax-plugin to v1.3.4
  package.json
  yarn.lock
Labels: dependencies
