Repository uzh-bf/klicker-uzh, pull requests merged in 2018-07, with the labels that each got.

#611 Update dependency subscriptions-transport-ws to v0.9.12
  package.json
  yarn.lock
Labels: dependencies

#610 Update dependency cypress to v3.0.2
  package.json
  yarn.lock
Labels: dependencies

#609 Update dependency next to v6.1.1
  package.json
  yarn.lock
Labels: dependencies

#612 Extend Registration Validation
  src/components/forms/RegistrationForm.js
Labels: enhancement

#623 Update dependency eslint to v5.1.0
  package.json
  yarn.lock
Labels: dependencies

#621 Update node:8-alpine Docker digest to d3ecde
  Dockerfile
Labels: dependencies

#619 Update dependency recharts to v1.0.1
  package.json
  yarn.lock
Labels: dependencies

#618 Update dependency node-sass to v4.9.2
  package.json
  yarn.lock
Labels: dependencies

#624 Update dependency fingerprintjs2 to v1.8.1
  package.json
  yarn.lock
Labels: dependencies

#627 Session Creation v2
  .eslintrc
  .storybook/addons.js
  .storybook/config.js
  .storybook/fixtures.js
  .storybook/test/addons.js
  .storybook/test/config.js
  package.json
  renovate.json
  src/__stories__/sessionCreation.stories.js
  src/components/forms/sessionCreation/SessionCreationForm.js
  src/components/questions/QuestionSingle.js
  src/components/sessions/creation/QuestionDropzone.js
  src/lib/index.js
  src/lib/utils/move.js
  src/lib/utils/move.test.js
  src/pages/questions/index.js
  yarn.lock
Labels: feature

#626 Update dependency nodemon to v1.18.0
  package.json
  yarn.lock
Labels: dependencies

#629 Pin dependency @storybook/addon-console to v1.0.4
  package.json
  yarn.lock
Labels: dependencies

#622 Update semantic-ui
  package.json
  yarn.lock
Labels: dependencies

#630 Update dependency react-beautiful-dnd to v8
  package.json
  yarn.lock
Labels: dependencies

#631 Update dependency nodemon to v1.18.1
  package.json
  yarn.lock
Labels: dependencies

#632 Update dependency elastic-apm-node to v1.8.3
  package.json
  yarn.lock
Labels: dependencies

#633 Improved Validation and Information for Session Creation
  .eslintrc
  semantic.json
  src/components/common/Autosuggest.js
  src/components/common/Collapser.js
  src/components/common/ListWithHeader.js
  src/components/common/Messager.js
  src/components/common/navbar/Navbar.js
  src/components/common/navbar/SessionArea.js
  src/components/common/sidebar/Sidebar.js
  src/components/confusion/ConfusionSection.js
  src/components/confusion/ConfusionSlider.js
  src/components/evaluation/Chart.js
  src/components/evaluation/EvaluationListItem.js
  src/components/evaluation/Info.js
  src/components/evaluation/charts/TableChart.js
  src/components/feedbacks/Feedback.js
  src/components/forms/QuestionEditForm.js
  src/components/forms/SessionCreationForm.js
  src/components/forms/components/FormWithLinks.js
  src/components/forms/index.js
  src/components/forms/sessionCreation/InfoArea.js
  src/components/forms/sessionCreation/QuestionDropzone.js
  src/components/forms/sessionCreation/SessionCreationForm.js
  src/components/layouts/CommonLayout.js
  src/components/layouts/EvaluationLayout.js
  src/components/layouts/StaticLayout.js
  src/components/layouts/StudentLayout.js
  src/components/layouts/TeacherLayout.js
  src/components/questionTypes/FREE/FREECreationPreview.js
  src/components/questionTypes/SC/SCCreationOption.js
  src/components/questionTypes/SC/SCCreationPlaceholder.js
  src/components/questions/Question.js
  src/components/questions/QuestionDetails.js
  src/components/questions/QuestionList.js
  src/components/questions/QuestionSingle.js
  src/components/questions/QuestionTags.js
  src/components/questions/TagList.js
  src/components/sessions/Session.js
  src/components/sessions/SessionList.js
  src/components/sessions/SessionTimeline.js
  src/components/sessions/creation/SessionTimelineInput.js
  src/components/sessions/index.js
  src/components/sessions/join/FeedbackArea.js
  src/lib/semantic/dist/components/card.css
  src/lib/semantic/dist/components/card.min.css
  src/lib/semantic/dist/components/segment.css
  src/lib/semantic/dist/components/segment.min.css
  src/lib/semantic/dist/semantic.css
  src/lib/semantic/dist/semantic.min.css
  src/pages/index.js
  src/pages/sessions/evaluation.js
  src/pages/user/login.js
  src/pages/user/registration.js
  src/pages/user/requestPassword.js
  src/pages/user/resetPassword.js
Labels: enhancement

#635 Update dependency formik to v1
  package.json
  yarn.lock
Labels: dependencies

#634 Editing Sessions
  .babelrc
  .eslintrc
  .graphqlconfig
  package.json
  server.js
  src/components/common/ListWithHeader.js
  src/components/common/navbar/AccountArea.js
  src/components/common/navbar/SearchArea.js
  src/components/common/navbar/SessionArea.js
  src/components/confusion/ConfusionBarometer.js
  src/components/forms/sessionCreation/SessionCreationForm.js
  src/components/layouts/EvaluationLayout.js
  src/components/questionTypes/FREE/FREEAnswerOptions.js
  src/components/questions/ActionBar.js
  src/components/sessions/Session.js
  src/components/sessions/SessionList.js
  src/constants.js
  src/graphql/index.js
  src/graphql/mutations/ModifySessionMutation.graphql
  src/graphql/queries/SessionDetailsQuery.graphql
  src/lib/withLogging.js
  src/pages/questions/index.js
  src/pages/sessions/evaluation.js
  src/pages/user/login.js
  src/pages/user/registration.js
  src/pages/user/requestPassword.js
  src/pages/user/resetPassword.js
  yarn.lock
Labels: feature

#636 Update dependency react-perf-devtool to v3.0.8
  package.json
  yarn.lock
Labels: dependencies

#637 Update dependency eslint-plugin-jsx-a11y to v6.1.1
  package.json
  yarn.lock
Labels: dependencies

#638 Update dependency jest to v23.4.1
  package.json
  yarn.lock
Labels: dependencies

#639 Update dependency nodemon to v1.18.2
  package.json
  yarn.lock
Labels: dependencies

#640 Copying Sessions
  src/components/forms/sessionCreation/SessionCreationForm.js
  src/components/sessions/Session.js
  src/components/sessions/SessionTimeline.js
  src/constants.js
  src/lib/withLogging.js
  src/pages/questions/index.js
  src/pages/sessions/running.js
Labels: feature

#641 Update dependency compression to v1.7.3
  package.json
  yarn.lock
Labels: dependencies

#642 Update dependency react-beautiful-dnd to v8.0.5
  package.json
  yarn.lock
Labels: dependencies

#645 Update dependency recharts to v1.1.0
  package.json
  yarn.lock
Labels: dependencies

#646 Update dependency isomorphic-unfetch to v2.1.0
  package.json
  yarn.lock
Labels: dependencies

#648 Update dependency raven-js to v3.26.4
  package.json
  yarn.lock
Labels: dependencies

#647 Images for Questions
  .travis.yml
  Dockerfile
  package.json
  src/components/common/Collapser.js
  src/components/forms/index.js
  src/components/forms/questionManagement/FileDropzone.js
  src/components/forms/questionManagement/QuestionCreationForm.js
  src/components/forms/questionManagement/QuestionEditForm.js
  src/components/sessions/join/QuestionArea.js
  src/components/sessions/join/QuestionFiles.js
  src/constants.js
  src/graphql/index.js
  src/graphql/mutations/CreateQuestionMutation.graphql
  src/graphql/mutations/ModifyQuestionMutation.graphql
  src/graphql/mutations/RequestPresignedURLMutation.graphql
  src/graphql/queries/JoinSessionQuery.graphql
  src/graphql/queries/QuestionDetailsQuery.graphql
  src/lang/de.json
  src/lang/en.json
  src/lib/index.js
  src/lib/utils/__snapshots__/css.test.js.snap
  src/lib/utils/css.js
  src/lib/utils/css.test.js
  src/lib/utils/files.js
  src/lib/utils/omitDeep.js
  src/pages/join.js
  src/pages/questions/create.js
  src/pages/questions/details.js
  yarn.lock
Labels: feature

#649 Update dependency yup to v0.26.0
  package.json
  yarn.lock
Labels: dependencies

#659 Update dependency logrocket-react to v2
  package.json
  yarn.lock
Labels: dependencies

#658 Update dependency subscriptions-transport-ws to v0.9.13
  package.json
  yarn.lock
Labels: dependencies

#655 Update dependency semantic-ui-react to v0.82.1
  package.json
  yarn.lock
Labels: dependencies

#653 Update dependency helmet to v3.13.0
  package.json
  yarn.lock
Labels: dependencies

#652 Update dependency eslint to v5.2.0
  package.json
  yarn.lock
Labels: dependencies

#660 Update dependency formik to v1.0.2
  package.json
  yarn.lock
Labels: dependencies

#662 Implement APQ with Apollo Engine
  .travis.yml
  Dockerfile
  semantic.json
  src/lib/initApollo.js
  src/lib/semantic/src/definitions/modules/search.js
  src/lib/semantic/src/theme.less
  src/lib/semantic/src/themes/default/elements/icon.overrides
  src/lib/semantic/tasks/admin/components/init.js
  src/lib/semantic/tasks/admin/components/update.js
  src/lib/semantic/tasks/admin/distributions/update.js
Labels: enhancement

#663 Bugfixes & Quick Wins
  .travis.yml
  Dockerfile
  src/components/common/navbar/Navbar.js
  src/components/common/sidebar/Sidebar.js
  src/components/common/sidebar/SidebarItem.js
  src/components/forms/questionManagement/QuestionCreationForm.js
  src/components/forms/sessionCreation/SessionCreationForm.js
  src/components/layouts/TeacherLayout.js
  src/components/questions/QuestionBlock.js
  src/components/questions/QuestionSingle.js
  src/components/sessions/Session.js
  src/components/sessions/SessionTimeline.js
  src/graphql/queries/RunningSessionQuery.graphql
  src/graphql/queries/SessionListQuery.graphql
  src/lib/withLogging.js
  src/pages/questions/create.js
  src/pages/questions/details.js
  src/pages/questions/index.js
  src/pages/sessions/index.js
  src/pages/sessions/running.js
  src/pages/user/login.js
  src/pages/user/registration.js
  src/pages/user/requestPassword.js
  src/pages/user/resetPassword.js
Labels: enhancement, feature

#664 Update dependency subscriptions-transport-ws to v0.9.14
  package.json
  yarn.lock
Labels: dependencies

#668 Update dependency elastic-apm-node to v1.10.0
  package.json
  yarn.lock
Labels: dependencies

#670 Update dependency isomorphic-unfetch to v2.1.1
  package.json
  yarn.lock
Labels: dependencies
