Repository uzh-bf/klicker-uzh, pull requests merged in 2018-08, with the labels that each got.

#671 Update dependency elastic-apm-node to v1.10.1
  package.json
  yarn.lock
Labels: dependencies

#674 Performance & Security Improvements
  .env.prod
  server.js
  src/components/common/sidebar/LanguageSwitcher.js
  src/components/forms/userSettings/AccountDataForm.js
  src/lib/initApollo.js
  src/lib/withApolloClient.js
  src/lib/withLogging.js
  src/next.config.js
  src/pages/_app.js
  src/pages/questions/index.js
  src/pages/sessions/running.js
  src/pages/user/login.js
Labels: enhancement

#673 Update dependency sanitize-html to v1.18.3
  package.json
  yarn.lock
Labels: dependencies

#672 Update dependency react-beautiful-dnd to v8.0.7
  package.json
  yarn.lock
Labels: dependencies

#675 Update react to v16.4.2
  package.json
  yarn.lock
Labels: dependencies

#669 Update dependency recompose to v0.28.1
  package.json
  yarn.lock
Labels: dependencies

#677 Update dependency sanitize-html to v1.18.4
  package.json
  yarn.lock
Labels: dependencies

#678 Configuration Management
  .env.prod
  config.js
  package.json
  server.js
  src/klicker.conf.js
  yarn.lock
Labels: enhancement

#679 Check existence of email and shortname on signup
  src/components/forms/RegistrationForm.js
  src/pages/user/registration.js
Labels: enhancement

#681 Update dependency eslint to v5.3.0
  package.json
  yarn.lock
Labels: dependencies

#682 Release Preparations
  .travis.yml
  Dockerfile
  package.json
  src/components/common/navbar/SearchArea.js
  src/components/forms/RegistrationForm.js
  src/components/forms/userSettings/AccountDataForm.js
  src/components/forms/userSettings/UserSettingsForm.js
  src/components/layouts/EvaluationLayout.js
  src/components/questions/ActionBar.js
  src/components/questions/QuestionDetails.js
  src/components/questions/QuestionList.js
  src/components/sessions/Session.js
  src/components/sessions/SessionList.js
  src/components/sessions/SessionTimeline.js
  src/graphql/index.js
  src/graphql/mutations/ActivateAccountMutation.graphql
  src/graphql/mutations/DeleteQuestionsMutation.graphql
  src/graphql/mutations/DeleteSessionsMutation.graphql
  src/graphql/mutations/RequestAccountDeletionMutation.graphql
  src/graphql/mutations/ResolveAccountDeletionMutation.graphql
  src/klicker.conf.js
  src/lib/withSortingAndFiltering.js
  src/pages/qr.js
  src/pages/questions/index.js
  src/pages/user/activateAccount.js
  src/pages/user/deleteAccount.js
Labels: feature

#685 Update dependency react-dropzone to v4.3.0
  package.json
  yarn.lock
Labels: dependencies

#684 Update dependency recompose to v0.28.2
  package.json
  yarn.lock
Labels: dependencies

#688 Update dependency prettier to v1.14.2
  package.json
  yarn.lock
Labels: dependencies

#687 Update dependency elastic-apm-node to v1.10.2
  package.json
  yarn.lock
Labels: dependencies

#686 Update dependency semantic-ui-react to v0.82.2
  package.json
  yarn.lock
Labels: dependencies

#689 General Improvements
  package.json
  src/components/forms/questionManagement/QuestionCreationForm.js
  src/components/forms/questionManagement/QuestionEditForm.js
  src/components/questionTypes/FREE/FREEAnswerOptions.js
  src/components/questions/creation/ContentInput.js
  src/components/sessions/join/QuestionArea.js
  src/klicker.conf.js
  src/lang/de.json
  src/lang/en.json
  src/pages/join.js
  src/pages/sessions/running.js
  yarn.lock
Labels: enhancement

#692 Update dependency react-beautiful-dnd to v9
  package.json
  yarn.lock
Labels: dependencies

#693 Deleting Responses
  package.json
  src/components/evaluation/Chart.js
  src/components/evaluation/EvaluationListItem.js
  src/components/evaluation/charts/TableChart.js
  src/components/forms/RegistrationForm.js
  src/constants.js
  src/graphql/index.js
  src/graphql/mutations/DeleteResponseMutation.graphql
  src/lang/de.json
  src/lang/en.json
  src/pages/sessions/evaluation.js
  yarn.lock
Labels: feature

#706 Update dependency react-beautiful-dnd to v9.0.1
  package.json
  yarn.lock
Labels: dependencies

#705 Update dependency react-dropzone to v5
  package.json
  yarn.lock
Labels: dependencies

#704 Update apollo
  package.json
  yarn.lock
Labels: dependencies

#703 Update dependency v8n to v1.2.1
  package.json
  yarn.lock
Labels: dependencies

#700 Update dependency elastic-apm-node to v1.11.0
  package.json
  yarn.lock
Labels: dependencies

#699 Update dependency formik to v1.0.3
  package.json
  yarn.lock
Labels: dependencies

#697 Update dependency url-loader to v1.1.1
  package.json
  yarn.lock
Labels: dependencies

#696 Update node:8 Docker digest to cf4ea9
  Dockerfile
Labels: dependencies

#695 Update eslint
  package.json
  yarn.lock
Labels: dependencies

#694 Update dependency lint-staged to v7.2.2
  package.json
  yarn.lock
Labels: dependencies
