Repository uzh-bf/klicker-uzh, pull requests merged in 2018-03, with the labels that each got.

#402 General improvements
  package.json
  src/components/__snapshots__/storyshots.test.js.snap
  src/components/common/navbar/SessionArea.js
  src/components/layouts/StaticLayout.js
  src/components/layouts/StudentLayout.js
  src/components/layouts/TeacherLayout.js
  src/components/questions/QuestionSingle.js
  src/components/questions/QuestionTags.js
  src/components/sessions/creation/SessionTimelineInput.js
  src/components/sessions/join/FeedbackArea.js
  src/components/sessions/join/QuestionArea.js
  src/lib/withLogging.js
  src/pages/index.js
  yarn.lock
Labels: enhancement

#403 Pin dependency why-did-you-update to v0.1.1
  package.json
  yarn.lock
Labels: dependencies

#401 Update Dockerfile node image 8-alpine digest (6bb963)
  Dockerfile
Labels: dependencies

#404 Update dependency cypress to v2.1.0
  package.json
  yarn.lock
Labels: dependencies

#400 Update dependency prettier to v1.11.1
  package.json
  yarn.lock
Labels: dependencies

#398 Update dependency prop-types to v15.6.1
  package.json
  yarn.lock
Labels: dependencies

#394 Update dependency accepts to v1.3.5
  package.json
  yarn.lock
Labels: dependencies

#399 Update dependency nodemon to v1.17.1
  package.json
  yarn.lock
Labels: dependencies

#397 Renovate monitoring packages
  package.json
  yarn.lock
Labels: dependencies

#396 Update dependency elastic-apm-node to v1.1.0
  package.json
  yarn.lock
Labels: dependencies

#395 Update dependency dotenv to v5.0.1
  package.json
  yarn.lock
Labels: dependencies

#405 Update student mutations for string returns
  src/graphql/mutations/AddConfusionTSMutation.graphql
  src/graphql/mutations/AddFeedbackMutation.graphql
  src/graphql/mutations/AddResponseMutation.graphql
Labels: enhancement

#406 General improvements
  server.js
  src/components/layouts/StudentLayout.js
  src/components/sessions/SessionTimeline.js
  src/pages/qr.js
Labels: enhancement, feature

#407 Pie and Bar Chart Fix
  src/components/evaluation/Possibilities.js
  src/components/evaluation/charts/BarChart.js
  src/components/evaluation/charts/PieChart.js
  src/components/layouts/EvaluationLayout.js
  src/constants.js
  src/lib/index.js
  src/lib/utils/charts.js
  src/lib/utils/charts.test.js
Labels: bug

#408 Update Dockerfile node image 8-alpine digest (06ebd9)
  Dockerfile
Labels: dependencies

#409 Update dependency cross-env to v5.1.4
  package.json
  yarn.lock
Labels: dependencies

#410 Update dependency elastic-apm-node to v1.1.1
  package.json
  yarn.lock
Labels: dependencies

#411 Update dependency lru-cache to v4.1.2
  package.json
  yarn.lock
Labels: dependencies

#412 Update dependency webpack-bundle-analyzer to v2.11.1
  package.json
  yarn.lock
Labels: dependencies

#414 Update dependency babel-plugin-inline-import-graphql-ast to v2.3.3
  package.json
  yarn.lock
Labels: dependencies

#415 Update dependency eslint to v4.18.2
  package.json
  yarn.lock
Labels: dependencies

#413 Update dependency apollo-link-persisted-queries to v0.2.0
  package.json
  yarn.lock
Labels: dependencies

#416 Update dependency helmet to v3.12.0
  package.json
  yarn.lock
Labels: dependencies

#417 Update dependency moment to v2.21.0
  package.json
  yarn.lock
Labels: dependencies

#419 Update monitoring packages
  package.json
  yarn.lock
Labels: dependencies

#421 Update dependency nodemon to v1.17.2
  package.json
  yarn.lock
Labels: dependencies

#420 Update dependency express to v4.16.3
  package.json
  yarn.lock
Labels: dependencies

#422 Update dependency raven-js to v3.23.2
  package.json
  yarn.lock
Labels: dependencies

#424 Update dependency elastic-apm-node to v1.2.0
  package.json
  yarn.lock
Labels: dependencies

#425 Update storybook packages to v3.3.15
  package.json
  yarn.lock
Labels: dependencies

#426 Add Klicker UZH logo
  src/components/__snapshots__/storyshots.test.js.snap
  src/components/common/sidebar/Sidebar.js
Labels: enhancement

#267 Quick Creation and Archiving
  .storybook/addons.js
  .storybook/base.css
  .storybook/config.js
  package.json
  server.js
  src/_theme.scss
  src/components/__snapshots__/storyshots.test.js.snap
  src/components/common/ListWithHeader.js
  src/components/common/navbar/Navbar.js
  src/components/common/navbar/SearchArea.js
  src/components/common/navbar/SessionArea.js
  src/components/common/sidebar/Sidebar.js
  src/components/forms/SessionCreationForm.js
  src/components/forms/components/FormikInput.js
  src/components/forms/components/SemanticInput.js
  src/components/forms/components/index.js
  src/components/forms/forms.stories.js
  src/components/forms/index.js
  src/components/layouts/CommonLayout.js
  src/components/questionTypes/FREE/FREECreationOptions.js
  src/components/questionTypes/SC/SCCreationOptions.js
  src/components/questions/ActionBar.js
  src/components/questions/Question.js
  src/components/questions/QuestionDetails.js
  src/components/questions/QuestionList.js
  src/components/questions/TagList.js
  src/components/questions/index.js
  src/components/questions/questions.stories.js
  src/components/questions/questions.stories2.js
  src/components/sessions/Session.js
  src/components/sessions/SessionTimeline.js
  src/graphql/index.js
  src/graphql/mutations/ArchiveQuestionsMutation.graphql
  src/graphql/queries/QuestionPoolQuery.graphql
  src/lib/index.js
  src/lib/utils/analytics.js
  src/lib/utils/charts.test.js
  src/lib/utils/filters.js
  src/lib/withLogging.js
  src/lib/withSelection.js
  src/lib/withSortingAndFiltering.js
  src/pages/questions/index.js
  yarn.lock
Labels: feature

#428 Chatlio Integration
  src/components/common/navbar/SessionArea.js
  src/lib/withLogging.js
  src/pages/index.js
  src/pages/join.js
  src/pages/qr.js
  src/pages/sessions/evaluation.js
  src/pages/user/login.js
  src/pages/user/registration.js
  src/pages/user/requestPassword.js
  src/pages/user/resetPassword.js
Labels: feature

#429 Update Dockerfile node image 8-alpine digest (a55d3e)
  Dockerfile
Labels: dependencies

#430 Update dependency babel-plugin-inline-import-graphql-ast to v2.3.5
  package.json
  yarn.lock
Labels: dependencies

#431 Update dependency elastic-apm-node to v1.2.1
  package.json
  yarn.lock
Labels: dependencies

#432 Update dependency graphql to v0.13.2
  package.json
  yarn.lock
Labels: dependencies

#433 Update dependency raven-js to v3.23.3
  package.json
  yarn.lock
Labels: dependencies

#434 Update dependency semantic-ui-css to v2.3.1
  package.json
  yarn.lock
Labels: dependencies

#435 Update dependency eslint to v4.19.0
  package.json
  yarn.lock
Labels: dependencies

#436 Update dependency semantic-ui-react to v0.79.0
  package.json
  yarn.lock
Labels: dependencies

#437 Chart colors fix
  src/components/evaluation/charts/BarChart.js
  src/components/evaluation/charts/PieChart.js
  src/components/evaluation/charts/StackChart.js
Labels: bug

#438 Question Block and Session Timeline optimizations
  src/components/__snapshots__/storyshots.test.js.snap
  src/components/questionTypes/FREE/FREECreationOptions.js
  src/components/questions/QuestionBlock.js
  src/components/questions/QuestionSingle.js
  src/components/sessions/SessionTimeline.js
Labels: enhancement

#440 Rework of the Login process
  src/components/forms/QuestionEditForm.js
  src/graphql/mutations/LoginMutation.graphql
  src/pages/questions/details.js
  src/pages/user/login.js
Labels: enhancement

#442 Update dependency elastic-apm-node to v1.3.0
  package.json
  yarn.lock
Labels: dependencies

#443 Update dependency eslint to v4.19.1
  package.json
  yarn.lock
Labels: dependencies

#444 Update dependency jest to v22.4.3
  package.json
  yarn.lock
Labels: dependencies

#445 Update dependency node-sass to v4.8.3
  package.json
  yarn.lock
Labels: dependencies

#446 Update dependency raven-js to v3.24.0
  package.json
  yarn.lock
Labels: dependencies

#447 Update dependency react-apollo to v2.1.1
  package.json
  yarn.lock
Labels: dependencies

#448 Update react-dnd packages to v2.6.0
  package.json
  yarn.lock
Labels: dependencies

#449 Update dependency d3 to v5
  package.json
  yarn.lock
Labels: dependencies

#452 Update dependency next to v5.1.0
  package.json
  yarn.lock
Labels: dependencies

#453 Logout
  src/components/__snapshots__/storyshots.test.js.snap
  src/components/common/navbar/AccountArea.js
  src/components/common/navbar/Navbar.js
  src/graphql/index.js
  src/graphql/mutations/LogoutMutation.graphql
Labels: feature
