Repository uzh-bf/klicker-uzh, pull requests merged in 2018-09, with the labels that each got.

#710 Update dependency formik to v1.1.1
  package.json
  yarn.lock
Labels: dependencies

#708 Update dependency file-loader to v2
  package.json
  yarn.lock
Labels: dependencies

#680 Update storybook
  package.json
  yarn.lock
Labels: dependencies

#707 Update dependency d3 to v5.7.0
  package.json
  yarn.lock
Labels: dependencies

#711 Update apollo
  package.json
  yarn.lock
Labels: dependencies

#719 Docker in Development
  .dockerignore
  .travis.yml
  Dockerfile
  Dockerfile.dev
  docker-compose.dev.yml
  docker-compose.prod.yml
  docker-compose.yml
  package.json
  server.js
  yarn.lock
Labels: enhancement

#721 Update dependency glob to v7.1.3
  package.json
  yarn.lock
Labels: dependencies

#717 Update dependency graphql to v14
  package.json
  yarn.lock
Labels: dependencies

#690 Update dependency node-sass to v4.9.3
  package.json
  yarn.lock
Labels: dependencies

#722 Update dependency semantic-ui-react to v0.82.3
  package.json
  yarn.lock
Labels: dependencies

#698 Update dependency ioredis to v4
  package.json
  yarn.lock
Labels: dependencies, waiting

#724 Upgrade to NodeJS 10
  Dockerfile
  Dockerfile.dev
  docker-compose.prod.yml
  package.json
  src/components/confusion/ConfusionBarometer.js
  src/components/questions/Question.js
  src/components/questions/QuestionList.js
  src/components/sessions/Session.js
  src/lib/utils/filters.js
  src/next.config.js
  src/pages/questions/index.js
  src/pages/sessions/running.js
  yarn.lock
Labels: enhancement

#666 Update test
  .babelrc
  package.json
  src/components/forms/questionManagement/QuestionEditForm.js
  src/components/sessions/join/QuestionArea.js
  src/lib/utils/html.js
  src/pages/questions/create.js
  src/pages/questions/details.js
  yarn.lock
Labels: dependencies

#654 Update dependency yup to v0.26.3
  package.json
  yarn.lock
Labels: dependencies, waiting

#734 Update dependency next to v6.1.2
  package.json
  yarn.lock
Labels: dependencies

#733 Update dependency graphql to v14.0.2
  package.json
  yarn.lock
Labels: dependencies

#732 Update react to v16.5.0
  package.json
  yarn.lock
Labels: dependencies

#731 Update dependency eslint-plugin-babel to v5.2.0
  package.json
  yarn.lock
Labels: dependencies

#740 Update dependency semantic-ui-react to v0.82.5
  package.json
  yarn.lock
Labels: dependencies

#739 Update dependency babel-jest to v23.6.0
  package.json
  yarn.lock
Labels: dependencies

#738 Update dependency react-autosuggest to v9.4.1
  package.json
  yarn.lock
Labels: dependencies

#735 Update dependency recharts to v1.2.0
  package.json
  yarn.lock
Labels: dependencies

#730 Update dependency formik to v1.3.0
  package.json
  yarn.lock
Labels: dependencies

#737 Update dependency react-dropzone to v5.1.0
  package.json
  yarn.lock
Labels: dependencies

#729 Update dependency sanitize-html to v1.18.5
  package.json
  yarn.lock
Labels: dependencies

#727 Update dependency raven-js to v3.27.0
  package.json
  yarn.lock
Labels: dependencies

#725 Update dependency react-tooltip to v3.8.4
  package.json
  yarn.lock
Labels: dependencies

#741 Update dependency morgan to v1.9.1
  package.json
  yarn.lock
Labels: dependencies

#743 Update dependency yup to v0.26.5
  package.json
  yarn.lock
Labels: dependencies

#726 Update test
  package.json
  yarn.lock
Labels: dependencies

#750 Update apollo
  package.json
  yarn.lock
Labels: dependencies

#755 Update dependency eslint to v5.6.0
  package.json
  yarn.lock
Labels: dependencies

#754 Update dependency babel-plugin-react-intl to v3
  package.json
  yarn.lock
Labels: dependencies

#752 Update dependency sanitize-html to v1.19.0
  package.json
  yarn.lock
Labels: dependencies

#749 Update dependency logrocket to v0.6.17
  package.json
  yarn.lock
Labels: dependencies

#751 Update dependency react-intl to v2.5.0
  package.json
  yarn.lock
Labels: dependencies

#747 Update dependency @babel/core to v7.0.1
  package.json
  yarn.lock
Labels: dependencies

#757 Update dependency isomorphic-unfetch to v3
  package.json
  yarn.lock
Labels: dependencies

#758 Update babel to v7.1.0
  package.json
  yarn.lock
Labels: dependencies

#762 Update dependency react-intl to v2.6.0
  package.json
  yarn.lock
Labels: dependencies

#753 Update react to v16.5.2
  package.json
  yarn.lock
Labels: dependencies, waiting

#761 Update dependency subscriptions-transport-ws to v0.9.15
  package.json
  yarn.lock
Labels: dependencies

#763 Upgrade to NextJS 7.0 and Webpack 4
  .travis.yml
  package.json
  server.js
  src/components/evaluation/Chart.js
  src/components/evaluation/Statistics.js
  src/components/evaluation/VisualizationType.js
  src/components/evaluation/charts/BarChart.js
  src/components/evaluation/charts/CloudChart.js
  src/components/evaluation/charts/HistogramChart.js
  src/components/evaluation/charts/PieChart.js
  src/components/evaluation/charts/StackChart.js
  src/components/evaluation/charts/TableChart.js
  src/components/layouts/EvaluationLayout.js
  src/components/sessions/SessionTimeline.js
  src/components/sessions/join/FeedbackArea.js
  src/components/sessions/join/QuestionArea.js
  src/constants.js
  src/klicker.conf.js
  src/lang/de.json
  src/lang/en.json
  src/lib/index.js
  src/lib/utils/math.js
  src/lib/utils/math.test.js
  src/lib/withFingerprint.js
  src/lib/withLogging.js
  src/lib/withStorage.js
  src/pages/_document.js
  src/pages/index.js
  src/pages/join.js
  src/pages/qr.js
  src/pages/sessions/evaluation.js
  src/pages/user/registration.js
  yarn.lock
Labels: feature

#774 Update dependency convict to v4.4.0
  package.json
  yarn.lock
Labels: dependencies

#775 Responsive evaluation screen
  src/components/layouts/EvaluationLayout.js
Labels: enhancement

#777 Update dependency react-storybook-addon-chapters to v2.1.8
  package.json
  yarn.lock
Labels: dependencies

#776 Update dependency babel-plugin-react-intl to v3.0.1
  package.json
  yarn.lock
Labels: dependencies
