Repository uzh-bf/klicker-uzh, pull requests merged in 2018-10, with the labels that each got.

#791 Update dependency next to v7.0.1
  package.json
  yarn.lock
Labels: dependencies

#790 Update dependency @babel/types to v7.1.2
  package.json
  yarn.lock
Labels: dependencies

#789 Update dependency @babel/core to v7.1.2
  package.json
  yarn.lock
Labels: dependencies

#785 Update eslint
  package.json
  yarn.lock
Labels: dependencies

#786 Update dependency react-intl to v2.7.0
  package.json
  yarn.lock
Labels: dependencies

#783 Update dependency react-dropzone to v5.1.1
  package.json
  yarn.lock
Labels: dependencies

#782 Update dependency husky to v1.0.1
  package.json
  yarn.lock
Labels: dependencies

#778 Update dependency dayjs to v1.7.7
  package.json
  yarn.lock
Labels: dependencies

#779 Update dependency webpack to v4.20.2
  package.json
  yarn.lock
Labels: dependencies

#784 Update apollo
  package.json
  yarn.lock
Labels: dependencies

#787 Update dependency recharts to v1.3.1
  package.json
  yarn.lock
Labels: dependencies

#781 Update storybook to v4.0.0-alpha.23
  package.json
  yarn.lock
Labels: dependencies

#798 Update dependency formik to v1.3.1
  package.json
  yarn.lock
Labels: dependencies

#797 Update dependency react-dropzone to v6
  package.json
  yarn.lock
Labels: dependencies

#795 Update dependency graphql-tag to v2.10.0
  package.json
  yarn.lock
Labels: dependencies

#794 Update dependency eslint-plugin-prettier to v3
  package.json
  yarn.lock
Labels: dependencies

#793 Update dependency husky to v1.1.0
  package.json
  yarn.lock
Labels: dependencies

#792 Update apollo
  package.json
  yarn.lock
Labels: dependencies

#807 Dependencies
  package.json
  renovate.json
  src/components/common/Autosuggest.js
  src/components/common/index.js
  src/components/forms/questionManagement/QuestionCreationForm.js
  src/components/questions/creation/ContentInput.js
  src/components/questions/creation/TagInput.js
  src/components/sessions/SessionTimeline.js
  src/klicker.conf.js
  src/lib/utils/__snapshots__/html.test.js.snap
  src/pages/join.js
  src/pages/qr.js
  src/pages/questions/create.js
  yarn.lock
Labels: dependencies, enhancement

#824 Update dependency next to v7.0.2
  package.json
  yarn.lock
Labels: dependencies

#826 Update dependency nodemon to v1.18.5
  package.json
  yarn.lock
Labels: dependencies

#823 Update dependency mathjs to v5.2.3
  package.json
  yarn.lock
Labels: dependencies

#822 Update dependency localforage to v1.7.3
  package.json
  yarn.lock
Labels: dependencies

#816 Update dependency husky to v1.1.2
  package.json
  yarn.lock
Labels: dependencies

#821 Update dependency immutable to v4.0.0-rc.12
  package.json
  yarn.lock
Labels: dependencies

#815 Update dependency elastic-apm-node to v1.13.0
  package.json
  yarn.lock
Labels: dependencies

#814 Update dependency helmet to v3.14.0
  package.json
  yarn.lock
Labels: dependencies

#813 Update dependency fingerprintjs2 to v1.8.5
  package.json
  yarn.lock
Labels: dependencies

#810 Update dependency dotenv to v6.1.0
  package.json
  yarn.lock
Labels: dependencies

#809 Update dependency @babel/types to v7.1.3
  package.json
  yarn.lock
Labels: dependencies

#808 Update Apollo GraphQL packages
  package.json
  yarn.lock
Labels: dependencies

#811 Update dependency eslint to v5.8.0
  package.json
  yarn.lock
Labels: dependencies

#756 Update semantic-ui
  package.json
  yarn.lock
Labels: dependencies, waiting

#812 Update dependency express to v4.16.4
  package.json
  yarn.lock
Labels: dependencies

#825 Update dependency node-sass to v4.9.4
  package.json
  yarn.lock
Labels: dependencies
