Repository uzh-bf/klicker-uzh, pull requests merged in 2019-04, with the labels that each got.

#916 Export evaluation in CSV format #88
  package-lock.json
  package.json
  src/components/evaluation/CsvExport.js
  src/components/evaluation/index.js
  src/components/layouts/EvaluationLayout.js
  src/pages/sessions/evaluation.js
Labels: feature

#914 Update dependency @types/react-dom to v16.8.4
  package-lock.json
  package.json
Labels: dependencies

#913 Update dependency @types/next to v8.0.3
  package-lock.json
  package.json
Labels: dependencies

#896 Update babel monorepo to v7.4.3
  package-lock.json
  package.json
Labels: dependencies

#900 Update dependency lint-staged to v8.1.5
  package-lock.json
  package.json
Labels: dependencies

#903 Update dependency dayjs to v1.8.12
  package-lock.json
  package.json
Labels: dependencies

#904 Update dependency elastic-apm-node to v2.9.0
  package-lock.json
  package.json
Labels: dependencies

#895 Update Apollo GraphQL packages
  package-lock.json
  package.json
Labels: dependencies

#898 Update dependency babel-plugin-import-graphql to v2.7.0
  package-lock.json
  package.json
Labels: dependencies

#899 Update dependency draft-js-export-html to v1.3.3
  package-lock.json
  package.json
Labels: dependencies

#905 Update dependency helmet to v3.16.0
  package-lock.json
  package.json
Labels: dependencies

#908 Update dependency cypress to v3.2.0
  package-lock.json
  package.json
Labels: dependencies

#910 Update dependency react-beautiful-dnd to v10.1.1
  package-lock.json
  package.json
Labels: dependencies

#911 Update dependency react-sortable-hoc to v1.8.3
  package-lock.json
  package.json
Labels: dependencies

#906 Update dependency mathjs to v5.9.0
  package-lock.json
  package.json
Labels: dependencies

#915 Added "Cancel Session" functionality (frontend)
  src/components/sessions/CancelModal.js
  src/components/sessions/SessionTimeline.js
  src/components/sessions/index.js
  src/graphql/index.js
  src/graphql/mutations/CancelSessionMutation.graphql
  src/lang/de.json
  src/lang/en.json
  src/pages/sessions/running.js
Labels: feature, waiting

#912 Update dependency react-storybook-addon-chapters to v3.1.3
  package-lock.json
  package.json
Labels: dependencies

#909 Update dependency d3 to v5.9.2
  package-lock.json
  package.json
Labels: dependencies

#907 Update dependency babel-plugin-inline-dotenv to v1.3.1
  package-lock.json
  package.json
Labels: dependencies

#897 Update dependency acorn to v6.1.1
  package-lock.json
  package.json
Labels: dependencies

#902 Update dependency @types/react to v16.8.13
  package-lock.json
  package.json
Labels: dependencies

#901 Update dependency @types/lodash to v4.14.123
  package-lock.json
  package.json
Labels: dependencies

#921 Update dependency compression to v1.7.4
  package-lock.json
  package.json
Labels: dependencies

#922 Update dependency formik to v1.5.2
  package-lock.json
  package.json
Labels: dependencies

#923 Update dependency graphql to v14.2.1
  package-lock.json
  package.json
Labels: dependencies

#924 Update dependency ioredis to v4.9.0
  package-lock.json
  package.json
Labels: dependencies

#925 Update dependency logrocket to v0.6.20
  package-lock.json
  package.json
Labels: dependencies

#926 Update dependency nodemon to v1.18.11
  package-lock.json
  package.json
Labels: dependencies

#928 Update dependency @types/react to v16.8.14
  package-lock.json
  package.json
Labels: dependencies

#929 Update dependency elastic-apm-node to v2.10.0
  package-lock.json
  package.json
Labels: dependencies

#930 Update dependency next to v8.1.0
  package-lock.json
  package.json
Labels: dependencies

#931 Update dependency prettier to v1.17.0
  package-lock.json
  package.json
Labels: dependencies

#933 Update dependency react-testing-library to v6.1.2
  package-lock.json
  package.json
Labels: dependencies

#932 Update dependency prismjs to v1.16.0
  package-lock.json
  package.json
Labels: dependencies

#940 Update dependency node-sass to v4.12.0
  package-lock.json
  package.json
Labels: dependencies

#939 Update dependency logrocket to v0.6.21
  package-lock.json
  package.json
Labels: dependencies

#938 Update dependency formik to v1.5.4
  package-lock.json
  package.json
Labels: dependencies

#937 Update dependency dayjs to v1.8.13
  package-lock.json
  package.json
Labels: dependencies

#935 Update babel monorepo to v7.4.4
  package-lock.json
  package.json
Labels: dependencies

#936 Update dependency @types/next to v8.0.4
  package-lock.json
  package.json
Labels: dependencies
