Repository uzh-bf/klicker-uzh, pull requests merged in 2025-08, with the labels that each got.

#4814 fix: ensure that no points are shown for non-gamified activities
  apps/frontend-manage/src/components/activities/overview/ActivityDetailsModal.tsx
  apps/frontend-pwa/src/components/course/SuspendedGroupView.tsx
  cypress/cypress/e2e/O-live-quiz-workflow.cy.ts
  cypress/cypress/e2e/P-microlearning-workflow.cy.ts
  cypress/cypress/e2e/Q-practice-quiz-workflow.cy.ts
  cypress/cypress/fixtures/O-live-quiz.json
  cypress/cypress/fixtures/P-microlearning.json
  cypress/cypress/fixtures/Q-practice-quiz.json
  cypress/cypress/support/commands.ts
  packages/graphql/src/graphql/ops/FActivityDetails.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/activities.ts
  packages/graphql/src/services/activities.ts
  packages/graphql/src/services/groups.ts
Labels: size:XXL

#4806 enhance(apps/frontend-manage): extend activity details with student preview
  apps/frontend-manage/src/components/activities/overview/ActivityDetailsModal.tsx
  apps/frontend-manage/src/components/activities/overview/ActivityDetailsStack.tsx
  apps/frontend-manage/src/components/activities/overview/ActivityOutdatedElementWarning.tsx
  apps/frontend-manage/src/components/activities/overview/ActivityPointsTable.tsx
  apps/frontend-manage/src/components/questions/manipulation/StudentElementPreview.tsx
  apps/frontend-manage/src/components/questions/manipulation/StudentElementPreviewActivityDetails.tsx
  apps/frontend-manage/src/components/questions/manipulation/StudentElementPreviewWrapper.tsx
  apps/frontend-pwa/src/components/course/SuspendedGroupView.tsx
  cypress/cypress/e2e/0-baseline-ops.cy.ts
  cypress/cypress/e2e/A-login-workflow.cy.ts
  cypress/cypress/e2e/B-feature-access-workflow.cy.ts
  cypress/cypress/e2e/C-control-workflow.cy.ts
  cypress/cypress/e2e/D-elements-content-workflow.cy.ts
  cypress/cypress/e2e/E-elements-flashcards-workflow.cy.ts
  cypress/cypress/e2e/F-elements-sc-workflow.cy.ts
  cypress/cypress/e2e/G-elements-mc-workflow.cy.ts
  cypress/cypress/e2e/H-elements-kprim-workflow.cy.ts
  cypress/cypress/e2e/I-elements-numerical-workflow.cy.ts
  cypress/cypress/e2e/J-elements-free-text-workflow.cy.ts
  cypress/cypress/e2e/K-elements-selection-workflow.cy.ts
  cypress/cypress/e2e/L-elements-case-study-workflow.cy.ts
  cypress/cypress/e2e/MA-elements-operations-workflow.cy.ts
  cypress/cypress/e2e/MB-instance-updates-workflow.cy.ts
  cypress/cypress/e2e/N-course-workflow.cy.ts
  cypress/cypress/e2e/O-live-quiz-workflow.cy.ts
  cypress/cypress/e2e/P-microlearning-workflow.cy.ts
  cypress/cypress/e2e/Q-practice-quiz-workflow.cy.ts
  cypress/cypress/e2e/R-bookmarking-workflow.cy.ts
  cypress/cypress/e2e/S-group-activity-workflow.cy.ts
  cypress/cypress/e2e/T-resources-workflow.cy.ts
  cypress/cypress/e2e/U-catalog-workflow.cy.ts
  cypress/cypress/e2e/V-template-workflow.cy.ts
  cypress/cypress/e2e/W-activity-log-workflow.cy.ts
  cypress/cypress/fixtures/O-live-quiz.json
  cypress/cypress/fixtures/P-microlearning.json
  cypress/cypress/fixtures/Q-practice-quiz.json
  cypress/cypress/fixtures/S-group-activity.json
  cypress/cypress/support/commands.ts
  packages/graphql/src/graphql/ops/FActivityDetails.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/activities.ts
  packages/graphql/src/services/activities.ts
  packages/graphql/src/services/groups.ts
  packages/graphql/src/services/stacks.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/shared-components/src/evaluation/ChoiceFeedback.tsx
Labels: feature, size:XXL

#4815 fix(apps/olat-api): make sure that permissions on course are correctly validated during OLAT API request
  apps/frontend-pwa/src/pages/course/[courseId]/createAccount.tsx
  apps/olat-api/package.json
  apps/olat-api/src/services.ts
  apps/olat-api/test/docker/Dockerfile.test
  apps/olat-api/test/helpers.ts
  pnpm-lock.yaml
Labels: security, size:L

#4816 fix(apps/frontend-*): ensure that locale is correctly handled for redirects and evaluation links
  apps/frontend-manage/src/components/activities/actions/useLiveQuizActions.ts
  apps/frontend-manage/src/components/activities/actions/useMicroLearningActions.ts
  apps/frontend-manage/src/components/activities/actions/usePracticeQuizActions.ts
  apps/frontend-manage/src/pages/analytics/[courseId]/quizzes/[id].tsx
  apps/frontend-manage/src/pages/courses/[id].tsx
  apps/frontend-manage/src/pages/microLearning/[id]/evaluation.tsx
  apps/frontend-manage/src/pages/practiceQuiz/[id]/evaluation.tsx
  apps/frontend-manage/src/pages/quizzes/[id]/evaluation.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/createAccount.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/docs/index.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/index.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/join.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/liveQuizzes/[id].tsx
  apps/frontend-pwa/src/pages/course/[courseId]/liveQuizzes/index.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/liveQuizzes/overview.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/microLearnings/[id]/index.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/microLearnings/index.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/microLearnings/overview.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/microlearning/[id]/[ix].tsx
  apps/frontend-pwa/src/pages/course/[courseId]/microlearning/[id]/evaluation.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/microlearning/[id]/index.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/practice.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/practiceQuizzes/[id].tsx
  apps/frontend-pwa/src/pages/course/[courseId]/practiceQuizzes/index.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/practiceQuizzes/overview.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/quiz/[id].tsx
  apps/frontend-pwa/src/pages/createAccount.tsx
  apps/frontend-pwa/src/pages/editProfile.tsx
  apps/frontend-pwa/src/pages/join/[shortname].tsx
  apps/frontend-pwa/src/pages/session/[id].tsx
Labels: size:L

#4817 fix(apps/frontend-manage): make sure to show element edit content recovery modal also on title click
  apps/frontend-manage/src/components/activities/creation/groupActivity/GroupActivitySettingsStep.tsx
  apps/frontend-manage/src/components/activities/creation/groupActivity/GroupActivityStackClues.tsx
  apps/frontend-manage/src/components/activities/creation/liveQuiz/LiveQuizSettingsStep.tsx
  apps/frontend-manage/src/components/activities/creation/microLearning/MicroLearningSettingsStep.tsx
  apps/frontend-manage/src/components/activities/creation/practiceQuiz/PracticeQuizSettingsStep.tsx
  apps/frontend-manage/src/components/evaluation/feedbacks/SingleFeedback.tsx
  apps/frontend-manage/src/components/questions/Element.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyCasesFields.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyOptions.tsx
  packages/prisma/src/data/seedTEST.ts
Labels: enhancement, size:M

#4820 enhance(apps/docs): update documentation of LTI integration with new functionalities
  apps/docs/docs/tutorials/lti_integration.mdx
  apps/docs/static/img/lti_olat/lti_link_account_management.png
  apps/docs/static/img/lti_olat/lti_link_documentation.png
  apps/docs/static/img/lti_olat/lti_link_leaderboard.png
  apps/docs/static/img/lti_olat/lti_link_live_quizzes.png
  apps/docs/static/img/lti_olat/olat_pq_integration_link.png
  apps/frontend-manage/src/components/courses/CourseOverviewHeader.tsx
  cypress/cypress/e2e/O-live-quiz-workflow.cy.ts
Labels: enhancement, size:L

#4828 feat: introduce functionality to mark activities as reviewed
  apps/auth/package.json
  apps/docs/docs/tutorials/review.mdx
  apps/docs/package.json
  apps/frontend-control/package.json
  apps/frontend-manage/package.json
  apps/frontend-manage/src/components/activities/overview/ActivityActions.tsx
  apps/frontend-manage/src/components/activities/overview/ActivityListEntry.tsx
  apps/frontend-manage/src/components/activities/overview/ActivityOutdatedElementWarning.tsx
  apps/frontend-manage/src/components/activities/overview/ActivityReviewStatus.tsx
  apps/frontend-manage/src/components/activities/overview/GroupActivityActions.tsx
  apps/frontend-manage/src/components/activities/overview/LiveQuizActions.tsx
  apps/frontend-manage/src/components/activities/overview/MicrolearningActions.tsx
  apps/frontend-manage/src/components/activities/overview/PracticeQuizActions.tsx
  apps/frontend-manage/src/components/activities/overview/details/ActivityDetailsModal.tsx
  apps/frontend-manage/src/components/activities/overview/details/ActivityInformation.tsx
  apps/frontend-manage/src/components/activities/overview/details/ActivityOverviewTable.tsx
  apps/frontend-manage/src/components/activities/overview/details/ActivityReviewButton.tsx
  apps/frontend-manage/src/components/courses/modals/CourseManipulationModal.tsx
  apps/frontend-manage/src/components/elements/manipulation/ElementEditModal.tsx
  apps/frontend-pwa/package.json
  apps/office-addin/package.json
  cypress/cypress/e2e/N-course-workflow.cy.ts
  cypress/cypress/e2e/P-microlearning-workflow.cy.ts
  cypress/cypress/e2e/Q-practice-quiz-workflow.cy.ts
  cypress/cypress/e2e/S-group-activity-workflow.cy.ts
  cypress/cypress/e2e/X-review-workflow.cy.ts
  cypress/cypress/fixtures/X-review.json
  cypress/cypress/support/commands.ts
  packages/graphql/src/graphql/ops/FActivityInfoData.graphql
  packages/graphql/src/graphql/ops/MSetActivityReviewStatus.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/activities.ts
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/schema/practiceQuiz.ts
  packages/graphql/src/services/activities.ts
  packages/graphql/src/services/courses.ts
  packages/graphql/src/services/groups.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/graphql/src/services/microLearning.ts
  packages/graphql/src/services/practiceQuizzes.ts
  packages/graphql/src/services/questions.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/markdown/package.json
  packages/prisma/src/prisma/migrations/20250809100538_activity_review_status/migration.sql
  packages/prisma/src/prisma/schema/quiz.prisma
  packages/shared-components/package.json
  packages/transactional/package.json
  pnpm-lock.yaml
Labels: feature, size:XXL

#4832 chore(cypress): implement end-to-end testing for element batch operations
  apps/frontend-manage/src/components/elements/Element.tsx
  apps/frontend-manage/src/components/elements/manipulation/ElementBatchOperationsModal.tsx
  apps/frontend-manage/src/components/elements/manipulation/ElementFormScoringSection.tsx
  apps/frontend-manage/src/components/elements/manipulation/batchOperations/ElementMultiplierCard.tsx
  apps/frontend-manage/src/components/elements/manipulation/batchOperations/SelectedElementsList.tsx
  apps/frontend-manage/src/components/elements/tags/TagList.tsx
  apps/frontend-manage/src/pages/index.tsx
  cypress/cypress.config.ts
  cypress/cypress/e2e/X-review-workflow.cy.ts
  cypress/cypress/support/commands.ts
Labels: feature, size:XL

#4836 chore(cypress): implement end-to-end testing for activity list batch operations
  apps/frontend-manage/src/pages/activities.tsx
  cypress/cypress/e2e/W-activity-log-workflow.cy.ts
  cypress/cypress/e2e/X-review-workflow.cy.ts
  cypress/cypress/fixtures/X-review.json
  cypress/cypress/fixtures/questions.json
  cypress/cypress/support/commands.ts
  packages/graphql/src/services/activities.ts
  packages/graphql/test/activityBatchOperations.test.ts
  packages/graphql/test/catalogSharing.test.ts
Labels: enhancement, size:XL

#4837 enhance: correctly handle scheduled practice quizzes for activity batch operations and improve UX
  apps/frontend-manage/src/components/activities/overview/ActivityBatchOperationsModal.tsx
  apps/frontend-manage/src/components/activities/overview/ActivityListEntry.tsx
  apps/frontend-manage/src/components/activities/overview/ActivityListSelectAllCheckbox.tsx
  apps/frontend-manage/src/components/activities/overview/ActivityNameChangeModal.tsx
  apps/frontend-manage/src/components/activities/overview/batchOperations/ActivityCourseCard.tsx
  apps/frontend-manage/src/components/activities/overview/batchOperations/ActivityLiveQuizPointsCard.tsx
  apps/frontend-manage/src/components/activities/overview/batchOperations/ActivityMultiplierCard.tsx
  apps/frontend-manage/src/components/activities/overview/batchOperations/types.ts
  apps/frontend-manage/src/pages/activities.tsx
  apps/frontend-manage/src/pages/index.tsx
  cypress/cypress/e2e/X-review-workflow.cy.ts
  packages/graphql/src/services/activities.ts
  packages/graphql/src/services/groups.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/graphql/src/services/microLearning.ts
  packages/graphql/src/services/practiceQuizzes.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:L

#4838 enhance(apps/docs): update documentation with new review and batch operation functionalities
  apps/docs/docs/tutorials/activity_batch_operations.mdx
  apps/docs/docs/tutorials/catalog_sharing.mdx
  apps/docs/docs/tutorials/direct_sharing.mdx
  apps/docs/docs/tutorials/element_batch_operations.mdx
  apps/docs/docs/tutorials/element_updates_activities.mdx
  apps/docs/docs/tutorials/live_quiz.mdx
  apps/docs/docs/tutorials/permissions_groups.mdx
  apps/docs/docs/tutorials/ppt_integration.mdx
  apps/docs/docs/tutorials/review.mdx
  apps/docs/sidebars.js
  apps/docs/static/img/review/activity_batch_operations.png
  apps/docs/static/img/review/activity_list_batch_operations.png
  apps/docs/static/img/review/activity_review_status.png
  apps/docs/static/img/review/element_batch_operations.png
  apps/docs/static/img/review/element_list_batch_operations.png
  apps/docs/static/img/review/live_quiz_details_modal.png
Labels: enhancement, size:L

#4840 enhance(apps/frontend-manage): re-open activity details view after editing element in activity context
  apps/docs/docs/tutorials/review.mdx
  apps/frontend-manage/src/components/activities/overview/ActivityListEntry.tsx
  apps/frontend-manage/src/components/activities/overview/details/ActivityDetailsModal.tsx
  apps/frontend-manage/src/components/activities/overview/details/ActivityOverviewTable.tsx
  apps/frontend-manage/src/components/activities/overview/details/ActivityReviewButton.tsx
  apps/frontend-manage/src/components/elements/manipulation/ElementEditModal.tsx
  apps/frontend-manage/src/pages/activities.tsx
  packages/graphql/src/graphql/ops/QGetActivityDetails.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/activities.ts
  packages/graphql/src/services/activities.ts
Labels: enhancement, size:L

#4843 enhance(apps/frontend-manage): add multiplier and review filters to element and activity lists
  apps/analytics/prisma/schema/py.prisma
  apps/frontend-manage/src/components/activities/overview/ActivityList.tsx
  apps/frontend-manage/src/components/activities/overview/ActivityOverviewFilters.tsx
  apps/frontend-manage/src/components/activities/overview/ActivityReviewStatus.tsx
  apps/frontend-manage/src/components/common/Pagination.tsx
  apps/frontend-manage/src/components/courses/GroupActivityList.tsx
  apps/frontend-manage/src/components/courses/LiveQuizList.tsx
  apps/frontend-manage/src/components/courses/MicroLearningList.tsx
  apps/frontend-manage/src/components/courses/PracticeQuizList.tsx
  apps/frontend-manage/src/components/elements/ElementList.tsx
  apps/frontend-manage/src/components/elements/tags/FilterList.tsx
  apps/frontend-manage/src/lib/hooks/useActivitySortingAndFiltering.ts
  apps/frontend-manage/src/lib/hooks/useSortingAndFiltering.ts
  apps/frontend-manage/src/pages/activities.tsx
  apps/frontend-manage/src/pages/index.tsx
  cypress/cypress/e2e/X-review-workflow.cy.ts
  packages/graphql/src/graphql/ops/QGetUserActivities.graphql
  packages/graphql/src/graphql/ops/QGetUserElements.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/query.ts
  packages/graphql/src/services/activities.ts
  packages/graphql/src/services/elements.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: feature, size:XXL

#4844 feat: support gamified live quizzes without assignment to gamified course
  apps/auth/package.json
  apps/docs/package.json
  apps/frontend-control/package.json
  apps/frontend-manage/package.json
  apps/frontend-manage/src/components/activities/creation/WizardLayout.tsx
  apps/frontend-manage/src/components/activities/creation/liveQuiz/AdvancedLiveQuizSettings.tsx
  apps/frontend-manage/src/components/activities/creation/liveQuiz/LiveQuizCourseMonitor.tsx
  apps/frontend-manage/src/components/activities/creation/liveQuiz/LiveQuizSettingsStep.tsx
  apps/frontend-manage/src/components/activities/creation/liveQuiz/LiveQuizWizard.tsx
  apps/frontend-manage/src/components/activities/creation/liveQuiz/submitLiveQuizForm.tsx
  apps/frontend-manage/src/components/activities/overview/details/ActivityDetailsModal.tsx
  apps/frontend-manage/src/components/activities/overview/details/ActivityReviewButton.tsx
  apps/frontend-manage/src/components/liveQuiz/cockpit/LiveQuizTimeline.tsx
  apps/frontend-manage/src/pages/index.tsx
  apps/frontend-manage/src/pages/quizzes/[id]/evaluation.tsx
  apps/frontend-pwa/package.json
  apps/frontend-pwa/src/components/Layout.tsx
  apps/frontend-pwa/src/components/common/Header.tsx
  apps/frontend-pwa/src/components/common/LiveQuizLeaderboard.tsx
  apps/frontend-pwa/src/components/liveQuiz/AccountSelector.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/index.tsx
  apps/frontend-pwa/src/pages/session/[id].tsx
  apps/office-addin/package.json
  packages/graphql/src/graphql/ops/QGetActivityTemplate.graphql
  packages/graphql/src/graphql/ops/QGetRunningLiveQuiz.graphql
  packages/graphql/src/graphql/ops/QGetSingleLiveQuiz.graphql
  packages/graphql/src/graphql/ops/QSelf.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/liveQuiz.ts
  packages/graphql/src/schema/query.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/graphql/src/services/participants.ts
  packages/graphql/test/assessmentSettings.test.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/markdown/package.json
  packages/shared-components/package.json
  packages/shared-components/src/Leaderboard.tsx
  packages/shared-components/src/Podium.tsx
  packages/transactional/package.json
  pnpm-lock.yaml
Labels: feature, size:XL

#4845 fix(packages/shared-components): make sure that quote and unnumbered list syntax in slate paragraph text is escaped on conversion to markdown
  packages/shared-components/src/utils/slateMdConversion.ts
Labels: size:S

#4850 fix(apps/frontend-manage): resolve issues with cache updates on removal of own object permissions and other minor bugfixes
  apps/docs/docs/tutorials/live_quiz.mdx
  apps/frontend-manage/src/components/activities/creation/liveQuiz/LiveQuizSettingsStep.tsx
  apps/frontend-manage/src/components/activities/overview/ActivityNameChangeModal.tsx
  apps/frontend-manage/src/components/activities/templates/liveQuiz/LiveQuizTemplateSettings.tsx
  apps/frontend-manage/src/components/sharing/DirectSharingForm.tsx
  apps/frontend-manage/src/components/sharing/ExistingPermissionEntries.tsx
  apps/frontend-manage/src/components/sharing/GrantedPermissionsTable.tsx
  apps/frontend-manage/src/components/sharing/ObjectSharingModal.tsx
  apps/frontend-manage/src/components/sharing/ObjectSharingModalWrapper.tsx
  apps/frontend-manage/src/components/sharing/usePermissionRevocation.ts
  apps/frontend-manage/src/pages/courses/[id].tsx
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: size:L

#4852 enhance: hide results of active live quiz blocks in browser evaluations
  apps/frontend-manage/src/components/evaluation/ActivityEvaluation.tsx
  apps/frontend-manage/src/components/evaluation/ElementEvaluation.tsx
  apps/frontend-manage/src/components/evaluation/EvaluationFooter.tsx
  apps/frontend-manage/src/pages/quizzes/[id]/evaluation.tsx
  cypress/cypress/e2e/O-live-quiz-workflow.cy.ts
  cypress/cypress/e2e/V-template-workflow.cy.ts
  packages/graphql/src/graphql/ops/FEvaluationResults.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/evaluation.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/graphql/src/services/stacks.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:L

#4857 enhance(apps/docs): add grading logic description for selection questions and case studies
  apps/docs/docs/gamification/experience.mdx
  apps/docs/docs/gamification/grading_logic.mdx
  apps/docs/docs/gamification/overview.mdx
  apps/docs/docs/getting_started/core_concepts.mdx
  apps/docs/docs/getting_started/welcome.mdx
  apps/docs/docs/student_tutorials/course_leaderboard.mdx
  apps/docs/docs/student_tutorials/groups_activities.mdx
  apps/docs/docs/student_tutorials/klickeruzh_app.mdx
  apps/docs/docs/student_tutorials/live_quiz.mdx
  apps/docs/docs/student_tutorials/microlearning.mdx
  apps/docs/docs/student_tutorials/practice_quiz.mdx
  apps/docs/docs/student_tutorials/student_accounts.mdx
  apps/docs/docs/tutorials/course_management.mdx
  apps/docs/docs/tutorials/delegated_access.mdx
  apps/docs/docs/tutorials/element_management.mdx
  apps/docs/docs/tutorials/element_stacks.mdx
  apps/docs/docs/tutorials/group_activity.mdx
  apps/docs/docs/tutorials/live_qa.mdx
  apps/docs/docs/tutorials/live_quiz.mdx
  apps/docs/docs/tutorials/lti_integration.mdx
  apps/docs/docs/tutorials/microlearning.mdx
  apps/docs/docs/tutorials/ppt_integration.mdx
  apps/docs/docs/tutorials/practice_quiz.mdx
  apps/docs/docs/tutorials/supported_element_types.mdx
Labels: enhancement, size:L

#4859 fix(apps/frontend-manage): ensure that element edit modal is not closed on element status change
  apps/frontend-manage/src/components/elements/manipulation/ElementEditModal.tsx
  apps/frontend-manage/src/components/elements/manipulation/ElementInformationFields.tsx
Labels: size:XS

#4826 fix(packages/prisma): fix formula parsing and update flashcards sets for BF1
  packages/prisma/src/data/helpers.ts
  packages/prisma/src/data/seedFlashcards.ts
Labels: size:L

#4862 enhance: add dedicated error page that handles server side errors and fix errors on activity overviews
  apps/frontend-pwa/src/lib/getParticipantToken.ts
  apps/frontend-pwa/src/pages/course/[courseId]/docs/index.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/index.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/liveQuizzes/overview.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/microLearnings/[id]/index.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/microLearnings/overview.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/practice.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/practiceQuizzes/[id].tsx
  apps/frontend-pwa/src/pages/course/[courseId]/practiceQuizzes/overview.tsx
  apps/frontend-pwa/src/pages/createAccount.tsx
  apps/frontend-pwa/src/pages/editProfile.tsx
  apps/frontend-pwa/src/pages/join/[shortname].tsx
  apps/frontend-pwa/src/pages/serverError.tsx
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:XXL
