Repository uzh-bf/klicker-uzh, pull requests merged in 2025-09, with the labels that each got.

#4869 fix(packages/graphql): make sure that entire histogram bar is covered by case study likert criterion solution illustration
  packages/graphql/src/services/stacks.ts
Labels: enhancement, size:S

#4875 enhance: restrict the available actions in connection with aborting, deleting or re-assigning assessment live quizzes
  apps/frontend-manage/src/components/activities/ActivityCreation.tsx
  apps/frontend-manage/src/components/activities/creation/liveQuiz/LiveQuizSettingsStep.tsx
  apps/frontend-manage/src/components/activities/overview/LiveQuizActions.tsx
  apps/frontend-manage/src/components/activities/templates/liveQuiz/LiveQuizTemplateSettings.tsx
  apps/frontend-manage/src/components/evaluation/ElementEvaluation.tsx
  apps/frontend-manage/src/components/liveQuiz/cockpit/CloseBlockConfirmDialog.tsx
  apps/frontend-manage/src/components/liveQuiz/cockpit/LiveQuizBlock.tsx
  apps/frontend-manage/src/components/liveQuiz/cockpit/LiveQuizCountdown.tsx
  apps/frontend-manage/src/components/liveQuiz/cockpit/LiveQuizTimeline.tsx
  apps/frontend-manage/src/pages/quizzes/[id]/cockpit.tsx
  apps/frontend-pwa/src/pages/join.tsx
  cypress/cypress.config.ts
  cypress/cypress/e2e/O-live-quiz-workflow.cy.ts
  packages/graphql/src/graphql/ops/QGetActiveUserCourses.graphql
  packages/graphql/src/graphql/ops/QGetCockpitQuiz.graphql
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/server.json
  packages/graphql/src/services/activities.ts
  packages/graphql/src/services/courses.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/graphql/test/access.test.ts
  packages/graphql/test/activityBatchOperations.test.ts
  packages/graphql/test/activitySharing.test.ts
  packages/graphql/test/assessmentRestrictions.test.ts
  packages/graphql/test/assessmentSettings.test.ts
  packages/graphql/test/catalogSharing.test.ts
  packages/graphql/test/courseSharing.test.ts
  packages/graphql/test/elementSharing.test.ts
  packages/graphql/test/helpers.ts
  packages/graphql/test/resourceSharing.test.ts
  packages/graphql/test/resources.test.ts
  packages/graphql/test/template.test.ts
  packages/graphql/test/userGroups.test.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/prisma/src/prisma/schema/migrations/20250904201500_add_pin_to_user_activities_view/migration.sql
Labels: feature, size:XXL

#4871 refactor: migrate from jsonwebtoken to jose
  .github/workflows/test-util.yml
  .serena/.gitignore
  apps/auth/package.json
  apps/auth/src/pages/api/auth/[...nextauth].ts
  apps/backend-docker/package.json
  apps/backend-docker/src/app.ts
  apps/frontend-control/package.json
  apps/frontend-pwa/package.json
  apps/frontend-pwa/src/lib/getParticipantToken.ts
  apps/frontend-pwa/src/pages/createAccount.tsx
  apps/func-incoming-responses/package.json
  apps/func-incoming-responses/src/index.ts
  apps/func-incoming-responses/tsconfig.json
  apps/func-response-processor/package.json
  apps/func-response-processor/src/index.ts
  apps/func-response-processor/tsconfig.json
  apps/hatchet-worker-response-processor/package.json
  apps/hatchet-worker-response-processor/src/processor.ts
  apps/lti/package.json
  apps/lti/src/index.ts
  cypress/cypress.config.ts
  cypress/cypress/support/commands.ts
  packages/graphql/package.json
  packages/graphql/src/scripts/impersonateParticipant.ts
  packages/graphql/src/scripts/impersonateUser.ts
  packages/graphql/src/services/accounts.ts
  packages/graphql/src/services/participants.ts
  packages/util/package.json
  packages/util/src/index.ts
  packages/util/src/jwt.ts
  packages/util/test/jwt.test.ts
  pnpm-lock.yaml
  project/archive/PLAN-jose-jwt.md
  project/future/PLAN-go-processor.md
  project/future/PLAN-jwt-security-enhancements.md
  project/future/PLAN-k6-load-testing.md
  project/future/RESEARCH-go-processor.md
Labels: size:XL

#4878 enhance: ensure uniqueness of live quiz assessment pins through retries and improve UX of assessment quizzes
  apps/frontend-manage/src/components/activities/creation/liveQuiz/LiveQuizSettingsStep.tsx
  apps/frontend-manage/src/components/activities/overview/details/ActivityDetailsActions.tsx
  apps/frontend-manage/src/components/activities/overview/details/ActivityDetailsModal.tsx
  apps/frontend-manage/src/components/activities/overview/details/ActivityInformation.tsx
  apps/frontend-manage/src/components/activities/overview/details/ActivityOverviewTable.tsx
  apps/frontend-manage/src/components/liveQuiz/cockpit/LiveQuizTimeline.tsx
  apps/frontend-pwa/src/pages/join/[shortname].tsx
  cypress/cypress/e2e/MA-elements-operations-workflow.cy.ts
  cypress/cypress/e2e/MB-instance-updates-workflow.cy.ts
  cypress/cypress/e2e/N-course-workflow.cy.ts
  cypress/cypress/e2e/O-live-quiz-workflow.cy.ts
  cypress/cypress/e2e/P-microlearning-workflow.cy.ts
  cypress/cypress/e2e/R-bookmarking-workflow.cy.ts
  cypress/cypress/e2e/S-group-activity-workflow.cy.ts
  cypress/cypress/e2e/W-activity-log-workflow.cy.ts
  cypress/cypress/e2e/X-review-workflow.cy.ts
  cypress/cypress/support/commands.ts
  packages/graphql/src/graphql/ops/QGetActivityDetails.graphql
  packages/graphql/src/graphql/ops/QGetShortnameQuizzes.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/activities.ts
  packages/graphql/src/schema/liveQuiz.ts
  packages/graphql/src/schema/query.ts
  packages/graphql/src/services/activities.ts
  packages/graphql/src/services/liveQuizzes.ts
Labels: enhancement, size:XL

#4882 fix(packages/graphql): ensure that direct permissions of activities are revoked correctly on soft deletion
  packages/graphql/src/services/groups.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/graphql/src/services/microLearning.ts
  packages/graphql/src/services/practiceQuizzes.ts
  packages/graphql/src/services/resources.ts
Labels: size:S

#4887 chore: remove old azure functions logic for live quiz submissions and corresponding CI actions
  .github/workflows/check-types.yml
  .github/workflows/v3_klickeruzhprod-response-processor(qa).yml
  .github/workflows/v3_klickeruzhprod-response-processor-v2(qa).yml
  .github/workflows/v3_klickeruzhprod-response-processor-v2.yml
  .github/workflows/v3_klickeruzhprod-response-processor.yml
  .github/workflows/v3_klickeruzhprod-responses(qa).yml
  .github/workflows/v3_klickeruzhprod-responses.yml
  .serena/memories/project_overview.md
  .versionrc.js
  apps/func-incoming-responses/.dockerignore
  apps/func-incoming-responses/.funcignore
  apps/func-incoming-responses/.gitignore
  apps/func-incoming-responses/Dockerfile
  apps/func-incoming-responses/docker-compose.yml
  apps/func-incoming-responses/host.json
  apps/func-incoming-responses/local.settings.template
  apps/func-incoming-responses/package.json
  apps/func-incoming-responses/src/index.ts
  apps/func-incoming-responses/src/sbus.ts
  apps/func-incoming-responses/tsconfig.json
  apps/func-incoming-responses/tsup.config.ts
  apps/func-response-processor/.dockerignore
  apps/func-response-processor/.funcignore
  apps/func-response-processor/.gitignore
  apps/func-response-processor/Dockerfile
  apps/func-response-processor/docker-compose.yml
  apps/func-response-processor/host.json
  apps/func-response-processor/local.settings.template
  apps/func-response-processor/package.json
  apps/func-response-processor/src/index.ts
  apps/func-response-processor/src/redis.ts
  apps/func-response-processor/tsconfig.json
  apps/func-response-processor/tsup.config.ts
  pnpm-lock.yaml
  util/traefik/rules_docker.yaml
  util/traefik/rules_wsl.yaml
Labels: size:XXL

#4888 chore(ci): simplify typescript type check action
  .github/workflows/check-types.yml
  .husky/pre-commit
  .serena/memories/task_completion_checklist.md
  apps/backend-docker/tsconfig.json
  package.json
Labels: size:L

#4891 fix(packages/graphql): make sure lecturer join link displays shared and owned live quizzes
  apps/frontend-pwa/src/pages/course/[courseId]/join.tsx
  packages/graphql/src/services/liveQuizzes.ts
Labels: enhancement, size:M

#4899 enhance: correctly display errors from response-api in student frontend and resolve race conditions
  apps/frontend-pwa/src/components/liveQuiz/QuestionArea.tsx
  apps/frontend-pwa/src/pages/session/[id].tsx
  apps/response-api/.env.example
  apps/response-api/src/index.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/util/src/jwt.ts
Labels: enhancement, size:L

#4900 enhance: pass execution context through to hatchet handlers
  packages/graphql/src/services/accounts.ts
  packages/graphql/src/services/groups.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/graphql/src/services/microLearning.ts
  packages/graphql/src/services/notifications.ts
  packages/graphql/src/services/participants.ts
  packages/graphql/src/services/practiceQuizzes.ts
  packages/graphql/test/helpers.ts
  packages/hatchet/src/index.ts
  packages/types/src/hatchet.ts
Labels: enhancement, size:XXL

#4902 enhance: re-compute instance results on block closure asynchronously based on cache or database data
  .github/workflows/test-olat-api.yml
  .vscode/settings.json
  apps/frontend-pwa/src/pages/session/[id].tsx
  apps/hatchet-worker-response-processor/src/index.ts
  apps/hatchet-worker-response-processor/src/processors/assessmentProcessor.ts
  apps/hatchet-worker-response-processor/src/processors/helpers.ts
  apps/hatchet-worker-response-processor/src/processors/processor.ts
  packages/grading/src/index.ts
  packages/graphql/src/index.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/graphql/src/types/app.ts
  packages/graphql/test/helpers.ts
  packages/hatchet/src/index.ts
  packages/prisma/src/prisma/schema/response.prisma
  packages/types/src/hatchet.ts
  packages/types/src/index.ts
  packages/util/package.json
  packages/util/src/blocks.ts
  packages/util/src/index.ts
  packages/util/src/jwt.ts
  pnpm-lock.yaml
Labels: enhancement, feature, size:XXL

#4904 enhance: add the possibility to reset assessment live quizzes
  .github/workflows/test-graphql.yml
  apps/frontend-manage/src/components/activities/actions/useLiveQuizActions.ts
  apps/frontend-manage/src/components/activities/overview/LiveQuizActions.tsx
  apps/frontend-manage/src/components/courses/modals/LiveQuizResetModal.tsx
  packages/graphql/src/graphql/ops/MResetAssessmentLiveQuiz.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/schema/query.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/graphql/test/assessmentRestrictions.test.ts
  packages/graphql/test/helpers.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, feature, size:XL

#4908 fix: ensure that scheduled publication tasks are cancelled on course deletion and add migration script for transfer from cronjobs to hatchet
  packages/graphql/package.json
  packages/graphql/src/scripts/2025-09-14_hatchet_tasks_activity_publication.ts
  packages/graphql/src/services/courses.ts
  packages/graphql/src/services/practiceQuizzes.ts
  packages/graphql/test/helpers.ts
  packages/prisma-data/src/data/data/TEST.ts
  packages/prisma-data/src/data/seedTEST.ts
Labels: size:L

#4905 enhance: improve stability of student eduid login
  .github/scripts/wait-for-services.sh
  .github/workflows/cypress-testing.yml
  .github/workflows/test-graphql.yml
  _run_app_dependencies.sh
  apps/auth/.env.development
  apps/auth/.env.production
  apps/auth/.env.qa
  apps/auth/.env.test
  apps/auth/Dockerfile
  apps/auth/package.json
  apps/auth/src/lib/constants.ts
  apps/auth/src/middleware.ts
  apps/auth/src/pages/api/auth/[...nextauth].ts
  apps/auth/src/pages/api/discourse.ts
  apps/auth/src/pages/discourse.tsx
  apps/auth/src/pages/index.tsx
  apps/auth/src/pages/student.tsx
  apps/backend-docker/.env.cypress
  apps/backend-docker/.env.example
  apps/backend-docker/package.json
  apps/docs/package.json
  apps/frontend-pwa/src/components/forms/LoginForm.tsx
  apps/frontend-pwa/src/pages/login.tsx
  apps/hatchet-worker-general/.env.example
  apps/hatchet-worker-general/src/index.ts
  apps/hatchet-worker-response-processor/.env.example
  apps/hatchet-worker-response-processor/src/index.ts
  apps/olat-api/package.json
  apps/response-api/.env.example
  apps/response-api/src/index.ts
  cypress/package.json
  deploy/charts/klicker-uzh-v2/templates/cm-backend-assessment.yaml
  deploy/charts/klicker-uzh-v2/templates/cm-backend-graphql.yaml
  deploy/charts/klicker-uzh-v2/templates/cm-hatchet-workers.yaml
  deploy/charts/klicker-uzh-v2/templates/cm-response-api-assessment.yaml
  deploy/charts/klicker-uzh-v2/templates/cm-response-api.yaml
  packages/graphql/.env.example
  packages/graphql/package.json
  packages/graphql/test/docker/.env.example
  packages/hatchet/src/client.ts
  packages/prisma/package.json
  packages/prisma/src/prisma/migrations/20250722112026_hatchet_scheduling_task_ids/migration.sql
  packages/prisma/src/prisma/schema/js.prisma
  packages/prisma/src/prisma/schema/participant.prisma
  pnpm-lock.yaml
  project/plans_archive/RESEARCH-cypress-hatchet.md
  util/_create_hatchet_token_cypress.sh
  util/_create_hatchet_token_graphql.sh
Labels: enhancement, size:XXL

#4903 enhance: add issuer and scope to signJWT, app origins for everything
  .github/workflows/cypress-testing.yml
  .github/workflows/test-graphql.yml
  apps/auth/.env.development
  apps/auth/.env.production
  apps/auth/.env.qa
  apps/auth/.env.test
  apps/auth/src/pages/api/auth/[...nextauth].ts
  apps/backend-docker/.env.cypress
  apps/backend-docker/.env.example
  apps/backend-docker/src/index.ts
  apps/frontend-control/.env.development
  apps/frontend-control/.env.production
  apps/frontend-control/.env.qa
  apps/frontend-control/.env.test
  apps/frontend-control/src/lib/apollo.ts
  apps/frontend-manage/.env.development
  apps/frontend-manage/.env.production
  apps/frontend-manage/.env.qa
  apps/frontend-manage/.env.test
  apps/frontend-manage/src/lib/apollo.ts
  apps/frontend-pwa/.env.assessment
  apps/frontend-pwa/.env.assessment.qa
  apps/frontend-pwa/.env.development
  apps/frontend-pwa/.env.production
  apps/frontend-pwa/.env.qa
  apps/frontend-pwa/.env.test
  apps/frontend-pwa/src/lib/apollo.ts
  apps/frontend-pwa/src/lib/getParticipantToken.ts
  apps/frontend-pwa/src/pages/createAccount.tsx
  apps/hatchet-worker-general/.env.example
  apps/hatchet-worker-response-processor/.env.example
  apps/lti/src/index.ts
  apps/office-addin/package.json
  apps/response-api/.env.example
  cypress/cypress/support/commands.ts
  deploy/charts/klicker-uzh-v2/templates/cm-frontend-assessment.yaml
  deploy/charts/klicker-uzh-v2/templates/cm-frontend-control.yaml
  deploy/charts/klicker-uzh-v2/templates/cm-frontend-manage.yaml
  deploy/charts/klicker-uzh-v2/templates/cm-frontend-pwa.yaml
  deploy/charts/klicker-uzh-v2/templates/cm-global.yaml
  deploy/charts/klicker-uzh-v2/templates/deployment-app.yaml
  deploy/charts/klicker-uzh-v2/templates/deployment-assessment.yaml
  deploy/charts/klicker-uzh-v2/templates/deployment-hatchet-workers.yaml
  deploy/charts/klicker-uzh-v2/templates/deployment-response-api.yaml
  deploy/charts/klicker-uzh-v2/values.yaml
  deploy/env-prod-v3/values.yaml
  deploy/env-qa-v3/values.yaml
  packages/graphql/src/scripts/impersonateParticipant.ts
  packages/graphql/src/scripts/impersonateUser.ts
  packages/graphql/src/services/accounts.ts
  packages/graphql/src/services/groups.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/prisma/package.json
  packages/util/src/jwt.ts
Labels: size:XL

#4910 fix(ci): resolve issues with graphql testing in ci environment
  .github/workflows/test-graphql.yml
  util/_create_hatchet_token_graphql.sh
Labels: size:M

#4912 enhance: validate participant login and course participation rigorously in response-api and assessment processor
  apps/hatchet-worker-response-processor/src/processors/assessmentProcessor.ts
  apps/response-api/package.json
  apps/response-api/src/index.ts
  packages/graphql/src/scripts/invitations_dev.csv
  packages/graphql/src/services/liveQuizzes.ts
  packages/util/src/jwt.ts
  packages/util/test/jwt.test.ts
  turbo.json
Labels: enhancement, size:L

#4917 chore(packages/graphql): make sure redis exec and assessment caches are set up correctly in graphql test workflows
  .github/workflows/test-graphql.yml
  apps/frontend-pwa/src/components/common/Header.tsx
  packages/graphql/test/docker/docker-compose.test.yml
  packages/graphql/test/helpers.ts
Labels: feature, size:M

#4916 enhance(apps/auth): improve authentication workflow including participant invitations and SSO
  apps/auth/src/lib/helpers.ts
  apps/auth/src/pages/api/auth/[...nextauth].ts
  apps/auth/src/pages/api/discourse.ts
  packages/graphql/src/scripts/importParticipantInvitations.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/graphql/src/services/participantInvitations.ts
  packages/prisma/src/prisma/schema/migrations/20250915092955_constraints_participant_invitation/migration.sql
  packages/util/src/email.ts
  packages/util/test/email.test.ts
Labels: size:XXL

#4922 fix(cypress): change the existing assessment test case to cover pin-protected quizzes instead
  apps/frontend-manage/src/components/activities/creation/liveQuiz/LiveQuizSettingsStep.tsx
  cypress/cypress/e2e/O-live-quiz-workflow.cy.ts
  cypress/cypress/e2e/V-template-workflow.cy.ts
  cypress/cypress/fixtures/O-live-quiz.json
  cypress/cypress/support/commands.ts
Labels: size:L

#4927 enhance(packages/graphql): instead of unlinking, set expiration date on instance keys within block closure operation
  packages/graphql/src/services/liveQuizzes.ts
Labels: enhancement, size:XS

#4929 fix: ensure that only valid live quiz grading parameters can be defined
  apps/frontend-manage/src/components/activities/overview/batchOperations/ActivityLiveQuizPointsCard.tsx
  packages/grading/src/index.ts
  packages/grading/test/index.test.ts
  packages/graphql/package.json
  packages/graphql/src/services/activities.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/graphql/src/services/templates.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/prisma/src/prisma/schema/migrations/20250919170000_live_quiz_scoring_constraints/migration.sql
Labels: enhancement, size:L

#4932 feat(apps/chat): dynamic MCP tools and chatbot parametrization, credit management improvements
  .github/scripts/wait-for-services.sh
  .github/workflows/claude-code-review.yml
  .serena/memories/chat_application.md
  .serena/memories/deployment_infrastructure.md
  .serena/memories/project_overview.md
  .serena/memories/project_structure.md
  .serena/memories/tech_stack.md
  apps/chat/eslint.config.mjs
  apps/chat/src/app/RuntimeProvider.tsx
  apps/chat/src/app/api/chatbots/[chatbotId]/chat/route.ts
  apps/chat/src/app/api/chatbots/[chatbotId]/threads/[threadId]/route.ts
  apps/chat/src/app/api/chatbots/[chatbotId]/threads/[threadId]/title/route.ts
  apps/chat/src/app/api/chatbots/[chatbotId]/threads/route.ts
  apps/chat/src/app/layout.tsx
  apps/chat/src/components/settings-panel.tsx
  apps/chat/src/components/thread.tsx
  apps/chat/src/components/tool-fallback.tsx
  apps/chat/src/components/tools-ui/rag-tool-ui.tsx
  apps/chat/src/hooks/useChatResponse.ts
  apps/chat/src/lib/config/prompts.ts
  apps/chat/src/services/credits.ts
  apps/chat/src/services/mcpClients.ts
  apps/chat/src/stores/settingsStore.ts
  apps/chat/src/utils/creditPeriods.ts
  apps/chat/src/utils/transactions.ts
  apps/chat/tsconfig.json
  deploy/_doppler_deploy_common.sh
  packages/graphql/src/scripts/2025-08-18_compare_redis_states.ts
  packages/prisma-data/src/data/seedChatbots.ts
  packages/prisma-data/src/data/seedMCPServers.ts
  packages/prisma-data/src/data/seedTEST.ts
  packages/prisma/src/prisma/schema/chat.prisma
  packages/prisma/src/prisma/schema/migrations/20250921094251_chatbot_mcp_credits_enhancements/migration.sql
  packages/util/src/crypto.ts
  packages/util/src/index.ts
  project/plans_archive/PLAN-chat-credits.md
  project/plans_archive/PLAN-chatbot-enhancements.md
  util/_create_hatchet_token_cypress.sh
  util/_run_with_doppler.sh
Labels: feature, size:XXL

#4935 enhance: add functionality to display assessment activity results to students
  apps/frontend-manage/src/components/activities/overview/LiveQuizActions.tsx
  apps/frontend-manage/src/components/evaluation/elements/LiveQuizEvaluationQRCode.tsx
  apps/frontend-pwa/src/components/insights/assessmentResults/AssessmentResultsList.tsx
  apps/frontend-pwa/src/components/insights/assessmentResults/PointsCard.tsx
  apps/frontend-pwa/src/components/insights/assessmentResults/SuspendedAssessmentResults.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/chatbot/[chatbotId].tsx
  apps/frontend-pwa/src/pages/course/[courseId]/index.tsx
  packages/graphql/src/graphql/ops/FActivityStudentPerformance.graphql
  packages/graphql/src/graphql/ops/QGetCourseOverviewData.graphql
  packages/graphql/src/graphql/ops/QGetStudentAssessmentResults.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/course.ts
  packages/graphql/src/schema/query.ts
  packages/graphql/src/services/courses.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/types/src/index.ts
Labels: feature, size:XXL

#4938 enhance(apps/chat): add dynamic disclaimer system
  .gitignore
  .prettierignore
  apps/chat/package.json
  apps/chat/src/app/api/chatbots/[chatbotId]/chat/route.ts
  apps/chat/src/app/api/chatbots/[chatbotId]/disclaimer/route.ts
  apps/chat/src/app/globals.css
  apps/chat/src/components/assistant.tsx
  apps/chat/src/components/disclaimer-modal.tsx
  apps/chat/src/components/settings-panel.tsx
  apps/chat/src/services/disclaimers.ts
  packages/prisma-data/src/data/seedChatbots.ts
  packages/prisma/src/prisma/schema/chat.prisma
  packages/prisma/src/prisma/schema/migrations/20250922202537_chatbot_disclaimers/migration.sql
  packages/prisma/src/prisma/schema/user.prisma
  pnpm-lock.yaml
  project/plans_archive/PLAN-chatbot-disclaimer.md
  util/_run_with_doppler.sh
Labels: enhancement, size:XXL

#4941 feat: add point correction mechanisms on point and quiz level
  apps/frontend-manage/src/components/courses/CourseOverviewHeader.tsx
  apps/frontend-manage/src/components/courses/PointCorrectionsModal.tsx
  apps/frontend-manage/src/components/courses/pointCorrections/PointCorrectionsAdjustmentsStep.tsx
  apps/frontend-manage/src/components/courses/pointCorrections/PointCorrectionsAudienceStep.tsx
  apps/frontend-manage/src/components/courses/pointCorrections/PointCorrectionsReasonStep.tsx
  apps/frontend-manage/src/components/courses/pointCorrections/PointCorrectionsScopeStep.tsx
  apps/frontend-manage/src/components/courses/pointCorrections/PointCorrectionsSummaryStep.tsx
  apps/frontend-manage/src/components/courses/pointCorrections/SuspendedPreviousCorrections.tsx
  apps/frontend-manage/src/components/courses/pointCorrections/types.ts
  apps/frontend-pwa/src/components/insights/assessmentResults/AssessmentResultsList.tsx
  apps/frontend-pwa/src/components/insights/assessmentResults/SuspendedAssessmentResults.tsx
  apps/hatchet-worker-response-processor/src/processors/assessmentProcessor.ts
  packages/graphql/src/graphql/ops/FActivityStudentPerformanceData.graphql
  packages/graphql/src/graphql/ops/FPointCorrectionData.graphql
  packages/graphql/src/graphql/ops/MCorrectAssessmentPointsInstance.graphql
  packages/graphql/src/graphql/ops/MCorrectAssessmentPointsLiveQuiz.graphql
  packages/graphql/src/graphql/ops/QGetAssessmentCourseParticipants.graphql
  packages/graphql/src/graphql/ops/QGetEndedLiveQuizzesCourse.graphql
  packages/graphql/src/graphql/ops/QGetPreviousPointCorrections.graphql
  packages/graphql/src/index.ts
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/assessment.ts
  packages/graphql/src/schema/course.ts
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/schema/query.ts
  packages/graphql/src/services/courses.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/graphql/src/types/app.ts
  packages/graphql/test/helpers.ts
  packages/graphql/test/instancePointCorrections.test.ts
  packages/graphql/test/liveQuizPointCorrections.test.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/prisma/src/prisma/schema/element.prisma
  packages/prisma/src/prisma/schema/migrations/20250923154945_point_corrections/migration.sql
  packages/prisma/src/prisma/schema/participant.prisma
  packages/prisma/src/prisma/schema/quiz.prisma
  packages/prisma/src/prisma/schema/response.prisma
  packages/prisma/src/prisma/schema/user.prisma
  packages/types/src/index.ts
Labels: feature, size:XXL

#4945 feat: display point corrections and applied point corrections on overviews and detailed student response listings
  apps/frontend-manage/src/components/courses/PointCorrectionsModal.tsx
  apps/frontend-manage/src/components/courses/pointCorrections/PreviousCorrectionsListModal.tsx
  apps/frontend-manage/src/components/courses/pointCorrections/PreviousPointCorrectionList.tsx
  apps/frontend-manage/src/components/courses/pointCorrections/SuspendedPreviousCorrections.tsx
  apps/frontend-manage/src/components/liveQuiz/results/LiveQuizSingleStudentResults.tsx
  apps/frontend-manage/src/pages/courses/[id]/assessment/liveQuiz/[quizId].tsx
  packages/graphql/src/graphql/ops/QGetAssessmentResultsLiveQuiz.graphql
  packages/graphql/src/graphql/ops/QGetLiveQuizStudentAssessmentResponses.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/assessment.ts
  packages/graphql/src/services/courses.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/types/src/index.ts
Labels: feature, size:XL

#4948 fix(packages/graphql): ensure that only students with a submitted response are counted as participating
  apps/frontend-manage/src/components/liveQuiz/results/LiveQuizStudentResultsTable.tsx
  packages/graphql/src/services/courses.ts
Labels: size:M

#4949 fix(packages/graphql): avoid hatchet rate limits by using batch task calls for point correction audit logs
  packages/graphql/src/services/courses.ts
  packages/graphql/test/docker/docker-compose.test.yml
  packages/graphql/test/helpers.ts
  packages/graphql/test/instancePointCorrections.test.ts
  packages/graphql/test/liveQuizPointCorrections.test.ts
  packages/graphql/test/run-tests-local.sh
  packages/types/src/hatchet.ts
Labels: enhancement, size:L
