Repository uzh-bf/klicker-uzh, pull requests merged in 2025-07, with the labels that each got.

#4759 fix: ensure that only elements with sufficient permissions are archived and toasts clearly indicate the success of the operation
  apps/frontend-manage/src/components/questions/Element.tsx
  apps/frontend-manage/src/components/questions/ElementList.tsx
  apps/frontend-manage/src/pages/index.tsx
  packages/graphql/src/graphql/ops/MToggleIsArchived.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/schema/question.ts
  packages/graphql/src/services/questions.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: size:L

#4758 wip: try to extend graphql testing docker configuration file to include hatchet setup
  .github/workflows/cypress-testing.yml
  .github/workflows/test-grading.yml
  .github/workflows/test-graphql.yml
  packages/graphql/jest.config.ts
  packages/graphql/run-tests.sh
  packages/graphql/test/docker/Dockerfile.test
  packages/graphql/test/docker/docker-compose.test.yml
  packages/graphql/test/helpers.ts
Labels: size:L

#4760 chore(apps/olat-api): ensure that affiliation provider account ids are also accepted for lti login
  apps/olat-api/src/index.ts
  apps/olat-api/test/index.test.ts
  apps/olat-api/test/userData.ts
Labels: enhancement, size:M

#4747 feat(apps/olat-api): define API for OLAT user activity queries
  .github/workflows/test-olat-api.yml
  .github/workflows/v3_olat-api-prod.yml
  .github/workflows/v3_olat-api-qa.yml
  CLAUDE.md
  apps/frontend-pwa/src/pages/course/[courseId]/liveQuiz/[id].tsx
  apps/olat-api/.dockerignore
  apps/olat-api/.gitignore
  apps/olat-api/CLAUDE.md
  apps/olat-api/Dockerfile
  apps/olat-api/package.json
  apps/olat-api/rollup.config.js
  apps/olat-api/run-tests.sh
  apps/olat-api/src/index.ts
  apps/olat-api/src/services.ts
  apps/olat-api/src/static.ts
  apps/olat-api/src/types.ts
  apps/olat-api/static/activityTypes.json
  apps/olat-api/static/openapi.yaml
  apps/olat-api/test/docker/Dockerfile.test
  apps/olat-api/test/docker/docker-compose.test.yml
  apps/olat-api/test/helpers.ts
  apps/olat-api/test/index.test.ts
  apps/olat-api/test/userData.ts
  apps/olat-api/tsconfig.json
  deploy/charts/klicker-uzh-v2/templates/deployment-app.yaml
  deploy/charts/klicker-uzh-v2/templates/ingress-olat-api.yaml
  deploy/charts/klicker-uzh-v2/templates/secret-olat-api.yaml
  deploy/charts/klicker-uzh-v2/templates/service-app.yaml
  deploy/charts/klicker-uzh-v2/values.yaml
  deploy/env-prod-v3/_restart.sh
  deploy/env-prod-v3/values-envsubst.yaml
  deploy/env-prod-v3/values.yaml
  deploy/env-qa-v3/_restart.sh
  deploy/env-qa-v3/values-envsubst.yaml
  deploy/env-qa-v3/values.yaml
  packages/graphql/src/graphql/ops/QValidateAvailableLiveQuiz.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/query.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/prisma/src/data/seedAccounts.ts
  packages/prisma/src/data/seedTEST.ts
  pnpm-lock.yaml
  turbo.json
Labels: feature, size:XXL

#4766 wip: fix cypress test suite with errors caused by component upgrades
  apps/backend-docker/package.json
  apps/frontend-manage/src/components/activities/templates/liveQuiz/useInitialLiveQuizTemplateFormData.ts
  cypress/cypress.config.ts
  cypress/cypress/e2e/0-baseline-ops.cy.ts
  cypress/cypress/e2e/A-login-workflow.cy.ts
  cypress/cypress/e2e/B-feature-access-workflow.cy.ts
  cypress/cypress/e2e/D-elements-content-workflow.cy.ts
  cypress/cypress/e2e/E-elements-flashcards-workflow.cy.ts
  cypress/cypress/e2e/F-elements-sc-workflow.cy.ts
  cypress/cypress/e2e/G-elements-mc-workflow.cy.ts
  cypress/cypress/e2e/H-elements-kprim-workflow.cy.ts
  cypress/cypress/e2e/I-elements-numerical-workflow.cy.ts
  cypress/cypress/e2e/J-elements-free-text-workflow.cy.ts
  cypress/cypress/e2e/K-elements-selection-workflow.cy.ts
  cypress/cypress/e2e/L-elements-case-study-workflow.cy.ts
  cypress/cypress/e2e/M-elements-operations-workflow.cy.ts
  cypress/cypress/e2e/N-course-workflow.cy.ts
  cypress/cypress/e2e/O-live-quiz-workflow.cy.ts
  cypress/cypress/e2e/P-microlearning-workflow.cy.ts
  cypress/cypress/e2e/Q-practice-quiz-workflow.cy.ts
  cypress/cypress/e2e/S-group-activity-workflow.cy.ts
  cypress/cypress/e2e/T-resources-workflow.cy.ts
  cypress/cypress/e2e/U-catalog-workflow.cy.ts
  cypress/cypress/e2e/V-template-workflow.cy.ts
  cypress/cypress/e2e/W-activity-log-workflow.cy.ts
  cypress/cypress/support/commands.ts
  cypress/cypress/support/e2e.ts
  cypress/package.json
  pnpm-lock.yaml
Labels: size:XXL

#4767 chore(apps/olat-api): replace deprecated tool for api validation
  apps/olat-api/package.json
  pnpm-lock.yaml
Labels: dependencies, size:XS

#4770 chore(apps/frontend-manage): add cache updates for answer collection editing and show success toast when copying embedding links
  apps/auth/package.json
  apps/docs/package.json
  apps/frontend-control/package.json
  apps/frontend-manage/package.json
  apps/frontend-manage/src/components/interaction/confusion/ConfusionCharts.tsx
  apps/frontend-manage/src/components/liveQuiz/EmbeddingModal.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionEditModal.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionMetaForm.tsx
  apps/frontend-manage/src/lib/hooks/useGamifiedCourseGrouping.tsx
  apps/frontend-manage/src/lib/hooks/useGroupsCourseGrouping.tsx
  apps/frontend-manage/src/lib/hooks/useLiveQuizCourseGrouping.tsx
  apps/frontend-pwa/package.json
  apps/office-addin/package.json
  packages/graphql/src/services/resources.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/markdown/package.json
  packages/shared-components/package.json
  packages/transactional/package.json
  pnpm-lock.yaml
Labels: enhancement, size:M

#4771 enhance(apps/frontend-*): use enhanced modal loading states for consistent UX
  apps/auth/package.json
  apps/docs/package.json
  apps/frontend-control/package.json
  apps/frontend-control/src/components/liveQuizzes/EmbeddingModal.tsx
  apps/frontend-manage/package.json
  apps/frontend-manage/src/components/activities/templates/ExistingElementSelectionModal.tsx
  apps/frontend-manage/src/components/activities/templates/TemplateNewElementModal.tsx
  apps/frontend-manage/src/components/activities/templates/extractFormValuesFromElementInstance.ts
  apps/frontend-manage/src/components/courses/modals/CourseDeletionModal.tsx
  apps/frontend-manage/src/components/courses/modals/TemplateConversionModal.tsx
  apps/frontend-manage/src/components/courses/modals/TemplateEditModal.tsx
  apps/frontend-manage/src/components/liveQuiz/EmbeddingModal.tsx
  apps/frontend-manage/src/components/liveQuiz/cockpit/CancelLiveQuizModal.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementEditForm.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementEditModal.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementInformationFields.tsx
  apps/frontend-manage/src/components/questions/manipulation/types.ts
  apps/frontend-manage/src/components/questions/manipulation/useElementFormInitialValues.ts
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionEditModal.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionViewingModal.tsx
  apps/frontend-manage/src/components/user/SuspendedFirstLoginModal.tsx
  apps/frontend-pwa/package.json
  apps/frontend-pwa/src/components/participant/ParticipantProfileModal.tsx
  apps/office-addin/package.json
  packages/markdown/package.json
  packages/shared-components/package.json
  packages/transactional/package.json
  pnpm-lock.yaml
Labels: enhancement, size:L

#4772 chore(apps/olat-api): update return key of activities api query and introduce proper typing
  apps/olat-api/CLAUDE.md
  apps/olat-api/src/index.ts
  apps/olat-api/src/services.ts
  apps/olat-api/src/static.ts
  apps/olat-api/src/types.ts
  apps/olat-api/static/openapi.yaml
  apps/olat-api/test/index.test.ts
Labels: enhancement, size:L

#4773 fix(apps/frontend-manage): resolve table scrolling and overflow issues on live quiz evaluation
  apps/frontend-manage/src/components/evaluation/ElementChart.tsx
  apps/frontend-manage/src/components/evaluation/elements/FTEvaluation.tsx
  apps/frontend-manage/src/components/evaluation/elements/QuestionCollapsible.tsx
  apps/frontend-manage/src/components/evaluation/elements/SEEvaluation.tsx
  apps/frontend-manage/src/components/sharing/DirectSharingForm.tsx
  apps/frontend-pwa/src/components/common/LiveQuizLeaderboard.tsx
  apps/frontend-pwa/src/components/liveQuiz/AllQuestionsAnsweredMessage.tsx
  apps/frontend-pwa/src/components/liveQuiz/FeedbackArea.tsx
  apps/frontend-pwa/src/components/liveQuiz/QuestionArea.tsx
  apps/frontend-pwa/src/components/practiceQuiz/PracticeQuizOverview.tsx
  apps/frontend-pwa/src/pages/session/[id].tsx
  apps/func-response-processor/src/index.ts
  packages/markdown/src/Markdown.tsx
  packages/shared-components/src/charts/ElementBarChart.tsx
  packages/shared-components/src/charts/ElementTableChart.tsx
  packages/shared-components/src/charts/ElementWordcloud.tsx
Labels: enhancement, size:L

#4774 enhance(apps(frontend-manage): add possibility to set and modify notication email on course
  apps/frontend-manage/src/components/courses/CourseOverviewHeader.tsx
  apps/frontend-manage/src/components/courses/modals/CourseManipulationModal.tsx
  apps/frontend-manage/src/pages/courses/[id].tsx
  apps/frontend-manage/src/pages/courses/index.tsx
  cypress/cypress/e2e/N-course-workflow.cy.ts
  cypress/cypress/fixtures/N-course.json
  packages/graphql/src/graphql/ops/QGetSingleCourse.graphql
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/server.json
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:L

#4775 fix: ensure that errors due to tags with identical names are handled gracefully
  apps/frontend-manage/src/components/questions/tags/TagEditForm.tsx
  apps/frontend-manage/src/components/questions/tags/UserTag.tsx
  packages/graphql/src/services/questions.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: size:M

#4769 chore: remove database structure for live sessions and question instances
  .github/workflows/check-types.yml
  apps/backend-docker/src/app.ts
  apps/olat-api/package.json
  apps/olat-api/test/helpers.ts
  packages/graphql/src/schema/question.ts
  packages/graphql/src/scripts/2025-07-10_drop_live_session_cache_data.ts
  packages/graphql/src/services/accounts.ts
  packages/graphql/src/services/questions.ts
  packages/graphql/src/services/stacks.ts
  packages/graphql/src/services/templates.ts
  packages/graphql/test/activityPermissions.test.ts
  packages/graphql/test/coursePermissions.test.ts
  packages/graphql/test/elementPermissions.test.ts
  packages/graphql/test/elementSharing.test.ts
  packages/graphql/test/helpers.ts
  packages/graphql/test/template.test.ts
  packages/prisma/src/data/helpers.ts
  packages/prisma/src/data/seedFlashcards.ts
  packages/prisma/src/data/seedTEST.ts
  packages/prisma/src/prisma/migrations/20250710145407_remove_live_session/migration.sql
  packages/prisma/src/prisma/schema/course.prisma
  packages/prisma/src/prisma/schema/element.prisma
  packages/prisma/src/prisma/schema/participant.prisma
  packages/prisma/src/prisma/schema/quiz.prisma
  packages/prisma/src/prisma/schema/user.prisma
  packages/util/src/elements.ts
Labels: size:L

#4779 chore: Add Claude Code GitHub Workflow
  .github/workflows/claude-code-review.yml
  .github/workflows/claude.yml
Labels: feature, size:L

#4778 enhance(apps/frontend-manage): introduce new Live-Q&A view for lecturer
  apps/frontend-manage/src/components/interaction/AudienceInteraction.tsx
  apps/frontend-manage/src/components/interaction/confusion/ConfusionCharts.tsx
  apps/frontend-manage/src/components/interaction/feedbacks/Feedback.tsx
  apps/frontend-manage/src/components/interaction/feedbacks/FeedbackChannel.tsx
  apps/frontend-manage/src/components/interaction/feedbacks/FeedbackDeletionModal.tsx
  apps/frontend-manage/src/components/interaction/feedbacks/FeedbackList.tsx
  apps/frontend-manage/src/components/interaction/feedbacks/FeedbackListEntry.tsx
  apps/frontend-manage/src/components/interaction/feedbacks/FeedbackOverviewFilters.tsx
  apps/frontend-manage/src/components/interaction/feedbacks/FeedbackSearchBar.tsx
  apps/frontend-manage/src/components/interaction/feedbacks/ModerationChangeModal.tsx
  apps/frontend-manage/src/lib/hooks/useFeedbackFilter.ts
  cypress/cypress/e2e/O-live-quiz-workflow.cy.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:XXL

#4781 enhance(apps/frontend-pwa): add error page for invalid live quiz links instead of persistent loading circle
  apps/frontend-control/src/pages/404.tsx
  apps/frontend-manage/src/pages/404.tsx
  apps/frontend-pwa/src/pages/404.tsx
  apps/frontend-pwa/src/pages/session/[id].tsx
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:M

#4782 chore(apps/docs): update documentation on element types, element management, and course management
  apps/docs/docs/tutorials/course_management.mdx
  apps/docs/docs/tutorials/element_management.mdx
  apps/docs/docs/tutorials/live_quiz.mdx
  apps/docs/docs/tutorials/supported_element_types.mdx
  apps/docs/docusaurus.config.ts
  apps/docs/postcss.config.js
  apps/docs/src/components/CatalystTitle.tsx
  apps/docs/src/components/PrivatePreviewTag.tsx
  apps/docs/src/components/development/RoadmapTile.tsx
  apps/docs/src/components/landing/TitleImage.tsx
  apps/docs/src/components/usecases/UseCase.tsx
  apps/docs/src/custom.css
  apps/docs/src/pages/about.tsx
  apps/docs/src/pages/development.tsx
  apps/docs/src/pages/use_cases/index.tsx
  apps/docs/static/img/courses/course_overview.png
  apps/docs/static/img/elements/MC_element_editor.png
  apps/docs/static/img/elements/SC_element_editor.png
  apps/docs/static/img/elements/element_deletion.png
  apps/docs/static/img/elements/element_duplication.png
  apps/docs/static/img/elements/element_editing.png
  apps/docs/static/img/elements/element_sharing.png
  apps/docs/static/img/group/random_groups_lecturer.png
  apps/docs/static/img/group/random_groups_student.png
  apps/docs/static/img/supported_element_types/CS_evaluation_histogram.png
  apps/docs/static/img/supported_element_types/CS_evaluation_scatter.png
  apps/docs/static/img/supported_element_types/CS_lecturer.png
  apps/docs/static/img/supported_element_types/CT_evaluation.png
  apps/docs/static/img/supported_element_types/CT_lecturer.png
  apps/docs/static/img/supported_element_types/CT_student.png
  apps/docs/static/img/supported_element_types/FC_evaluation_barChart.png
  apps/docs/static/img/supported_element_types/FC_evaluation_table.png
  apps/docs/static/img/supported_element_types/FT_evaluation.png
  apps/docs/static/img/supported_element_types/FT_lecturer.png
  apps/docs/static/img/supported_element_types/KP_evaluation_barChart.png
  apps/docs/static/img/supported_element_types/KP_evaluation_table.png
  apps/docs/static/img/supported_element_types/KP_lecturer.png
  apps/docs/static/img/supported_element_types/MC_evaluation_barChart.png
  apps/docs/static/img/supported_element_types/MC_evaluation_table.png
  apps/docs/static/img/supported_element_types/MC_lecturer.png
  apps/docs/static/img/supported_element_types/NR_evaluation_histogram.png
  apps/docs/static/img/supported_element_types/NR_evaluation_table.png
  apps/docs/static/img/supported_element_types/NR_lecturer.png
  apps/docs/static/img/supported_element_types/SC_evaluation_barChart.png
  apps/docs/static/img/supported_element_types/SC_evaluation_table.png
  apps/docs/static/img/supported_element_types/SC_lecturer.png
  apps/docs/static/img/supported_element_types/SE_evaluation.png
  apps/docs/static/img/supported_element_types/SE_lecturer.png
  apps/frontend-pwa/src/components/participant/groups/GroupAction.tsx
Labels: size:L

#4786 feat: add possibility to update elements to latest versions in activity editor
  apps/frontend-manage/src/components/activities/creation/CompletionStep.tsx
  apps/frontend-manage/src/components/activities/creation/InstanceUpdateOption.tsx
  apps/frontend-manage/src/components/activities/creation/StackBlockCreation.tsx
  apps/frontend-manage/src/components/activities/creation/StackCreationStep.tsx
  apps/frontend-manage/src/components/activities/creation/WizardElementList.tsx
  apps/frontend-manage/src/components/activities/creation/groupActivity/GroupActivityStackClues.tsx
  apps/frontend-manage/src/components/activities/creation/groupActivity/GroupActivityWizard.tsx
  apps/frontend-manage/src/components/activities/creation/liveQuiz/LiveQuizCreationBlock.tsx
  apps/frontend-manage/src/components/activities/creation/liveQuiz/LiveQuizQuestionsStep.tsx
  apps/frontend-manage/src/components/activities/creation/liveQuiz/LiveQuizWizard.tsx
  apps/frontend-manage/src/components/activities/creation/microLearning/MicroLearningWizard.tsx
  apps/frontend-manage/src/components/activities/creation/practiceQuiz/PracticeQuizWizard.tsx
  apps/frontend-manage/src/components/activities/overview/ActivityDetailsModal.tsx
  apps/frontend-manage/src/components/questions/manipulation/InstanceUpdateSwitch.tsx
  cypress/cypress/e2e/MA-elements-operations-workflow.cy.ts
  cypress/cypress/e2e/MB-instance-updates-workflow.cy.ts
  cypress/cypress/fixtures/DM-questions.json
  packages/graphql/src/graphql/ops/QGetOutdatedElementInstances.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/query.ts
  packages/graphql/src/schema/question.ts
  packages/graphql/src/services/questions.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/types/src/index.ts
Labels: enhancement, size:XXL

#4789 enhance: correctly update, load and display if an activity contains oudated element instances
  .github/workflows/claude-code-review.yml
  apps/frontend-manage/src/components/activities/overview/ActivityDetailsModal.tsx
  apps/frontend-manage/src/components/activities/overview/ActivityListEntry.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementEditModal.tsx
  cypress/cypress/e2e/MB-instance-updates-workflow.cy.ts
  packages/graphql/src/graphql/ops/FActivityInfoData.graphql
  packages/graphql/src/graphql/ops/MFlagOutdatedElementInstances.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/activities.ts
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/schema/practiceQuiz.ts
  packages/graphql/src/schema/question.ts
  packages/graphql/src/scripts/2025-07-20_compute_outdated_instances.ts
  packages/graphql/src/services/activities.ts
  packages/graphql/src/services/courses.ts
  packages/graphql/src/services/groups.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/graphql/src/services/microLearning.ts
  packages/graphql/src/services/practiceQuizzes.ts
  packages/graphql/src/services/questions.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/prisma/src/prisma/migrations/20250720133414_instance_outdated_flags/migration.sql
  packages/prisma/src/prisma/schema/element.prisma
  packages/prisma/src/prisma/schema/quiz.prisma
Labels: enhancement, size:XL

#4790 fix(apps/frontend-manage): make sure to show correct tooltip when hovering over scatter plot items on case study evaluation
  apps/frontend-manage/src/components/evaluation/elements/CSTwoDimScatterPlot.tsx
Labels: size:L

#4598 enhance: extend choices answer representation
  apps/frontend-manage/src/components/courses/groupActivity/GroupActivityGradingStack.tsx
  apps/frontend-pwa/src/components/groupActivity/GroupActivityStack.tsx
  apps/frontend-pwa/src/components/liveQuiz/QuestionArea.tsx
  apps/frontend-pwa/src/components/practiceQuiz/ElementStack.tsx
  apps/func-response-processor/package.json
  apps/func-response-processor/src/index.ts
  packages/grading/src/index.ts
  packages/grading/test/index.test.ts
  packages/graphql/src/graphql/ops/FStackFeedbackEvaluations.graphql
  packages/graphql/src/graphql/ops/MGradeGroupActivitySubmission.graphql
  packages/graphql/src/graphql/ops/QGetGradingGroupActivity.graphql
  packages/graphql/src/graphql/ops/QGroupActivityDetails.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/groupActivity.ts
  packages/graphql/src/schema/practiceQuiz.ts
  packages/graphql/src/schema/question.ts
  packages/graphql/src/services/stacks.ts
  packages/shared-components/src/questions/KPAnswerOptions.tsx
  packages/types/src/index.ts
  pnpm-lock.yaml
Labels: enhancement, size:L

#4791 fix: update database user to new username across entire app to be consistent with new development setup
  .github/scripts/wait-for-services.sh
  .github/workflows/cypress-testing.yml
  apps/analytics/src/notebooks/activity_progress.ipynb
  apps/analytics/src/notebooks/aggregated_analytics.ipynb
  apps/analytics/src/notebooks/aggregated_course_analytics.ipynb
  apps/analytics/src/notebooks/archive/daily_participant_analytics.ipynb
  apps/analytics/src/notebooks/archive/test.ipynb
  apps/analytics/src/notebooks/instance_activity_performance.ipynb
  apps/analytics/src/notebooks/participant_activity_performance.ipynb
  apps/analytics/src/notebooks/participant_analytics.ipynb
  apps/analytics/src/notebooks/participant_course_analytics.ipynb
  apps/analytics/src/notebooks/participant_performance.ipynb
  apps/auth/.env.test
  apps/backend-docker/.env.cypress
  apps/backend-docker/.env.template
  apps/olat-api/test/helpers.ts
  cypress/cypress.config.ts
  docker-compose.yml
  package.json
  packages/grading/package.json
  packages/graphql/test/helpers.ts
  packages/prisma/package.json
  pnpm-lock.yaml
  turbo.json
Labels: size:M

#4797 chore(apps/auth): update staging eduid configuration
  apps/auth/.env.qa
Labels: size:XS

#4798 fix(apps/auth): ensure that institutional affiliations are created correctly on first login
  apps/auth/src/pages/api/auth/[...nextauth].ts
Labels: size:M

#4802 enhance: allow disabling gamification and group creation as long as no activities were assigned to the course and no participant groups created
  apps/frontend-manage/src/components/courses/CourseOverviewHeader.tsx
  apps/frontend-manage/src/components/courses/modals/CourseManipulationModal.tsx
  apps/frontend-manage/src/pages/courses/[id].tsx
  cypress/cypress/e2e/N-course-workflow.cy.ts
  packages/graphql/src/services/courses.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:M

#4805 enhance(apps/docs): rework documentation for answer collections, live quiz and live q&a
  apps/docs/docs/tutorials/answer_collections.mdx
  apps/docs/docs/tutorials/course_management.mdx
  apps/docs/docs/tutorials/element_management.mdx
  apps/docs/docs/tutorials/live_qa.mdx
  apps/docs/docs/tutorials/live_quiz.mdx
  apps/docs/docs/tutorials/ppt_integration.mdx
  apps/docs/src/pages/about.tsx
  apps/docs/static/img/answer_collections/answer_collection_create.jpeg
  apps/docs/static/img/answer_collections/answer_collection_create.png
  apps/docs/static/img/answer_collections/answer_collection_edit.jpeg
  apps/docs/static/img/answer_collections/answer_collection_edit.png
  apps/docs/static/img/answer_collections/answer_collection_edit2.jpeg
  apps/docs/static/img/answer_collections/answer_collection_edit2.png
  apps/docs/static/img/answer_collections/answer_collection_edit3.jpeg
  apps/docs/static/img/answer_collections/answer_collection_edit3.png
  apps/docs/static/img/answer_collections/answer_collection_overview.jpeg
  apps/docs/static/img/answer_collections/answer_collection_overview.png
  apps/docs/static/img/answer_collections/answer_collection_usage.png
  apps/docs/static/img/answer_collections/answer_collection_usage_cs.png
  apps/docs/static/img/supported_element_types/CS_lecturer.png
Labels: enhancement, size:L

#4807 enhance(apps/control-frontend): change login method for frontend-control to Edu-ID
  apps/frontend-control/.env.development
  apps/frontend-control/.env.production
  apps/frontend-control/.env.qa
  apps/frontend-control/.env.test
  apps/frontend-control/src/components/common/LoginForm.tsx
  apps/frontend-control/src/pages/login.tsx
  apps/frontend-manage/src/components/common/Countdown.tsx
  apps/frontend-manage/src/components/common/Header.tsx
  apps/frontend-manage/src/pages/token.tsx
  cypress/cypress.config.ts
  cypress/cypress/e2e/C-control-workflow.cy.ts
  cypress/cypress/support/commands.ts
  packages/graphql/src/graphql/ops/MGenerateLoginToken.graphql
  packages/graphql/src/graphql/ops/MLoginUserToken.graphql
  packages/graphql/src/graphql/ops/QGetLoginToken.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/schema/query.ts
  packages/graphql/src/schema/user.ts
  packages/graphql/src/services/accounts.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/prisma/src/prisma/migrations/20250729083503_remove_control_login_token/migration.sql
  packages/prisma/src/prisma/schema/user.prisma
Labels: enhancement, size:XL

#4809 enhance(apps/docs): update documentation for microlearnings and practice quizzes
  apps/docs/docs/tutorials/live_quiz.mdx
  apps/docs/docs/tutorials/microlearning.mdx
  apps/docs/docs/tutorials/practice_quiz.mdx
  apps/docs/sidebars.js
  apps/docs/src/components/CatalystTitle.tsx
Labels: enhancement, size:L

#4810 enhance(apps/docs): introduce documentation on participant group management and update group activity documentation
  apps/docs/docs/student_tutorials/groups_activities.mdx
  apps/docs/docs/tutorials/course_management.mdx
  apps/docs/docs/tutorials/group_activity.mdx
  apps/docs/docs/tutorials/live_qa.mdx
  apps/docs/docs/tutorials/live_quiz.mdx
  apps/docs/docs/tutorials/microlearning.mdx
  apps/docs/docs/tutorials/participant_group_management.mdx
  apps/docs/docs/tutorials/practice_quiz.mdx
  apps/docs/sidebars.js
  apps/docs/static/img/group_activity/creation_options.png
  apps/docs/static/img/group_activity/creation_questions.png
  apps/docs/static/img/group_activity/creation_settings.png
  apps/docs/static/img/group_activity/creation_stack.png
  apps/docs/static/img/group_activity/ga_grading_view.png
  apps/docs/static/img/group_activity/ga_list.png
  apps/docs/static/img/practice_quiz/pq_olat_view.png
  packages/prisma/src/data/seedTEST.ts
Labels: enhancement, size:L

#4811 enhance(apps/frontend-manage): allow to choose language of live quiz embedding links
  apps/auth/package.json
  apps/docs/package.json
  apps/frontend-control/package.json
  apps/frontend-manage/package.json
  apps/frontend-manage/src/components/activities/overview/ActivityActions.tsx
  apps/frontend-manage/src/components/courses/getLTIAccessLink.tsx
  apps/frontend-manage/src/components/groups/UserGroupEntry.tsx
  apps/frontend-manage/src/components/interaction/feedbacks/FeedbackSearchAndFilters.tsx
  apps/frontend-manage/src/components/liveQuiz/EmbeddingModal.tsx
  apps/frontend-manage/src/components/liveQuiz/HMACLink.tsx
  apps/frontend-manage/src/components/questions/Element.tsx
  apps/frontend-pwa/package.json
  apps/office-addin/package.json
  packages/markdown/package.json
  packages/shared-components/package.json
  packages/transactional/package.json
  pnpm-lock.yaml
Labels: enhancement, size:L

#4812 fix(apps/frontend-manage): add correct dependencies to dnd drop context to avoid loosing stack or block metadata
  apps/frontend-manage/src/components/activities/creation/StackBlockCreation.tsx
  apps/frontend-manage/src/components/activities/creation/StackCreationStep.tsx
  apps/frontend-manage/src/components/activities/creation/groupActivity/GroupActivityStackClues.tsx
  apps/frontend-manage/src/components/activities/creation/liveQuiz/LiveQuizCreationBlock.tsx
  apps/frontend-manage/src/components/activities/creation/liveQuiz/LiveQuizQuestionsStep.tsx
Labels: dependencies, size:XS

#4813 chore: finish up implementation of activity details modal and minor restructuring
  apps/frontend-manage/src/components/activities/overview/ActivityDetailsModal.tsx
  apps/frontend-manage/src/components/activities/overview/ActivityDetailsStack.tsx
  apps/frontend-manage/src/components/activities/overview/ActivityOutdatedElementWarning.tsx
  apps/frontend-manage/src/components/activities/overview/ActivityPointsTable.tsx
  cypress/cypress/e2e/0-baseline-ops.cy.ts
  cypress/cypress/e2e/A-login-workflow.cy.ts
  cypress/cypress/e2e/B-feature-access-workflow.cy.ts
  cypress/cypress/e2e/C-control-workflow.cy.ts
  cypress/cypress/e2e/D-elements-content-workflow.cy.ts
  cypress/cypress/e2e/E-elements-flashcards-workflow.cy.ts
  cypress/cypress/e2e/F-elements-sc-workflow.cy.ts
  cypress/cypress/e2e/G-elements-mc-workflow.cy.ts
  cypress/cypress/e2e/H-elements-kprim-workflow.cy.ts
  cypress/cypress/e2e/I-elements-numerical-workflow.cy.ts
  cypress/cypress/e2e/J-elements-free-text-workflow.cy.ts
  cypress/cypress/e2e/K-elements-selection-workflow.cy.ts
  cypress/cypress/e2e/L-elements-case-study-workflow.cy.ts
  cypress/cypress/e2e/MA-elements-operations-workflow.cy.ts
  cypress/cypress/e2e/MB-instance-updates-workflow.cy.ts
  cypress/cypress/e2e/N-course-workflow.cy.ts
  cypress/cypress/e2e/O-live-quiz-workflow.cy.ts
  cypress/cypress/e2e/P-microlearning-workflow.cy.ts
  cypress/cypress/e2e/Q-practice-quiz-workflow.cy.ts
  cypress/cypress/e2e/R-bookmarking-workflow.cy.ts
  cypress/cypress/e2e/S-group-activity-workflow.cy.ts
  cypress/cypress/e2e/T-resources-workflow.cy.ts
  cypress/cypress/e2e/U-catalog-workflow.cy.ts
  cypress/cypress/e2e/V-template-workflow.cy.ts
  cypress/cypress/e2e/W-activity-log-workflow.cy.ts
  cypress/cypress/fixtures/O-live-quiz.json
  cypress/cypress/fixtures/P-microlearning.json
  cypress/cypress/fixtures/Q-practice-quiz.json
  cypress/cypress/fixtures/S-group-activity.json
  cypress/cypress/support/commands.ts
  packages/graphql/src/graphql/ops/FActivityDetails.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/activities.ts
  packages/graphql/src/services/activities.ts
  packages/graphql/src/services/groups.ts
  packages/graphql/src/services/stacks.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/shared-components/src/evaluation/ChoiceFeedback.tsx
Labels: feature, size:XXL
