Repository uzh-bf/klicker-uzh, pull requests merged in 2025-03, with the labels that each got.

#4538 enhance(apps/frontend-manage): show sharing functionalities for object admin or owner on catalog object
  apps/frontend-manage/src/components/catalog/import/CatalogObjectItem.tsx
  apps/frontend-manage/src/components/catalog/import/ObjectSharingModal.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionItem.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionSharingModal.tsx
  apps/frontend-manage/src/components/resources/answerCollections/TransferAnswerCollectionOwnershipModal.tsx
  apps/frontend-manage/src/lib/hooks/useCatalogObjectActionsDropdown.tsx
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:L

#4539 enhance: add functionality for editors to change name of catalog collection and approve associated requests
  apps/frontend-manage/src/components/catalog/administration/CatalogCollectionListItem.tsx
  apps/frontend-manage/src/components/catalog/collections/CatalogCollectionNameChangeModal.tsx
  apps/frontend-manage/src/components/catalog/import/CatalogSharingRequest.tsx
  apps/frontend-manage/src/components/catalog/import/SharingRequestApprovalModal.tsx
  packages/graphql/src/graphql/ops/MChangeCatalogCollectionName.graphql
  packages/graphql/src/graphql/ops/QGetCatalogCollectionsList.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/services/sharing.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:L

#4540 chore(cypress): extend coverage of test suite to include catalog collection functionalities
  apps/frontend-manage/src/components/catalog/collections/CatalogCollectionSharingModal.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionSharingModal.tsx
  cypress/cypress.config.ts
  cypress/cypress/e2e/L-catalog-workflow.cy.ts
  cypress/cypress/fixtures/L-catalog.json
  cypress/cypress/support/commands.ts
Labels: enhancement, size:XL

#4543 refactor: unify ownership transfer modals across different object types
  apps/frontend-manage/src/components/catalog/actions/ObjectSharingModal.tsx
  apps/frontend-manage/src/components/catalog/actions/SharingRequestApprovalModal.tsx
  apps/frontend-manage/src/components/catalog/actions/useRequestCatalogObject.ts
  apps/frontend-manage/src/components/catalog/administration/CatalogCollectionListItem.tsx
  apps/frontend-manage/src/components/catalog/collections/CatalogCollectionPermissionsTable.tsx
  apps/frontend-manage/src/components/catalog/collections/CatalogCollectionSharingModal.tsx
  apps/frontend-manage/src/components/catalog/collections/TransferCatalogCollectionOwnershipModal.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionItem.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionPermissionsTable.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionSharingModal.tsx
  apps/frontend-manage/src/components/resources/answerCollections/TransferAnswerCollectionOwnershipModal.tsx
  apps/frontend-manage/src/components/sharing/CollectionAccessRemovalErrorToast.tsx
  apps/frontend-manage/src/components/sharing/CollectionAccessRemovalSuccessToast.tsx
  apps/frontend-manage/src/components/sharing/CollectionSharingErrorToast.tsx
  apps/frontend-manage/src/components/sharing/CollectionSharingSuccessToast.tsx
  apps/frontend-manage/src/components/sharing/DirectSharingForm.tsx
  apps/frontend-manage/src/components/sharing/ExistingPermissionEntries.tsx
  apps/frontend-manage/src/components/sharing/GrantedPermissionsTable.tsx
  apps/frontend-manage/src/components/sharing/ModifyOwnPermissionsModal.tsx
  apps/frontend-manage/src/components/sharing/ObjectPermissionLevel.tsx
  apps/frontend-manage/src/components/sharing/PermissionsTable.tsx
  apps/frontend-manage/src/components/sharing/TransferOwnershipErrorToast.tsx
  apps/frontend-manage/src/components/sharing/TransferOwnershipModal.tsx
  apps/frontend-manage/src/components/sharing/TransferOwnershipSuccessToast.tsx
  apps/frontend-manage/src/components/sharing/useTransferObjectOwnership.ts
  apps/frontend-manage/src/lib/hooks/usePermissionLevelSelection.ts
  cypress/cypress/e2e/K-resources-workflow.cy.ts
  cypress/cypress/e2e/L-catalog-workflow.cy.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:XL

#4545 refactor: combine sharing modals into generic approach with properly separated logic
  apps/frontend-manage/src/components/catalog/actions/CatalogObjectItem.tsx
  apps/frontend-manage/src/components/catalog/actions/ObjectSharingModal.tsx
  apps/frontend-manage/src/components/catalog/actions/SharingRequestApprovalModal.tsx
  apps/frontend-manage/src/components/catalog/administration/CatalogCollectionListItem.tsx
  apps/frontend-manage/src/components/catalog/collections/CatalogCollectionAccessRemovalErrorToast.tsx
  apps/frontend-manage/src/components/catalog/collections/CatalogCollectionAccessRemovalSuccessToast.tsx
  apps/frontend-manage/src/components/catalog/collections/CatalogCollectionPermissionsTable.tsx
  apps/frontend-manage/src/components/catalog/collections/CatalogCollectionSharingModal.tsx
  apps/frontend-manage/src/components/catalog/collections/CatalogCollectionSharingSuccessToast.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionItem.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionPermissionsTable.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionSharingModal.tsx
  apps/frontend-manage/src/components/sharing/CollectionSharingErrorToast.tsx
  apps/frontend-manage/src/components/sharing/GrantedPermissionsTable.tsx
  apps/frontend-manage/src/components/sharing/ObjectAccessRemovalErrorToast.tsx
  apps/frontend-manage/src/components/sharing/ObjectAccessRemovalSuccessToast.tsx
  apps/frontend-manage/src/components/sharing/ObjectSharingErrorToast.tsx
  apps/frontend-manage/src/components/sharing/ObjectSharingModal.tsx
  apps/frontend-manage/src/components/sharing/ObjectSharingModalWrapper.tsx
  apps/frontend-manage/src/components/sharing/ObjectSharingSuccessToast.tsx
  apps/frontend-manage/src/components/sharing/PermissionsTable.tsx
  apps/frontend-manage/src/components/sharing/useObjectActionPermissions.ts
  apps/frontend-manage/src/components/sharing/useObjectPermissions.ts
  apps/frontend-manage/src/components/sharing/useObjectSharing.ts
  apps/frontend-manage/src/components/sharing/usePermissionLevelChange.ts
  apps/frontend-manage/src/components/sharing/usePermissionRevocation.ts
  apps/frontend-manage/src/components/sharing/useTransferObjectOwnership.ts
  apps/frontend-manage/src/lib/hooks/useCatalogCollectionActionsDropdown.tsx
  apps/frontend-manage/src/lib/hooks/useCatalogObjectActionsDropdown.tsx
  cypress/cypress/e2e/L-catalog-workflow.cy.ts
  packages/graphql/src/graphql/ops/MChangeAnswerCollectionPermissionLevel.graphql
  packages/graphql/src/graphql/ops/MRevokeAnswerCollectionAccess.graphql
  packages/graphql/src/graphql/ops/MRevokeCollectionAccess.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/services/resources.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:XXL

#4546 refactor: combine access change modals into single component and generalize access requests
  apps/frontend-manage/src/components/catalog/actions/CatalogChangeAccessModal.tsx
  apps/frontend-manage/src/components/catalog/actions/CatalogObjectItem.tsx
  apps/frontend-manage/src/components/catalog/actions/CatalogRequestErrorToast.tsx
  apps/frontend-manage/src/components/catalog/actions/CatalogRequestModal.tsx
  apps/frontend-manage/src/components/catalog/actions/CatalogRequestSuccessToast.tsx
  apps/frontend-manage/src/components/catalog/actions/ObjectChangeAccessModal.tsx
  apps/frontend-manage/src/components/catalog/administration/CatalogCollectionListItem.tsx
  apps/frontend-manage/src/components/catalog/collections/CatalogCollectionChangeAccessModal.tsx
  apps/frontend-manage/src/components/resources/AnswerCollections.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionItem.tsx
  apps/frontend-manage/src/components/resources/answerCollections/CollectionRemovalModal.tsx
  apps/frontend-manage/src/components/sharing/ObjectRemovalErrorToast.tsx
  apps/frontend-manage/src/components/sharing/ObjectRemovalModal.tsx
  apps/frontend-manage/src/components/sharing/ObjectRemovalSuccessToast.tsx
  apps/frontend-manage/src/components/sharing/useObjectRemoval.ts
  cypress/cypress/e2e/K-resources-workflow.cy.ts
  cypress/cypress/e2e/L-catalog-workflow.cy.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:XL

#4547 refactor: unify graphql catalog and sharing operations for different object types with same return types
  apps/frontend-manage/src/components/catalog/actions/useImportCatalogObject.ts
  apps/frontend-manage/src/components/catalog/actions/useRequestCancellationCatalogObject.ts
  apps/frontend-manage/src/components/catalog/actions/useRequestCatalogObject.ts
  apps/frontend-manage/src/components/catalog/administration/AddObjectToCatalogModal.tsx
  apps/frontend-manage/src/components/sharing/useObjectPermissions.ts
  apps/frontend-manage/src/components/sharing/useObjectSharing.ts
  apps/frontend-manage/src/components/sharing/usePermissionLevelChange.ts
  apps/frontend-manage/src/components/sharing/usePermissionRevocation.ts
  apps/frontend-manage/src/components/sharing/useTransferObjectOwnership.ts
  cypress/cypress/e2e/K-resources-workflow.cy.ts
  packages/graphql/src/graphql/ops/FCatalogObjectData.graphql
  packages/graphql/src/graphql/ops/MAddAnswerCollectionToCatalog.graphql
  packages/graphql/src/graphql/ops/MAddObjectToCatalog.graphql
  packages/graphql/src/graphql/ops/MCancelAnswerCollectionRequest.graphql
  packages/graphql/src/graphql/ops/MCancelObjectSharingRequest.graphql
  packages/graphql/src/graphql/ops/MChangeCatalogCollectionPermissionLevel.graphql
  packages/graphql/src/graphql/ops/MImportAnswerCollection.graphql
  packages/graphql/src/graphql/ops/MImportCatalogObject.graphql
  packages/graphql/src/graphql/ops/MRequestAnswerCollection.graphql
  packages/graphql/src/graphql/ops/MRequestCatalogObject.graphql
  packages/graphql/src/graphql/ops/MRevokeAnswerCollectionAccess.graphql
  packages/graphql/src/graphql/ops/MRevokeCatalogCollectionAccess.graphql
  packages/graphql/src/graphql/ops/MRevokeObjectAccess.graphql
  packages/graphql/src/graphql/ops/MShareAnswerCollection.graphql
  packages/graphql/src/graphql/ops/MShareObject.graphql
  packages/graphql/src/graphql/ops/MTransferCatalogCollectionOwnership.graphql
  packages/graphql/src/graphql/ops/MTransferCollectionOwnership.graphql
  packages/graphql/src/graphql/ops/MTransferObjectOwnership.graphql
  packages/graphql/src/graphql/ops/QChangePermissionLevel.graphql
  packages/graphql/src/graphql/ops/QGetAnswerCollectionPermissions.graphql
  packages/graphql/src/graphql/ops/QGetCatalogCollectionPermissions.graphql
  packages/graphql/src/graphql/ops/QGetCatalogObjects.graphql
  packages/graphql/src/graphql/ops/QGetObjectPermissions.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/schema/query.ts
  packages/graphql/src/services/resources.ts
  packages/graphql/src/services/sharing.ts
Labels: enhancement, size:XXL

#4548 refactor: simplify service functions to leverage shared logic between object types
  apps/frontend-manage/src/components/catalog/actions/useRequestCatalogObject.ts
  apps/frontend-manage/src/components/sharing/usePermissionLevelChange.ts
  packages/graphql/src/graphql/ops/MRequestCatalogObject.graphql
  packages/graphql/src/graphql/ops/QChangePermissionLevel.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/services/sharing.ts
Labels: enhancement, size:XXL

#4549 enhance: add testing with database interactions for graphql package
  .github/workflows/test-graphql.yml
  package.json
  packages/graphql/package.json
  packages/graphql/run-tests.sh
  packages/graphql/src/services/resources.ts
  packages/graphql/src/services/sharing.ts
  packages/graphql/test/docker/Dockerfile.test
  packages/graphql/test/docker/docker-compose.test.yml
  packages/graphql/test/sharing.test.ts
  packages/graphql/test/sharingData.ts
Labels: enhancement, size:XXL

#4550 enhance: introduce activity template database structures and add hidden UI elements for template creation dialog
  apps/frontend-manage/src/components/catalog/actions/info/CatalogAdditionalObjectInfo.tsx
  apps/frontend-manage/src/components/courses/modals/TemplateConversionModal.tsx
  apps/frontend-manage/src/components/liveQuiz/LiveQuiz.tsx
  packages/graphql/src/graphql/ops/QCheckTemplateInfoAvailable.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/query.ts
  packages/graphql/src/schema/sharing.ts
  packages/graphql/src/services/sharing.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/prisma/src/prisma/migrations/20250311124701_template_database_structure/migration.sql
  packages/prisma/src/prisma/schema/quiz.prisma
  packages/prisma/src/prisma/schema/resources.prisma
  packages/types/src/index.ts
  packages/util/src/index.ts
Labels: feature, size:XL

#4551 fix: ensure that live quiz is removed from course on corresponding wizard selection when editing
  apps/frontend-manage/src/components/activities/creation/liveQuiz/submitLiveQuizForm.tsx
  packages/graphql/src/services/liveQuizzes.ts
Labels: size:M

#4553 enhance: add creation logic for live quiz templates
  .gitignore
  apps/frontend-manage/src/components/courses/modals/TemplateConversionModal.tsx
  apps/frontend-manage/src/components/courses/modals/TemplateCreationErrorToast.tsx
  apps/frontend-manage/src/components/courses/modals/TemplateCreationSuccessToast.tsx
  apps/frontend-manage/src/components/liveQuiz/LiveQuiz.tsx
  apps/frontend-manage/src/pages/quizzes/index.tsx
  packages/graphql/src/graphql/ops/QCreateActivityTemplate.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/services/groups.ts
  packages/graphql/src/services/sharing.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/prisma/src/prisma/schema/resources.prisma
Labels: enhancement, size:XXL

#4554 enhance: support editing and deletion functionalities for live quiz templates
  .gitignore
  apps/frontend-manage/src/components/courses/modals/TemplateConversionModal.tsx
  apps/frontend-manage/src/components/courses/modals/TemplateDeletionErrorToast.tsx
  apps/frontend-manage/src/components/courses/modals/TemplateDeletionModal.tsx
  apps/frontend-manage/src/components/courses/modals/TemplateDeletionSuccessToast.tsx
  apps/frontend-manage/src/components/courses/modals/TemplateEditErrorToast.tsx
  apps/frontend-manage/src/components/courses/modals/TemplateEditModal.tsx
  apps/frontend-manage/src/components/courses/modals/TemplateEditSuccessToast.tsx
  apps/frontend-manage/src/components/courses/modals/TemplateFormFields.tsx
  apps/frontend-manage/src/components/liveQuiz/LiveQuiz.tsx
  packages/graphql/src/graphql/ops/MDeleteActivityTemplate.graphql
  packages/graphql/src/graphql/ops/MEditActivityTemplate.graphql
  packages/graphql/src/graphql/ops/QGetTemplateInformation.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/schema/query.ts
  packages/graphql/src/schema/sharing.ts
  packages/graphql/src/services/sharing.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  scratchpad.md
Labels: enhancement, size:XXL

#4555 chore(cypress): extend test suite to cover the creation, editing, and deletion of live quiz templates
  apps/frontend-manage/src/components/activities/creation/CompletionStep.tsx
  apps/frontend-manage/src/components/courses/GroupActivityElement.tsx
  apps/frontend-manage/src/components/courses/LiveQuizElement.tsx
  apps/frontend-manage/src/components/courses/LiveQuizList.tsx
  apps/frontend-manage/src/components/courses/MicroLearningElement.tsx
  apps/frontend-manage/src/components/courses/PracticeQuizElement.tsx
  apps/frontend-manage/src/components/courses/StatusTag.tsx
  apps/frontend-manage/src/components/courses/modals/TemplateConversionModal.tsx
  apps/frontend-manage/src/components/courses/modals/TemplateEditModal.tsx
  apps/frontend-manage/src/components/liveQuiz/LiveQuiz.tsx
  cypress/cypress/e2e/C-control-workflow.cy.ts
  cypress/cypress/e2e/E-course-workflow.cy.ts
  cypress/cypress/e2e/F-live-quiz-workflow.cy.ts
  cypress/cypress/e2e/G-microlearning-workflow.cy.ts
  cypress/cypress/e2e/H-practice-quiz-workflow.cy.ts
  cypress/cypress/e2e/J-group-activity-workflow.cy.ts
  cypress/cypress/e2e/M-template-workflow.cy.ts
  cypress/cypress/fixtures/F-live-quiz.json
  cypress/cypress/fixtures/M-template.json
  cypress/cypress/fixtures/questions.json
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:XXL

#4556 enhance: implement functionalities to add and remove live quiz templates to catalog
  apps/frontend-manage/src/components/catalog/actions/CatalogObjectItem.tsx
  apps/frontend-manage/src/components/catalog/actions/CatalogSharingRequest.tsx
  apps/frontend-manage/src/components/catalog/actions/ObjectFilters.tsx
  apps/frontend-manage/src/components/catalog/actions/SharingRequestApprovalModal.tsx
  apps/frontend-manage/src/components/catalog/administration/AddObjectToCatalogModal.tsx
  apps/frontend-manage/src/components/catalog/administration/ObjectAccessSelection.tsx
  apps/frontend-manage/src/components/catalog/administration/ObjectTypeSelection.tsx
  apps/frontend-manage/src/components/catalog/administration/SelectObjectForCatalog.tsx
  apps/frontend-manage/src/components/courses/GroupActivityElement.tsx
  apps/frontend-manage/src/components/courses/LiveQuizElement.tsx
  apps/frontend-manage/src/components/courses/MicroLearningElement.tsx
  apps/frontend-manage/src/components/courses/PracticeQuizElement.tsx
  apps/frontend-manage/src/components/courses/modals/TemplateDeletionModal.tsx
  apps/frontend-manage/src/components/liveQuiz/LiveQuiz.tsx
  apps/frontend-manage/src/lib/hooks/useCatalogObjectActionsDropdown.tsx
  packages/graphql/src/graphql/ops/QGetCatalogLiveQuizTemplates.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/schema/query.ts
  packages/graphql/src/services/sharing.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/types/src/index.ts
Labels: enhancement, size:L

#4557 chore(cypress): extend test suite to cover usage of live quiz templates in catalog collections
  apps/frontend-manage/src/components/catalog/actions/CatalogObjectItem.tsx
  cypress/cypress/e2e/F-live-quiz-workflow.cy.ts
  cypress/cypress/e2e/L-catalog-workflow.cy.ts
  cypress/cypress/e2e/M-template-workflow.cy.ts
  cypress/cypress/fixtures/L-catalog.json
  cypress/cypress/fixtures/questions.json
  cypress/cypress/support/commands.ts
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/schema/query.ts
  packages/graphql/src/services/sharing.ts
  packages/graphql/src/services/templates.ts
Labels: enhancement, size:XXL

#4558 wip: implement structure, live quiz settings, and state management for live quiz templates
  apps/frontend-manage/src/components/activities/creation/liveQuiz/AdvancedLiveQuizSettings.tsx
  apps/frontend-manage/src/components/activities/creation/liveQuiz/LiveQuizGradingIllustration.tsx
  apps/frontend-manage/src/components/activities/templates/ActivityRecoveryPrompt.tsx
  apps/frontend-manage/src/components/activities/templates/GroupActivityTemplate.tsx
  apps/frontend-manage/src/components/activities/templates/LiveQuizTemplate.tsx
  apps/frontend-manage/src/components/activities/templates/MicroLearningTemplate.tsx
  apps/frontend-manage/src/components/activities/templates/PracticeQuizTemplate.tsx
  apps/frontend-manage/src/components/activities/templates/SectionCollapsible.tsx
  apps/frontend-manage/src/components/activities/templates/SettingsNotSavedToast.tsx
  apps/frontend-manage/src/components/activities/templates/TemplateInfo.tsx
  apps/frontend-manage/src/components/activities/templates/TouchMonitor.tsx
  apps/frontend-manage/src/components/activities/templates/liveQuiz/LiveQuizTemplateSettings.tsx
  apps/frontend-manage/src/components/activities/templates/liveQuiz/loadProgressFromLiveQuizData.ts
  apps/frontend-manage/src/components/activities/templates/liveQuiz/useInitialLiveQuizTemplateFormData.ts
  apps/frontend-manage/src/components/catalog/actions/CatalogObjectItem.tsx
  apps/frontend-manage/src/lib/hooks/useCatalogObjectActionsDropdown.tsx
  apps/frontend-manage/src/pages/templates/[id].tsx
  packages/graphql/src/graphql/ops/FCatalogObjectData.graphql
  packages/graphql/src/graphql/ops/QGetActivityTemplate.graphql
  packages/graphql/src/index.ts
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/query.ts
  packages/graphql/src/schema/sharing.ts
  packages/graphql/src/schema/template.ts
  packages/graphql/src/services/sharing.ts
  packages/graphql/src/services/templates.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/types/src/index.ts
Labels: feature, size:XXL

#4559 enhance: implement structure of template element component and action to keep unmodified template content
  apps/frontend-manage/src/components/activities/templates/LiveQuizTemplate.tsx
  apps/frontend-manage/src/components/activities/templates/SectionCollapsible.tsx
  apps/frontend-manage/src/components/activities/templates/TemplateElementContent.tsx
  apps/frontend-manage/src/components/activities/templates/TemplateElementPreview.tsx
  apps/frontend-manage/src/components/activities/templates/liveQuiz/LiveQuizTemplateSettings.tsx
  apps/frontend-manage/src/components/activities/templates/liveQuiz/LiveQuizTemplateTimeLimitModal.tsx
  apps/frontend-manage/src/components/activities/templates/liveQuiz/loadProgressFromLiveQuizData.ts
  apps/frontend-manage/src/components/activities/templates/liveQuiz/useInitialLiveQuizTemplateFormData.ts
  apps/frontend-manage/src/components/activities/templates/markElementAsProcessed.ts
  apps/frontend-manage/src/components/activities/templates/types.ts
  apps/frontend-manage/src/components/questions/manipulation/useArtificialElementInstance.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:XL

#4561 enhance: add possibility to replace template instances with existing elements
  apps/auth/package.json
  apps/backend-docker/package.json
  apps/docs/package.json
  apps/frontend-control/package.json
  apps/frontend-manage/package.json
  apps/frontend-manage/src/components/activities/templates/ExistingElementSelectionModal.tsx
  apps/frontend-manage/src/components/activities/templates/LiveQuizTemplate.tsx
  apps/frontend-manage/src/components/activities/templates/TemplateElementContent.tsx
  apps/frontend-manage/src/components/activities/templates/TemplateElementPreview.tsx
  apps/frontend-manage/src/components/activities/templates/goToNextTemplateElement.ts
  apps/frontend-manage/src/components/activities/templates/liveQuiz/LiveQuizTemplateSettings.tsx
  apps/frontend-manage/src/components/activities/templates/markTemplateElementAsProcessed.ts
  apps/frontend-pwa/package.json
  apps/func-incoming-responses/package.json
  apps/func-response-processor/package.json
  apps/office-addin/package.json
  packages/graphql/src/graphql/ops/FElementData.graphql
  packages/graphql/src/graphql/ops/QGetMatchingUserElementsTemplate.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/query.ts
  packages/graphql/src/schema/template.ts
  packages/graphql/src/services/templates.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/markdown/package.json
  packages/shared-components/package.json
  packages/transactional/package.json
  pnpm-lock.yaml
Labels: enhancement, size:XL

#4562 enhance: show warning if a template element is already available in the user's account (name comparison)
  apps/frontend-manage/src/components/activities/templates/ActivityRecoveryPrompt.tsx
  apps/frontend-manage/src/components/activities/templates/TemplateElementContent.tsx
  packages/graphql/src/graphql/ops/QCheckTemplateElementExists.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/query.ts
  packages/graphql/src/services/templates.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:L

#4563 chore(packages/graphql): add unit testing for live quiz template existing element selection fetching
  packages/graphql/src/services/templates.ts
  packages/graphql/test/sharing.test.ts
  packages/graphql/test/template.test.ts
  packages/graphql/test/templateData.ts
Labels: size:XL

#4564 enhance: support the creation of new elements through the live quiz template view
  apps/frontend-manage/src/components/activities/templates/TemplateElementContent.tsx
  apps/frontend-manage/src/components/activities/templates/TemplateElementPreview.tsx
  apps/frontend-manage/src/components/activities/templates/TemplateNewElementModal.tsx
  apps/frontend-manage/src/components/activities/templates/useFormValuesFromElementInstance.ts
  apps/frontend-manage/src/components/questions/manipulation/ElementEditForm.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementEditModal.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementInformationFields.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/AnswerFeedbackSetting.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyCollectionSelection.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyOptions.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/SampleSolutionSetting.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/SelectionOptions.tsx
  apps/frontend-manage/src/components/questions/manipulation/useArtificialElementInstance.ts
  packages/graphql/src/graphql/ops/FElementData.graphql
  packages/graphql/src/graphql/ops/QGetAnswerCollectionsElements.graphql
  packages/graphql/src/graphql/ops/QGetTemplatePreviewAnswerCollectionEntries.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/query.ts
  packages/graphql/src/schema/resource.ts
  packages/graphql/src/services/questions.ts
  packages/graphql/src/services/resources.ts
  packages/graphql/src/services/templates.ts
  packages/graphql/test/sharing.test.ts
Labels: enhancement, size:XXL

#4565 enhance(packages/graphql): implement access control for template queries in backend
  apps/frontend-manage/src/components/activities/templates/TemplateElementPreview.tsx
  packages/graphql/src/services/resources.ts
  packages/graphql/src/services/templates.ts
Labels: size:L

#4566 chore(packages/graphql): extend unit tests to cover template access control and template answer collection queries
  packages/graphql/src/services/templates.ts
  packages/graphql/test/sharing.test.ts
  packages/graphql/test/template.test.ts
Labels: enhancement, size:L

#4567 enhance: implement submission logic for live quiz templates
  apps/frontend-manage/src/components/activities/templates/ActivityRecoveryPrompt.tsx
  apps/frontend-manage/src/components/activities/templates/ExistingElementSelectionModal.tsx
  apps/frontend-manage/src/components/activities/templates/LiveQuizTemplate.tsx
  apps/frontend-manage/src/components/activities/templates/extractFormValuesFromElementInstance.ts
  apps/frontend-manage/src/components/activities/templates/liveQuiz/LiveQuizTemplateSettings.tsx
  apps/frontend-manage/src/components/activities/templates/liveQuiz/LiveQuizTemplateSubmissionButton.tsx
  apps/frontend-manage/src/components/activities/templates/liveQuiz/processLiveQuizTemplateBlocksData.ts
  apps/frontend-manage/src/components/activities/templates/useFormValuesFromElementInstance.ts
  apps/frontend-manage/src/components/catalog/actions/CatalogChangeAccessModal.tsx
  apps/frontend-manage/src/components/catalog/collections/CatalogCollectionDeletionModal.tsx
  apps/frontend-manage/src/components/catalog/collections/CreateCatalogCollectionModal.tsx
  apps/frontend-manage/src/pages/templates/[id].tsx
  apps/frontend-manage/tsconfig.json
  packages/graphql/src/graphql/ops/MCreateLiveQuizFromTemplate.graphql
  packages/graphql/src/lib/validateAndProcessElementOptions.ts
  packages/graphql/src/lib/validateCaseStudyOptions.ts
  packages/graphql/src/lib/validateElementInputs.ts
  packages/graphql/src/lib/validateFreeTextOptions.ts
  packages/graphql/src/lib/validateKPRIMOptions.ts
  packages/graphql/src/lib/validateMCOptions.ts
  packages/graphql/src/lib/validateNumericalOptions.ts
  packages/graphql/src/lib/validateSCOptions.ts
  packages/graphql/src/lib/validateSelectionOptions.ts
  packages/graphql/src/lib/validateSharedChoicesFields.ts
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/schema/practiceQuiz.ts
  packages/graphql/src/schema/question.ts
  packages/graphql/src/services/questions.ts
  packages/graphql/src/services/resources.ts
  packages/graphql/src/services/templates.ts
  packages/graphql/test/templateData.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/types/src/index.ts
Labels: enhancement, size:XXL

#4568 fix(packages/graphql): make sure that graphql test suite runs sequentially
  packages/graphql/src/services/resources.ts
  packages/graphql/test/docker/Dockerfile.test
  packages/graphql/test/sharing.test.ts
  packages/graphql/test/template.test.ts
Labels: size:L

#4569 chore(cypress): extend cypress test suite to cover the use of live quiz templates
  apps/frontend-manage/src/components/activities/templates/ExistingElementSelectionModal.tsx
  apps/frontend-manage/src/components/activities/templates/LiveQuizTemplate.tsx
  apps/frontend-manage/src/components/activities/templates/NewElementDataDiscardingModal.tsx
  apps/frontend-manage/src/components/activities/templates/TemplateElementContent.tsx
  apps/frontend-manage/src/components/activities/templates/TemplateInfo.tsx
  apps/frontend-manage/src/components/activities/templates/goToNextTemplateElement.ts
  apps/frontend-manage/src/components/activities/templates/liveQuiz/LiveQuizTemplateSubmissionButton.tsx
  apps/frontend-manage/src/components/catalog/actions/ObjectImport.tsx
  apps/frontend-manage/src/components/questions/QuestionList.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementInformationFields.tsx
  cypress/cypress/e2e/M-template-workflow.cy.ts
  cypress/cypress/fixtures/M-template.json
  cypress/cypress/fixtures/questions.json
  cypress/cypress/support/commands.ts
  cypress/package.json
  packages/graphql/src/services/templates.ts
  pnpm-lock.yaml
Labels: enhancement, size:XXL

#4570 enhance(packages/graphql): block deletion or removal of answer collections that are linked to activity templates
  packages/graphql/src/services/resources.ts
  packages/graphql/src/services/sharing.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:XL

#4571 style(apps/frontend-manage): improve UX for live quiz template workflow with unified styling logic
  apps/frontend-manage/src/components/activities/templates/TemplateElementContent.tsx
  cypress/cypress/e2e/M-template-workflow.cy.ts
Labels: enhancement, size:S

#4575 chore(cypress): extend test suite to cover different cases for activity editing with missing elements / resources
  apps/frontend-manage/src/components/liveQuiz/LiveQuiz.tsx
  cypress/cypress/e2e/F-live-quiz-workflow.cy.ts
  cypress/cypress/e2e/G-microlearning-workflow.cy.ts
  cypress/cypress/e2e/H-practice-quiz-workflow.cy.ts
  cypress/cypress/fixtures/F-live-quiz.json
  cypress/cypress/fixtures/G-microlearning.json
  cypress/cypress/fixtures/H-practice-quiz.json
  cypress/cypress/fixtures/questions.json
Labels: size:XXL

#4579 enhance(apps/frontend-manage): add option to show explanation on evaluation view
  apps/frontend-manage/src/components/evaluation/ActivityEvaluation.tsx
  apps/frontend-manage/src/components/evaluation/ElementChart.tsx
  apps/frontend-manage/src/components/evaluation/ElementEvaluation.tsx
  apps/frontend-manage/src/components/evaluation/EvaluationFooter.tsx
  apps/frontend-manage/src/components/evaluation/elements/CSEvaluation.tsx
  apps/frontend-manage/src/components/evaluation/elements/CSEvaluationHistogram.tsx
  apps/frontend-manage/src/components/evaluation/elements/CSEvaluationScatter.tsx
  apps/frontend-manage/src/components/evaluation/elements/ChoicesEvaluation.tsx
  apps/frontend-manage/src/components/evaluation/elements/FTEvaluation.tsx
  apps/frontend-manage/src/components/evaluation/elements/NREvaluation.tsx
  apps/frontend-manage/src/components/evaluation/elements/SEEvaluation.tsx
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/shared-components/dist/utilities.css
  packages/shared-components/src/charts/ElementBarChart.tsx
  packages/shared-components/src/charts/ElementHistogram.tsx
  packages/shared-components/src/charts/ElementTableChart.tsx
  packages/shared-components/src/charts/ElementWordcloud.tsx
  packages/shared-components/src/evaluation/EvaluationExplanation.tsx
Labels: enhancement, size:XL

#4580 fix(apps/frontend-manage): resolve issues with case study options updates on criterion or item deletion
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyCollectionSelection.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyCriteriaFields.tsx
Labels: size:L

#4581 enhance(apps/frontend-manage): improve live quiz template view and template conversion modal
  apps/frontend-manage/src/components/activities/templates/ExistingElementSelectionModal.tsx
  apps/frontend-manage/src/components/activities/templates/LiveQuizTemplate.tsx
  apps/frontend-manage/src/components/activities/templates/TemplateElementContent.tsx
  apps/frontend-manage/src/components/activities/templates/liveQuiz/useInitialLiveQuizTemplateFormData.ts
  apps/frontend-manage/src/components/activities/templates/types.ts
  apps/frontend-manage/src/components/courses/modals/TemplateConversionModal.tsx
  apps/frontend-manage/src/components/courses/modals/TemplateFormFields.tsx
  apps/frontend-manage/src/components/liveQuiz/LiveQuiz.tsx
  packages/graphql/src/graphql/ops/QGetUserLiveQuizzes.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/groupActivity.ts
  packages/graphql/src/schema/liveQuiz.ts
  packages/graphql/src/schema/microLearning.ts
  packages/graphql/src/schema/practiceQuiz.ts
  packages/graphql/src/services/courses.ts
  packages/graphql/src/services/templates.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/prisma/src/prisma/migrations/20250324152155_template_name_tracking/migration.sql
  packages/prisma/src/prisma/schema/quiz.prisma
Labels: enhancement, size:L

#4582 feat: add support for step / likert scale criteria on case study elements
  apps/auth/package.json
  apps/backend-docker/package.json
  apps/docs/package.json
  apps/frontend-control/package.json
  apps/frontend-manage/package.json
  apps/frontend-manage/src/components/activities/templates/extractFormValuesFromElementInstance.ts
  apps/frontend-manage/src/components/questions/manipulation/ElementFormErrors.tsx
  apps/frontend-manage/src/components/questions/manipulation/InstanceUpdateSwitch.tsx
  apps/frontend-manage/src/components/questions/manipulation/helpers.ts
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyCasesFields.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyCriteriaFields.tsx
  apps/frontend-manage/src/components/questions/manipulation/types.ts
  apps/frontend-manage/src/components/questions/manipulation/useArtificialElementInstance.ts
  apps/frontend-manage/src/components/questions/manipulation/useElementFormInitialValues.ts
  apps/frontend-manage/src/components/questions/manipulation/useValidationSchema.ts
  apps/frontend-pwa/package.json
  apps/frontend-pwa/src/components/liveQuiz/FeedbackArea.tsx
  apps/func-incoming-responses/package.json
  apps/func-response-processor/package.json
  apps/office-addin/package.json
  cypress/cypress/e2e/D9-questions-case-study-workflow.cy.ts
  cypress/cypress/support/commands.ts
  packages/graphql/src/graphql/ops/FElementData.graphql
  packages/graphql/src/graphql/ops/FElementDataWithoutSolutions.graphql
  packages/graphql/src/graphql/ops/MManipulateCaseStudyQuestion.graphql
  packages/graphql/src/graphql/ops/QGetSingleQuestion.graphql
  packages/graphql/src/graphql/ops/QGetUserQuestions.graphql
  packages/graphql/src/lib/validateAndProcessElementOptions.ts
  packages/graphql/src/lib/validateCaseStudyOptions.ts
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/elementData.ts
  packages/graphql/src/schema/evaluation.ts
  packages/graphql/src/schema/question.ts
  packages/graphql/src/services/stacks.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/markdown/package.json
  packages/shared-components/dist/utilities.css
  packages/shared-components/package.json
  packages/shared-components/src/evaluation/CSEvaluation.tsx
  packages/shared-components/src/questions/CSCase.tsx
  packages/shared-components/src/questions/CSSlider.tsx
  packages/transactional/package.json
  packages/types/src/index.ts
  pnpm-lock.yaml
Labels: feature, size:XL

#4584 enhance(apps/frontend-manage): update validation logic for step and likert criteria on case study elements to support exact solutions
  apps/frontend-manage/src/components/questions/manipulation/InstanceUpdateSwitch.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyCasesFields.tsx
  apps/frontend-manage/src/components/questions/manipulation/useValidationSchema.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:M

#4585 chore(cypress): extend test suite to include the creation of likert criteria on case study elements
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyCriteriaFields.tsx
  cypress/cypress/e2e/D9-questions-case-study-workflow.cy.ts
  cypress/cypress/fixtures/D-questions.json
  cypress/cypress/fixtures/questions.json
  cypress/cypress/support/commands.ts
Labels: enhancement, size:XL

#4586 chore: transform app styles to tailwind classes where possible
  apps/auth/src/pages/_app.tsx
  apps/frontend-control/src/pages/_app.tsx
  apps/frontend-manage/src/pages/_app.tsx
  apps/frontend-pwa/src/pages/_app.tsx
Labels: enhancement, size:M

#4589 enhance(apps/frontend-manage): extend evaluation view for case study elements with step criteria
  apps/frontend-manage/src/components/evaluation/elements/CSEvaluationHistogram.tsx
  apps/frontend-manage/src/components/evaluation/elements/CSEvaluationHistogramChart.tsx
  apps/frontend-manage/src/components/evaluation/elements/CSOneDimScatterPlot.tsx
  apps/frontend-manage/src/components/evaluation/elements/CSTwoDimScatterPlot.tsx
  apps/frontend-manage/src/components/evaluation/elements/getLabelForValue.ts
  packages/graphql/src/graphql/ops/FEvaluationResults.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/evaluation.ts
  packages/graphql/src/services/stacks.ts
Labels: enhancement, size:L

#4590 enhance(apps/frontend-manage): improve UI components of for answer collection editing and add search functionality
  apps/frontend-manage/src/components/resources/answerCollections/AddAnswerCollectionEntry.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionEditModal.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionMetaForm.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionOption.tsx
  apps/frontend-manage/src/components/resources/answerCollections/TouchMonitor.tsx
  cypress/cypress/e2e/D8-questions-selection-workflow.cy.ts
  cypress/cypress/e2e/D9-questions-case-study-workflow.cy.ts
  cypress/cypress/e2e/K-resources-workflow.cy.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:L

#4591 enhance(apps/frontend-manage): extend answer collection viewing modal with accordion and search functionality
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionItem.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionViewingModal.tsx
  cypress/cypress/e2e/K-resources-workflow.cy.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:L

#4593 enhance: improve display of content element, improve display of question content on library (raw text with max lines), foundations for content element in LQ
  .windsurfrules
  apps/frontend-manage/src/components/activities/creation/WizardElementList.tsx
  apps/frontend-manage/src/components/common/ContentInput.tsx
  apps/frontend-manage/src/components/evaluation/ElementEvaluation.tsx
  apps/frontend-manage/src/components/evaluation/elements/CTEvaluation.tsx
  apps/frontend-manage/src/components/questions/Question.tsx
  packages/markdown/package.json
  packages/markdown/src/Ellipsis.tsx
  packages/markdown/src/Markdown.tsx
  packages/markdown/src/public/components.css
  packages/markdown/src/public/utilities.css
  packages/markdown/tailwind.config.cjs
  packages/shared-components/dist/utilities.css
  packages/shared-components/src/ContentElement.tsx
  packages/shared-components/src/utils/slateMdConversion.ts
  pnpm-lock.yaml
Labels: enhancement, size:XXL

#4592 enhance(apps/frontend-manage): add option to trigger refetch of answer collections on element edit modal options
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyCollectionSelection.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyOptions.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/SelectionOptions.tsx
Labels: enhancement, size:L

#4594 fix(packages/graphql): ensure that links between templates and required resources are updated on element instance update
  packages/graphql/src/lib/context.ts
  packages/graphql/src/services/questions.ts
  packages/graphql/src/services/templates.ts
Labels: size:L

#4595 chore(packages/graphql): add unit testing for template instance updates
  packages/graphql/test/template.test.ts
Labels: size:L
