Repository uzh-bf/klicker-uzh, pull requests merged in 2025-06, with the labels that each got.

#4724 fix: update tailwind structure to ensure that design-system styles are properly applied
  apps/auth/package.json
  apps/auth/src/globals.css
  apps/auth/src/pages/_app.tsx
  apps/auth/tailwind.config.mjs
  apps/backend-docker/package.json
  apps/docs/package.json
  apps/docs/tailwind.config.mjs
  apps/frontend-control/package.json
  apps/frontend-control/src/globals.css
  apps/frontend-control/src/pages/_app.tsx
  apps/frontend-control/tailwind.config.mjs
  apps/frontend-manage/package.json
  apps/frontend-manage/src/globals.css
  apps/frontend-manage/src/pages/_app.tsx
  apps/frontend-manage/tailwind.config.mjs
  apps/frontend-pwa/package.json
  apps/frontend-pwa/src/globals.css
  apps/frontend-pwa/src/pages/_app.tsx
  apps/frontend-pwa/tailwind.config.mjs
  apps/func-incoming-responses/package.json
  apps/func-response-processor/package.json
  apps/office-addin/package.json
  apps/office-addin/tailwind.config.js
  packages/markdown/package.json
  packages/shared-components/package.json
  packages/transactional/package.json
  pnpm-lock.yaml
Labels: enhancement, size:L

#4729 enhance(apps/frontend-pwa): hide functionalities not available to temporary participants on live quiz view and update existing pages to correctly handle temporary participant accounts
  apps/backend-docker/src/app.ts
  apps/frontend-pwa/src/components/Layout.tsx
  apps/frontend-pwa/src/components/common/AvatarWithLevel.tsx
  apps/frontend-pwa/src/components/common/Header.tsx
  apps/frontend-pwa/src/components/common/MobileMenuBar.tsx
  apps/frontend-pwa/src/components/practiceQuiz/PracticeQuiz.tsx
  apps/frontend-pwa/src/components/practiceQuiz/PracticeQuizOverview.tsx
  apps/frontend-pwa/src/pages/404.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/join.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/microlearning/[id]/[ix].tsx
  apps/frontend-pwa/src/pages/course/[courseId]/microlearning/[id]/evaluation.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/microlearning/[id]/index.tsx
  apps/frontend-pwa/src/pages/editProfile.tsx
  apps/frontend-pwa/src/pages/index.tsx
  apps/func-incoming-responses/src/index.ts
  apps/func-response-processor/src/index.ts
  cypress/cypress/e2e/A-login-workflow.cy.ts
  cypress/cypress/e2e/P-microlearning-workflow.cy.ts
  cypress/cypress/e2e/P-microlearning-workflow_LEGACY.cy.ts
  cypress/cypress/e2e/S-group-activity-workflow.cy.ts
  cypress/cypress/e2e/S-group-activity-workflow_LEGACY.cy.ts
  packages/graphql/src/services/accounts.ts
  packages/graphql/src/services/courses.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/graphql/src/services/participants.ts
  packages/graphql/src/services/practiceQuizzes.ts
  packages/graphql/src/services/stacks.ts
Labels: size:L

#4730 enhance: add possibility to select avatar from selection for temporary accounts without login
  apps/frontend-pwa/src/components/liveQuiz/AccountSelector.tsx
  apps/frontend-pwa/src/components/liveQuiz/CarouselMonitor.tsx
  packages/graphql/src/graphql/ops/MLoginTemporaryParticipant.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/services/accounts.ts
  packages/graphql/src/services/participants.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/shared-components/src/Leaderboard.tsx
Labels: enhancement, size:L

#4732 fix(apps/frontend-manage): resolve rendering loop that blocked creation of case study elements
  apps/frontend-manage/src/components/evaluation/hooks/useChartTypeUpdate.tsx
  apps/frontend-manage/src/components/evaluation/hooks/useStackInstanceUpdates.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyCollectionSelection.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/SelectionCollectionOptions.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/SelectionManualItemCreation.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/useAnswerCollectionChangeEffect.ts
  apps/frontend-manage/src/components/questions/manipulation/options/useSelectionItemsChangeEffect.ts
  apps/frontend-manage/src/components/questions/manipulation/options/useSolutionsUpdateItemsChange.ts
  apps/frontend-pwa/src/components/hooks/useRemainingInstances.ts
Labels: size:L

#4735 chore(cypress): extend e2e testing to cover participation in gamified live quiz without participant account
  apps/frontend-manage/src/components/common/Header.tsx
  apps/frontend-manage/src/components/liveQuiz/cockpit/LiveQuizQRModal.tsx
  apps/frontend-manage/src/components/liveQuiz/cockpit/LiveQuizTimeline.tsx
  apps/frontend-manage/src/pages/qr/[...args].tsx
  apps/frontend-pwa/src/components/common/Header.tsx
  apps/frontend-pwa/src/components/liveQuiz/AccountSelector.tsx
  cypress/cypress/e2e/O-live-quiz-workflow.cy.ts
  cypress/cypress/fixtures/O-live-quiz.json
  packages/shared-components/src/Participant.tsx
Labels: enhancement, size:L

#4738 enhance(packages/shared-components): add possibility to override lower and upper bounds of histogram within bounds
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/shared-components/dist/utilities.css
  packages/shared-components/src/charts/ElementHistogram.tsx
  packages/shared-components/src/evaluation/NREvaluation.tsx
Labels: enhancement, size:L

#4740 style(apps/frontend-manage): resolve datepicker and input styling issues, add countdowns to activity details view
  apps/auth/package.json
  apps/backend-docker/package.json
  apps/docs/package.json
  apps/frontend-control/package.json
  apps/frontend-manage/package.json
  apps/frontend-manage/src/components/activities/overview/ActivityDetailsModal.tsx
  apps/frontend-pwa/package.json
  apps/frontend-pwa/src/components/liveQuiz/AccountSelector.tsx
  apps/frontend-pwa/src/components/liveQuiz/QuestionArea.tsx
  apps/frontend-pwa/src/pages/session/[id].tsx
  apps/func-incoming-responses/package.json
  apps/func-response-processor/package.json
  apps/office-addin/package.json
  packages/graphql/src/graphql/ops/FActivityInfoData.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/activities.ts
  packages/graphql/src/services/activities.ts
  packages/graphql/src/services/courses.ts
  packages/markdown/package.json
  packages/prisma/src/data/seedTEST.ts
  packages/shared-components/package.json
  packages/transactional/package.json
  pnpm-lock.yaml
Labels: enhancement, dependencies, size:M

#4741 enhance(apps/frontend-pwa): add basic animations to gamified live quizzes
  apps/auth/package.json
  apps/backend-docker/package.json
  apps/docs/package.json
  apps/frontend-control/package.json
  apps/frontend-manage/package.json
  apps/frontend-manage/src/components/interaction/feedbacks/Feedback.tsx
  apps/frontend-pwa/package.json
  apps/frontend-pwa/src/components/liveQuiz/AllQuestionsAnsweredMessage.tsx
  apps/frontend-pwa/src/components/liveQuiz/FeedbackArea.tsx
  apps/frontend-pwa/src/components/liveQuiz/FeedbackAreaSubscriber.tsx
  apps/frontend-pwa/src/components/liveQuiz/PublicFeedback.tsx
  apps/frontend-pwa/src/components/liveQuiz/QuestionArea.tsx
  apps/frontend-pwa/src/pages/session/[id].tsx
  apps/func-incoming-responses/package.json
  apps/func-response-processor/package.json
  apps/office-addin/package.json
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/markdown/package.json
  packages/shared-components/package.json
  packages/transactional/package.json
  pnpm-lock.yaml
Labels: enhancement, size:L

#4745 enhance(apps/frontend-pwa): replace menubar on student course docs with tabs
  apps/frontend-pwa/src/components/docs/DocsLayout.tsx
Labels: enhancement, size:M

#4746 feat(apps/olat-api): define API for OLAT user activity queries
  .github/workflows/test-olat-api.yml
  apps/olat-api/.dockerignore
  apps/olat-api/.gitignore
  apps/olat-api/Dockerfile
  apps/olat-api/package.json
  apps/olat-api/rollup.config.js
  apps/olat-api/run-tests.sh
  apps/olat-api/src/index.ts
  apps/olat-api/static/activityTypes.json
  apps/olat-api/test/docker/Dockerfile.test
  apps/olat-api/test/docker/docker-compose.test.yml
  apps/olat-api/test/helpers.ts
  apps/olat-api/test/index.test.ts
  apps/olat-api/test/userData.ts
  apps/olat-api/tsconfig.json
  bruno/https---localhost-3020-hello.bru
  packages/prisma/src/data/seedAccounts.ts
  packages/prisma/src/data/seedTEST.ts
  pnpm-lock.yaml
  turbo.json
Labels: feature, size:XXL

#4695 chore: support local https using traefik
  .gitignore
  .vscode/launch.json
  apps/auth/.env.development
  apps/frontend-control/.env.development
  apps/frontend-manage/.env.development
  apps/frontend-pwa/.env.development
  apps/frontend-pwa/capacitor.config.ts
  docker-compose.yml
  util/traefik/rules_docker.yaml
  util/traefik/rules_wsl.yaml
Labels: deployment, size:L

#4757 implement autogenerated secrets and .env files for backend and hatchet
  .windsurfrules
  CLAUDE.md
  _generate_hatchet_token.sh
  apps/backend-docker/.env.template
  apps/backend-docker/.gitignore
  apps/backend-docker/package.json
  apps/hatchet/.env.example
  apps/hatchet/.gitignore
  apps/hatchet/package.json
  docker-compose.yml
  util/_run_with_doppler.sh
  util/hatchet/README.md
  util/hatchet/_generate_hatchet_token.sh
  util/hatchet/docker-compose.hatchet-token.yml
  util/hatchet/env-updater.sh
  util/hatchet/token-generator.sh
Labels: size:XL
