Repository uzh-bf/klicker-uzh, pull requests merged in 2025-05, with the labels that each got.

#4653 chore(cypress): resolve issues in test suite and ensure proper atomicity for independence of workflows
  .github/workflows/cypress-testing.yml
  apps/frontend-manage/src/components/courses/GroupActivityList.tsx
  apps/frontend-manage/src/components/courses/LiveQuizList.tsx
  apps/frontend-manage/src/components/courses/MicroLearningList.tsx
  apps/frontend-manage/src/components/courses/PracticeQuizList.tsx
  cypress/cypress.config.ts
  cypress/cypress/e2e/A-login-workflow.cy.ts
  cypress/cypress/e2e/B-feature-access-workflow.cy.ts
  cypress/cypress/e2e/C-control-workflow.cy.ts
  cypress/cypress/e2e/D-elements-content-workflow.cy.ts
  cypress/cypress/e2e/E-elements-flashcards-workflow.cy.ts
  cypress/cypress/e2e/F-elements-sc-workflow.cy.ts
  cypress/cypress/e2e/G-elements-mc-workflow.cy.ts
  cypress/cypress/e2e/H-elements-kprim-workflow.cy.ts
  cypress/cypress/e2e/I-elements-numerical-workflow.cy.ts
  cypress/cypress/e2e/J-elements-free-text-workflow.cy.ts
  cypress/cypress/e2e/K-elements-selection-workflow.cy.ts
  cypress/cypress/e2e/L-elements-case-study-workflow.cy.ts
  cypress/cypress/e2e/M-elements-operations-workflow.cy.ts
  cypress/cypress/e2e/N-course-workflow.cy.ts
  cypress/cypress/e2e/O-live-quiz-workflow.cy.ts
  cypress/cypress/e2e/P-microlearning-workflow.cy.ts
  cypress/cypress/e2e/Q-practice-quiz-workflow.cy.ts
  cypress/cypress/e2e/R-bookmarking-workflow.cy.ts
  cypress/cypress/e2e/S-group-activity-workflow.cy.ts
  cypress/cypress/e2e/T-resources-workflow.cy.ts
  cypress/cypress/e2e/U-catalog-workflow.cy.ts
  cypress/cypress/e2e/V-template-workflow.cy.ts
  cypress/cypress/fixtures/B-feature-access.json
  cypress/cypress/fixtures/questions.json
  cypress/cypress/support/commands.ts
  cypress/package.json
  pnpm-lock.yaml
Labels: size:XXL

#4654 enhance(apps/frontend-manage): add separate confirmation step for permission revocation including hint to derived permissions
  apps/frontend-manage/src/components/sharing/ExistingPermissionEntries.tsx
  apps/frontend-manage/src/components/sharing/PermissionRevocationModal.tsx
  cypress/cypress/e2e/M-elements-operations-workflow.cy.ts
  cypress/cypress/e2e/T-resources-workflow.cy.ts
  packages/graphql/src/services/resources.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:L

#4655 feat: implement direct object sharing functionalities for user groups
  apps/frontend-manage/src/components/sharing/DirectSharingForm.tsx
  apps/frontend-manage/src/components/sharing/useObjectSharing.ts
  packages/graphql/src/services/sharing.ts
Labels: feature, size:L

#4656 fix(packages/util): ensure that user group owners are also granted permissions on objects shared with the group
  packages/graphql/test/catalogPermissions.test.ts
  packages/graphql/test/resourcePermissions.test.ts
  packages/util/src/permissions.ts
Labels: size:L

#4657 chore(packages/graphql): add unit testing to all existing sharing functionalities related to user groups
  packages/graphql/src/services/sharing.ts
  packages/graphql/test/catalogSharing.test.ts
  packages/graphql/test/elementSharing.test.ts
  packages/graphql/test/helpers.ts
  packages/graphql/test/resourceSharing.test.ts
  packages/util/src/permissions.ts
Labels: size:XXL

#4658 chore(cypress): extend e2e testing to include direct user group sharing functionalities
  apps/frontend-manage/src/components/sharing/DirectSharingForm.tsx
  cypress/cypress/e2e/M-elements-operations-workflow.cy.ts
  cypress/cypress/e2e/T-resources-workflow.cy.ts
  cypress/cypress/e2e/U-catalog-workflow.cy.ts
  cypress/cypress/fixtures/DM-questions.json
  cypress/cypress/fixtures/T-resources.json
  cypress/cypress/fixtures/U-catalog.json
  cypress/cypress/support/commands.ts
Labels: enhancement, size:XL

#4660 enhance: improve and restructure the recomputation logic for access requests (including user group support)
  packages/graphql/src/services/groups.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/graphql/src/services/microLearning.ts
  packages/graphql/src/services/practiceQuizzes.ts
  packages/graphql/src/services/sharing.ts
  packages/graphql/src/services/templates.ts
  packages/graphql/test/access.test.ts
  packages/util/src/permissions.ts
Labels: enhancement, size:XXL

#4663 feat: implement sharing functionalities for live quizzes
  apps/frontend-manage/src/components/activities/overview/ActivityListEntry.tsx
  apps/frontend-manage/src/components/activities/overview/LiveQuizActions.tsx
  apps/frontend-manage/src/components/catalog/actions/CatalogObjectItem.tsx
  apps/frontend-manage/src/components/catalog/administration/ObjectTypeSelection.tsx
  apps/frontend-manage/src/components/courses/modals/TemplateConversionModal.tsx
  apps/frontend-manage/src/components/sharing/DirectSharingForm.tsx
  apps/frontend-manage/src/components/sharing/ObjectPermissionLevel.tsx
  apps/frontend-manage/src/components/sharing/PermissionsTable.tsx
  apps/frontend-manage/src/components/sharing/PropagatedPermissionsTable.tsx
  apps/frontend-manage/src/components/sharing/useObjectActionPermissions.ts
  apps/frontend-manage/src/components/sharing/useObjectPropagatedPermissions.ts
  apps/frontend-manage/src/components/sharing/useTransferObjectOwnership.ts
  apps/frontend-manage/src/lib/hooks/usePermissionLevelSelection.ts
  cypress/cypress/e2e/V-template-workflow.cy.ts
  packages/graphql/src/graphql/ops/QGetUserActivities.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/activities.ts
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/schema/query.ts
  packages/graphql/src/services/activities.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/graphql/src/services/sharing.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/types/src/index.ts
Labels: feature, size:XXL

#4664 enhance: add possibility to remove live quizzes that are not shared through user groups, owner or accessed through group permissions
  apps/frontend-manage/src/components/activities/overview/ActivityListEntry.tsx
  apps/frontend-manage/src/components/activities/overview/ActivityRemovalModal.tsx
  apps/frontend-manage/src/components/activities/overview/LiveQuizActions.tsx
  apps/frontend-manage/src/components/catalog/administration/AddObjectToCatalogModal.tsx
  cypress/cypress/e2e/O-live-quiz-workflow.cy.ts
  packages/graphql/src/graphql/ops/MRemoveLiveQuiz.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:L

#4665 chore(packages/graphql): add unit testing for live quiz sharing functionalities
  packages/graphql/src/schema/participant.ts
  packages/graphql/src/services/courses.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/graphql/src/services/sharing.ts
  packages/graphql/test/access.test.ts
  packages/graphql/test/activitySharing.test.ts
  packages/graphql/test/helpers.ts
  packages/prisma/src/data/seedLevels.ts
  packages/util/rollup.config.js
  packages/util/src/index.ts
  packages/util/src/levels.ts
Labels: enhancement, size:XXL

#4666 chore(cypress): extend e2e testing for live quiz sharing functionalities
  apps/auth/package.json
  apps/backend-docker/package.json
  apps/docs/package.json
  apps/frontend-control/package.json
  apps/frontend-manage/package.json
  apps/frontend-manage/src/components/activities/creation/CompletionStep.tsx
  apps/frontend-manage/src/components/activities/overview/ActivityDetailsModal.tsx
  apps/frontend-manage/src/components/sharing/ObjectAccessRemovalSuccessToast.tsx
  apps/frontend-manage/src/components/sharing/ObjectSharingSuccessToast.tsx
  apps/frontend-pwa/package.json
  apps/func-incoming-responses/package.json
  apps/func-response-processor/package.json
  apps/office-addin/package.json
  cypress/cypress.config.ts
  cypress/cypress/e2e/M-elements-operations-workflow.cy.ts
  cypress/cypress/e2e/N-course-workflow.cy.ts
  cypress/cypress/e2e/O-live-quiz-workflow.cy.ts
  cypress/cypress/fixtures/O-live-quiz.json
  cypress/cypress/support/commands.ts
  packages/markdown/package.json
  packages/shared-components/package.json
  packages/transactional/package.json
  pnpm-lock.yaml
Labels: size:XXL

#4667 chore(apps/frontend-manage): make sure element edit form inputs are disabled for user with read permissions on shared element
  apps/frontend-manage/src/components/questions/Element.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementContentInput.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementEditForm.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementEditModal.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementExplanationField.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementFormScoringSection.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementInformationFields.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyCasesFields.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyCollectionSelection.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyCriteriaFields.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyOptions.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/ChoicesOptions.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/DisplayModeSetting.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/FreeTextOptions.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/NumericalExactSolutionsInput.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/NumericalOptions.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/NumericalSolutionRangesInput.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/NumericalSolutionTypeSwitch.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/SelectionOptions.tsx
  apps/frontend-manage/src/components/questions/tags/SuspendedTagInput.tsx
  cypress/cypress.config.ts
Labels: enhancement, size:XL

#4668 enhance: replace live quiz overview on course with new activity list when feature flag is set
  apps/frontend-manage/src/components/activities/overview/LiveQuizActions.tsx
  apps/frontend-manage/src/components/courses/GroupActivityList.tsx
  apps/frontend-manage/src/components/courses/LiveQuizList.tsx
  apps/frontend-manage/src/components/courses/MicroLearningList.tsx
  apps/frontend-manage/src/components/courses/PracticeQuizList.tsx
  apps/frontend-manage/src/components/questions/Element.tsx
  apps/frontend-manage/src/pages/courses/[id].tsx
  packages/graphql/src/graphql/ops/FActivityInfoData.graphql
  packages/graphql/src/graphql/ops/QGetSingleCourse.graphql
  packages/graphql/src/graphql/ops/QGetUserActivities.graphql
  packages/graphql/src/graphql/ops/QGetUserCourses.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/activities.ts
  packages/graphql/src/schema/course.ts
  packages/graphql/src/schema/question.ts
  packages/graphql/src/services/courses.ts
  packages/prisma/src/prisma/migrations/20250507144816_template_answer_collection_entry_link/migration.sql
  packages/prisma/src/prisma/schema/course.prisma
  packages/prisma/src/prisma/schema/element.prisma
Labels: enhancement, size:XL

#4670 enhance: add possibility to remove shared courses from account
  apps/frontend-manage/src/components/courses/CourseArchiveButton.tsx
  apps/frontend-manage/src/components/courses/CourseListButton.tsx
  apps/frontend-manage/src/components/courses/modals/CourseArchiveModal.tsx
  apps/frontend-manage/src/components/courses/modals/CourseDeletionModal.tsx
  apps/frontend-manage/src/components/courses/modals/CourseRemovalModal.tsx
  apps/frontend-manage/src/components/sharing/GrantedPermissionsTable.tsx
  apps/frontend-manage/src/pages/courses/index.tsx
  packages/graphql/src/graphql/ops/MRemoveCourse.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/services/courses.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:XL

#4671 fix(packages/util): favor direct permissions with propagation enabled over direct permissions with same permission level without
  packages/util/src/permissions.ts
Labels: size:M

#4672 chore(packages/graphql): add unit testing for course sharing functionality
  packages/graphql/src/schema/query.ts
  packages/graphql/src/services/sharing.ts
  packages/graphql/test/access.test.ts
  packages/graphql/test/activitySharing.test.ts
  packages/graphql/test/catalogSharing.test.ts
  packages/graphql/test/courseSharing.test.ts
  packages/graphql/test/elementSharing.test.ts
  packages/graphql/test/helpers.ts
  packages/graphql/test/resourceSharing.test.ts
Labels: size:XL

#4673 chore(packages/graphql): add migration script for the recomputation of derived permissions for existing objects
  packages/graphql/package.json
  packages/graphql/src/scripts/2025-05-08_derived_permissions_migration.ts
  packages/graphql/src/services/questions.ts
  packages/graphql/src/services/templates.ts
  pnpm-lock.yaml
Labels: size:L

#4674 enhance(packages/util): improve efficiency of derived permission recomputation for entire objects
  packages/graphql/src/services/sharing.ts
  packages/util/src/permissions.ts
Labels: enhancement, size:XXL

#4675 chore(cypress): implement end-to-end testing for course sharing functionalities
  apps/frontend-manage/src/components/activities/overview/ActivityListEntry.tsx
  apps/frontend-manage/src/components/questions/Element.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionItem.tsx
  apps/frontend-manage/src/components/sharing/ObjectPermissionLevel.tsx
  cypress/cypress.config.ts
  cypress/cypress/e2e/N-course-workflow.cy.ts
  cypress/cypress/fixtures/N-course.json
  cypress/cypress/support/commands.ts
Labels: enhancement, size:XXL

#4676 enhance(packages/graphql): implement backend logic for sharing functionalities of practice quizzes, microlearning and group activities
  apps/frontend-manage/src/components/activities/overview/ActivityList.tsx
  apps/frontend-manage/src/components/activities/overview/ActivityListLegend.tsx
  apps/frontend-manage/src/components/common/Header.tsx
  apps/frontend-manage/src/components/courses/LiveQuizList.tsx
  apps/frontend-manage/src/pages/activities.tsx
  packages/graphql/src/graphql/ops/MRemoveGroupActivity.graphql
  packages/graphql/src/graphql/ops/MRemoveMicroLearning.graphql
  packages/graphql/src/graphql/ops/MRemovePracticeQuiz.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/schema/query.ts
  packages/graphql/src/services/activities.ts
  packages/graphql/src/services/groups.ts
  packages/graphql/src/services/microLearning.ts
  packages/graphql/src/services/practiceQuizzes.ts
  packages/graphql/src/services/sharing.ts
  packages/types/src/index.ts
Labels: size:XXL

#4678 fix: resolve issues with object removal logic and implement a single graphql endpoint for all object types
  apps/frontend-manage/src/components/activities/overview/ActivityRemovalModal.tsx
  apps/frontend-manage/src/components/catalog/actions/CatalogObjectItem.tsx
  apps/frontend-manage/src/components/catalog/actions/CatalogObjectRemovalModal.tsx
  apps/frontend-manage/src/components/courses/modals/CourseRemovalModal.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementRemovalModal.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionItem.tsx
  apps/frontend-manage/src/components/sharing/AnswerCollectionRemovalModal.tsx
  apps/frontend-manage/src/components/sharing/ObjectRemovalModal.tsx
  apps/frontend-manage/src/components/sharing/ObjectSharingModalWrapper.tsx
  apps/frontend-manage/src/components/sharing/useObjectRemoval.ts
  apps/frontend-manage/src/components/sharing/useTransferObjectOwnership.ts
  packages/graphql/src/graphql/ops/MRemoveAnswerCollection.graphql
  packages/graphql/src/graphql/ops/MRemoveCourse.graphql
  packages/graphql/src/graphql/ops/MRemoveElement.graphql
  packages/graphql/src/graphql/ops/MRemoveGroupActivity.graphql
  packages/graphql/src/graphql/ops/MRemoveLiveQuiz.graphql
  packages/graphql/src/graphql/ops/MRemoveMicroLearning.graphql
  packages/graphql/src/graphql/ops/MRemoveObject.graphql
  packages/graphql/src/graphql/ops/MRemovePracticeQuiz.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/services/questions.ts
  packages/graphql/src/services/resources.ts
Labels: size:XL

#4679 chore(cypress): extend end-to-end testing to cover object removal for all supported objects
  apps/frontend-manage/src/components/activities/overview/ActivityRemovalModal.tsx
  apps/frontend-manage/src/components/activities/overview/LiveQuizActions.tsx
  apps/frontend-manage/src/components/courses/modals/ActivityConfirmationModal.tsx
  apps/frontend-manage/src/components/sharing/TransferOwnershipSuccessToast.tsx
  apps/frontend-manage/src/components/sharing/useTransferObjectOwnership.ts
  cypress/cypress/e2e/N-course-workflow.cy.ts
  cypress/cypress/e2e/O-live-quiz-workflow.cy.ts
  packages/graphql/src/graphql/ops/FActivityInfoData.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/activities.ts
  packages/graphql/src/services/activities.ts
  packages/graphql/src/services/courses.ts
  packages/graphql/test/resources.test.ts
Labels: size:XL

#4683 refactor(packages/util): split permissions functionality into submodules
  packages/util/src/permissions.ts
  packages/util/src/permissions/accessRequest.ts
  packages/util/src/permissions/answerCollection.ts
  packages/util/src/permissions/catalog.ts
  packages/util/src/permissions/constants.ts
  packages/util/src/permissions/course.ts
  packages/util/src/permissions/element.ts
  packages/util/src/permissions/groupActivity.ts
  packages/util/src/permissions/liveQuiz.ts
  packages/util/src/permissions/microlearning.ts
  packages/util/src/permissions/practiceQuiz.ts
  packages/util/src/permissions/util.ts
Labels: size:XXL

#4685 enhance(apps/frontend-manage): activate element instance update trigger by default
  apps/frontend-manage/src/components/questions/manipulation/ElementEditModal.tsx
  apps/frontend-manage/src/components/questions/manipulation/InstanceUpdateSwitch.tsx
  cypress/cypress/e2e/M-elements-operations-workflow.cy.ts
  cypress/cypress/e2e/O-live-quiz-workflow.cy.ts
  cypress/cypress/e2e/O-live-quiz-workflow_LEGACY.cy.ts
  cypress/cypress/e2e/P-microlearning-workflow.cy.ts
  cypress/cypress/e2e/P-microlearning-workflow_LEGACY.cy.ts
  cypress/cypress/e2e/Q-practice-quiz-workflow.cy.ts
  cypress/cypress/e2e/Q-practice-quiz-workflow_LEGACY.cy.ts
  packages/shared-components/src/Loader.tsx
Labels: enhancement, size:L

#4686 enhance: improve display of shared or dependent objects in user accounts
  apps/frontend-manage/src/components/activities/overview/ActivityListEntry.tsx
  apps/frontend-manage/src/components/activities/overview/ActivityOverviewFilters.tsx
  apps/frontend-manage/src/components/questions/Element.tsx
  apps/frontend-manage/src/components/questions/tags/SuspendedTags.tsx
  apps/frontend-manage/src/components/questions/tags/TagList.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionItem.tsx
  apps/frontend-manage/src/components/sharing/SharingTypeBadge.tsx
  apps/frontend-manage/src/lib/hooks/useSortingAndFiltering.ts
  apps/frontend-manage/src/lib/utils/filters.ts
  apps/frontend-manage/src/pages/activities.tsx
  apps/frontend-manage/src/pages/index.tsx
  cypress/cypress/e2e/N-course-workflow.cy.ts
  cypress/cypress/e2e/O-live-quiz-workflow.cy.ts
  cypress/cypress/e2e/T-resources-workflow.cy.ts
  packages/graphql/src/graphql/ops/FActivityInfoData.graphql
  packages/graphql/src/graphql/ops/MCreateAnswerCollection.graphql
  packages/graphql/src/graphql/ops/QGetAnswerCollectionsInfo.graphql
  packages/graphql/src/graphql/ops/QGetUserElements.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/activities.ts
  packages/graphql/src/schema/question.ts
  packages/graphql/src/schema/resource.ts
  packages/graphql/src/schema/sharing.ts
  packages/graphql/src/services/activities.ts
  packages/graphql/src/services/courses.ts
  packages/graphql/src/services/questions.ts
  packages/graphql/src/services/resources.ts
  packages/graphql/src/services/sharing.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/types/src/index.ts
Labels: enhancement, size:XL

#4687 enhance(apps/frontend-manage): store filters and sorting states from library in local storage
  apps/frontend-manage/src/components/questions/tags/SuspendedTags.tsx
  apps/frontend-manage/src/components/questions/tags/TagList.tsx
  apps/frontend-manage/src/lib/hooks/useSortingAndFiltering.ts
  apps/frontend-manage/src/pages/activities.tsx
  apps/frontend-manage/src/pages/index.tsx
  cypress/cypress/e2e/N-course-workflow.cy.ts
  cypress/cypress/e2e/O-live-quiz-workflow.cy.ts
Labels: size:M

#4688 enhance: add possibility to show information on origin of derived permission
  apps/frontend-manage/src/components/sharing/DerivedPermissionInfoDialog.tsx
  apps/frontend-manage/src/components/sharing/DerivedPermissionsTable.tsx
  packages/graphql/src/graphql/ops/QGetDerivedPermissionOrigin.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/query.ts
  packages/graphql/src/schema/sharing.ts
  packages/graphql/src/services/sharing.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:XL

#4689 enhance(apps/frontend-manage): support activity removal functionality for practice quizzes, microlearning and group activities
  apps/frontend-manage/src/components/activities/actions/useGroupActivityActions.ts
  apps/frontend-manage/src/components/activities/actions/useMicroLearningActions.ts
  apps/frontend-manage/src/components/activities/actions/usePracticeQuizActions.ts
  apps/frontend-manage/src/components/activities/overview/GroupActivityActions.tsx
  apps/frontend-manage/src/components/activities/overview/MicrolearningActions.tsx
  apps/frontend-manage/src/components/activities/overview/PracticeQuizActions.tsx
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:L

#4691 chore(cypress): add end-to-end testing for group activity sharing functionalities
  apps/frontend-manage/src/components/activities/overview/ActivityListEntry.tsx
  cypress/cypress/e2e/S-group-activity-workflow.cy.ts
  cypress/cypress/fixtures/S-group-activity.json
Labels: size:XXL

#4693 enhance: update permission module with optional propagation of permissions to element level
  apps/frontend-manage/src/components/sharing/ObjectSharingModal.tsx
  apps/frontend-manage/src/components/sharing/useObjectPropagatedPermissions.ts
  packages/graphql/test/activityPermissions.test.ts
  packages/graphql/test/activitySharing.test.ts
  packages/graphql/test/elementPermissions.test.ts
  packages/util/src/permissions/element.ts
Labels: enhancement, size:XXL

#4694 enhance: separate element status from remaining element form logic to allow users with read access to change it
  apps/auth/package.json
  apps/backend-docker/package.json
  apps/docs/package.json
  apps/frontend-control/package.json
  apps/frontend-manage/package.json
  apps/frontend-manage/src/components/activities/templates/TemplateNewElementModal.tsx
  apps/frontend-manage/src/components/activities/templates/extractFormValuesFromElementInstance.ts
  apps/frontend-manage/src/components/activities/templates/liveQuiz/processLiveQuizTemplateBlocksData.ts
  apps/frontend-manage/src/components/questions/manipulation/ElementEditForm.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementEditModal.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementInformationFields.tsx
  apps/frontend-manage/src/components/questions/manipulation/helpers.ts
  apps/frontend-manage/src/components/questions/manipulation/types.ts
  apps/frontend-manage/src/components/questions/manipulation/useElementFormInitialValues.ts
  apps/frontend-pwa/package.json
  apps/func-incoming-responses/package.json
  apps/func-response-processor/package.json
  apps/office-addin/package.json
  packages/graphql/src/graphql/ops/MChangeElementStatus.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/services/questions.ts
  packages/markdown/package.json
  packages/shared-components/package.json
  packages/transactional/package.json
  pnpm-lock.yaml
Labels: enhancement, size:L

#4697 enhance(apps/frontend-manage): ensure that newest activity logs are shown at the bottom with automated scrolling
  apps/frontend-manage/src/components/activities/actions/useGroupActivityActions.ts
  apps/frontend-manage/src/components/activities/actions/useLiveQuizActions.ts
  apps/frontend-manage/src/components/activities/actions/useMicroLearningActions.ts
  apps/frontend-manage/src/components/activities/actions/usePracticeQuizActions.ts
  apps/frontend-manage/src/components/questions/Element.tsx
  apps/frontend-manage/src/components/sharing/ActivityLog.tsx
  apps/frontend-manage/src/lib/hooks/useAnswerCollectionActionsDropdown.tsx
  apps/frontend-manage/src/lib/hooks/useObjectActivity.ts
  packages/graphql/src/services/sharing.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:L

#4698 enhance(apps/frontend-manage): improve structure of element actions and show comment functionality to all users with at least read permissions
  apps/docs/docs/getting_started/welcome.mdx
  apps/docs/docs/student_tutorials/student_accounts.mdx
  apps/docs/docs/tutorials/lti_integration.mdx
  apps/docs/src/constants.tsx
  apps/docs/src/pages/development.tsx
  apps/docs/src/pages/use_cases/index.tsx
  apps/frontend-manage/src/components/activities/actions/useAvailableActions.ts
  apps/frontend-manage/src/components/activities/overview/LiveQuizActions.tsx
  apps/frontend-manage/src/components/common/SupportModal.tsx
  apps/frontend-manage/src/components/interaction/feedbacks/Feedback.tsx
  apps/frontend-manage/src/components/questions/Element.tsx
  apps/frontend-manage/src/components/questions/useAvailableElementActions.ts
  apps/frontend-manage/src/components/questions/useElementActions.ts
  cypress/cypress/e2e/M-elements-operations-workflow.cy.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:XL

#4699 enhance: add proper next-intl based translations for activity log change messages
  apps/frontend-manage/src/components/sharing/ActivityLog.tsx
  packages/graphql/src/graphql/ops/FActivityEntryData.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/sharing.ts
  packages/graphql/src/services/sharing.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/types/src/index.ts
Labels: enhancement, size:L

#4700 chore(cypress): resolve flakiness and extend activity log coverage across application
  apps/frontend-manage/src/components/courses/CourseListButton.tsx
  apps/frontend-manage/src/components/questions/Element.tsx
  apps/frontend-manage/src/components/questions/useElementActions.ts
  apps/frontend-manage/src/lib/hooks/useAnswerCollectionActionsDropdown.tsx
  cypress/cypress/e2e/W-activity-log-workflow.cy.ts
  cypress/cypress/fixtures/W-activity-log.json
  packages/i18n/messages/en.ts
Labels: size:XL

#4701 enhance(apps/docs): extend docs with new element types, answer collections and new structure for sharing, etc.
  apps/docs/docs/private-preview.mdx
  apps/docs/docs/tutorials/activity_templates.mdx
  apps/docs/docs/tutorials/answer_collections.mdx
  apps/docs/docs/tutorials/catalog_sharing.mdx
  apps/docs/docs/tutorials/direct_sharing.mdx
  apps/docs/docs/tutorials/group_activity.mdx
  apps/docs/docs/tutorials/live_qa.mdx
  apps/docs/docs/tutorials/live_quiz.mdx
  apps/docs/docs/tutorials/microlearning.mdx
  apps/docs/docs/tutorials/permissions_groups.mdx
  apps/docs/docs/tutorials/ppt_integration.mdx
  apps/docs/docs/tutorials/practice_quiz.mdx
  apps/docs/docs/tutorials/supported_element_types.mdx
  apps/docs/package.json
  apps/docs/sidebars.js
  apps/docs/src/components/CatalystTitle.tsx
  apps/docs/src/components/PrivatePreviewTag.tsx
  apps/docs/src/pages/about.tsx
  apps/docs/static/demo_questions_medical.md
  apps/docs/static/demo_questions_medical_de.md
  apps/docs/static/img/answer_collections/answer_collection_create.jpeg
  apps/docs/static/img/answer_collections/answer_collection_edit.jpeg
  apps/docs/static/img/answer_collections/answer_collection_edit2.jpeg
  apps/docs/static/img/answer_collections/answer_collection_edit3.jpeg
  apps/docs/static/img/answer_collections/answer_collection_overview.jpeg
  apps/docs/static/img/answer_collections/answer_collection_share.jpeg
  apps/docs/static/img/answer_collections/answer_collection_usage.png
  apps/docs/static/img/answer_collections/answer_collection_usage_cs.png
  apps/docs/static/img/sharing/share_answer_collection_matrix.png
  apps/docs/static/img/sharing/share_course_matrix.png
  apps/docs/static/img/sharing/share_course_propagate_no.png
  apps/docs/static/img/sharing/share_course_propagate_yes.png
  apps/docs/static/img/sharing/share_element_matrix.png
  apps/docs/static/img/sharing/share_granted_permissions.png
  apps/docs/static/img/sharing/share_lq_matrix.png
  apps/docs/static/img/sharing/share_ownership_transfer.png
  apps/docs/static/img/supported_element_types/CS_lecturer.png
  apps/docs/static/img/supported_element_types/CS_student.png
  apps/docs/static/img/supported_element_types/SE_lecturer.png
  apps/docs/static/img/supported_element_types/SE_student.png
  pnpm-lock.yaml
Labels: enhancement, size:XXL

#4703 enhance(packages/graphql): add proper audit logging to all object removal service functions
  packages/graphql/src/services/accounts.ts
  packages/graphql/src/services/analytics.ts
  packages/graphql/src/services/courses.ts
  packages/graphql/src/services/feedbacks.ts
  packages/graphql/src/services/groups.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/graphql/src/services/microLearning.ts
  packages/graphql/src/services/notifications.ts
  packages/graphql/src/services/participants.ts
  packages/graphql/src/services/practiceQuizzes.ts
  packages/graphql/src/services/questions.ts
  packages/graphql/src/services/stacks.ts
  packages/graphql/test/activitySharing.test.ts
  packages/graphql/test/courseSharing.test.ts
Labels: enhancement, size:XXL

#4704 feat: add possibility to define case study items inline in element edit form
  apps/frontend-manage/src/components/activities/templates/TemplateNewElementModal.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementEditForm.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementEditModal.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementFormErrors.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementTypeMonitor.tsx
  apps/frontend-manage/src/components/questions/manipulation/helpers.ts
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyCollectionSelection.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyCriterionModeMonitor.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyManualItemCreation.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyOptions.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/SelectionOptions.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/useSelectedAnswerEntry.ts
  apps/frontend-manage/src/components/questions/manipulation/options/useSelectedNewItems.ts
  apps/frontend-manage/src/components/questions/manipulation/types.ts
  apps/frontend-manage/src/components/questions/manipulation/useArtificialElementInstance.ts
  apps/frontend-manage/src/components/questions/manipulation/useElementFormInitialValues.ts
  apps/frontend-manage/src/components/questions/manipulation/useValidationSchema.ts
  apps/frontend-manage/src/pages/index.tsx
  packages/graphql/src/graphql/ops/MCreateAnswerCollection.graphql
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/resource.ts
  packages/graphql/src/services/resources.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: feature, size:XL

#4707 feat: support inline answer collection creation for selection questions
  apps/frontend-manage/src/components/questions/manipulation/ElementEditForm.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementEditModal.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyCollectionSelection.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyOptions.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/SelectionCollectionOptions.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/SelectionManualItemCreation.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/SelectionOptions.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/useAnswerCollectionChangeEffect.ts
  apps/frontend-manage/src/components/questions/manipulation/options/useSelectAnswerCollectionOptions.ts
  apps/frontend-manage/src/components/questions/manipulation/options/useSelectedAnswerEntry.ts
  apps/frontend-manage/src/components/questions/manipulation/options/useSelectionItemsChangeEffect.ts
  apps/frontend-manage/src/components/questions/manipulation/types.ts
  apps/frontend-manage/src/components/questions/manipulation/useValidationSchema.ts
  cypress/cypress/e2e/L-elements-case-study-workflow.cy.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: feature, size:XL

#4708 chore(cypress): extend end-to-end test suite of selection questions to cover inline item definition
  apps/frontend-manage/src/components/questions/manipulation/helpers.ts
  cypress/cypress/e2e/K-elements-selection-workflow.cy.ts
  cypress/cypress/fixtures/DM-questions.json
Labels: size:L

#4710 chore(cypress): cover inline answer collection definition within templates in end-to-end testing
  cypress/cypress/e2e/K-elements-selection-workflow.cy.ts
  cypress/cypress/e2e/V-template-workflow.cy.ts
  cypress/cypress/fixtures/V-template.json
  packages/graphql/src/services/resources.ts
  packages/graphql/test/resources.test.ts
Labels: size:L

#4711 fix: resolve minor issues with inline answer collection definition on case study and selection questions
  apps/frontend-manage/src/components/questions/manipulation/ElementEditForm.tsx
  apps/frontend-manage/src/components/questions/manipulation/ElementEditModal.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyCollectionSelection.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyManualItemCreation.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyOptions.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/NumericalSolutionTypeSwitch.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/SelectionCollectionOptions.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/SelectionManualItemCreation.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/SelectionOptions.tsx
  apps/frontend-manage/src/components/questions/manipulation/useArtificialElementInstance.ts
  apps/frontend-manage/src/components/questions/tags/SuspendedTagInput.tsx
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/shared-components/src/DebouncedUsernameField.tsx
Labels: size:XL

#4712 enhance(apps/frontend-manage): add confidence intervals when hovering over case study scatter plot items
  apps/frontend-manage/src/components/evaluation/elements/CSEvaluationScatter.tsx
  apps/frontend-manage/src/components/evaluation/elements/CSOneDimScatterPlot.tsx
  apps/frontend-manage/src/components/evaluation/elements/CSTwoDimScatterPlot.tsx
  apps/frontend-manage/src/components/evaluation/hooks/useCaseStudyScatterData.tsx
Labels: enhancement, size:L

#4713 feat(apps/frontend-manage): add possibility to open answer collection edit modal directly from element edit modal
  apps/frontend-manage/src/components/questions/manipulation/ElementEditForm.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/AnswerCollectionInlineEditButton.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyCollectionSelection.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyManualItemCreation.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyOptions.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/SelectionCollectionOptions.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/SelectionOptions.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/useSolutionsUpdateItemsChange.ts
  apps/frontend-manage/src/components/resources/answerCollections/AddAnswerCollectionEntry.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionEditModal.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionMetaForm.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionOption.tsx
  packages/graphql/src/graphql/ops/QGetAnswerCollectionsElements.graphql
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/server.json
  packages/graphql/src/services/resources.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: feature, size:XL

#4717 chore: remove owner and name uniqueness constraint for answer collections
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionItem.tsx
  packages/graphql/src/graphql/ops/QGetAnswerCollectionsInfo.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/resource.ts
  packages/graphql/src/services/resources.ts
  packages/graphql/src/services/sharing.ts
  packages/graphql/test/resources.test.ts
  packages/prisma/src/data/seedTEST.ts
  packages/prisma/src/prisma/migrations/20250526152311_remove_answer_collection_name_uniqueness/migration.sql
  packages/prisma/src/prisma/schema/resources.prisma
Labels: size:L

#4722 enhance(apps/frontend-manage): replace date picker with improved component and update cypress test suite accordingly
  apps/auth/package.json
  apps/backend-docker/package.json
  apps/docs/package.json
  apps/frontend-control/package.json
  apps/frontend-manage/package.json
  apps/frontend-manage/src/components/courses/CourseOverviewHeader.tsx
  apps/frontend-manage/src/components/courses/modals/CourseManipulationModal.tsx
  apps/frontend-manage/src/pages/courses/index.tsx
  apps/frontend-pwa/package.json
  apps/func-incoming-responses/package.json
  apps/func-response-processor/package.json
  apps/office-addin/package.json
  cypress/cypress/e2e/N-course-workflow.cy.ts
  cypress/cypress/e2e/V-template-workflow.cy.ts
  packages/markdown/package.json
  packages/shared-components/package.json
  packages/transactional/package.json
  pnpm-lock.yaml
Labels: enhancement, size:L

#4723 enhance(apps/frontend-manage): replace datetime picker component through new version
  apps/auth/package.json
  apps/backend-docker/package.json
  apps/docs/package.json
  apps/frontend-control/package.json
  apps/frontend-manage/package.json
  apps/frontend-manage/src/components/activities/creation/WizardLayout.tsx
  apps/frontend-manage/src/components/activities/creation/groupActivity/GroupActivitySettingsStep.tsx
  apps/frontend-manage/src/components/activities/creation/groupActivity/GroupActivityWizard.tsx
  apps/frontend-manage/src/components/activities/creation/microLearning/MicroLearningSettingsStep.tsx
  apps/frontend-manage/src/components/activities/creation/microLearning/MicroLearningWizard.tsx
  apps/frontend-manage/src/components/courses/modals/CourseManipulationModal.tsx
  apps/frontend-manage/src/components/courses/modals/ExtensionModal.tsx
  apps/frontend-manage/src/components/courses/modals/PracticeQuizPublishingModal.tsx
  apps/frontend-pwa/package.json
  apps/func-incoming-responses/package.json
  apps/func-response-processor/package.json
  apps/office-addin/package.json
  cypress/cypress.config.ts
  cypress/cypress/e2e/M-elements-operations-workflow.cy.ts
  cypress/cypress/e2e/N-course-workflow.cy.ts
  cypress/cypress/e2e/P-microlearning-workflow.cy.ts
  cypress/cypress/e2e/P-microlearning-workflow_LEGACY.cy.ts
  cypress/cypress/e2e/Q-practice-quiz-workflow.cy.ts
  cypress/cypress/e2e/Q-practice-quiz-workflow_LEGACY.cy.ts
  cypress/cypress/e2e/R-bookmarking-workflow.cy.ts
  cypress/cypress/e2e/S-group-activity-workflow.cy.ts
  cypress/cypress/e2e/S-group-activity-workflow_LEGACY.cy.ts
  cypress/cypress/e2e/W-activity-log-workflow.cy.ts
  cypress/cypress/e2e/helpers.ts
  cypress/cypress/support/commands.ts
  packages/markdown/package.json
  packages/prisma/src/data/seedTEST.ts
  packages/shared-components/package.json
  packages/transactional/package.json
  pnpm-lock.yaml
Labels: enhancement, size:XXL
