Repository uzh-bf/klicker-uzh, pull requests merged in 2025-02, with the labels that each got.

#4487 enhance: add evaluation components and computation logic for case study elements in practice quizzes
  apps/auth/package.json
  apps/backend-docker/package.json
  apps/docs/package.json
  apps/frontend-control/package.json
  apps/frontend-manage/package.json
  apps/frontend-pwa/package.json
  apps/func-incoming-responses/package.json
  apps/func-response-processor/package.json
  apps/office-addin/package.json
  packages/markdown/package.json
  packages/shared-components/dist/utilities.css
  packages/shared-components/package.json
  packages/shared-components/src/CaseStudyQuestion.tsx
  packages/shared-components/src/StudentElement.tsx
  packages/shared-components/src/evaluation/CSEvaluation.tsx
  packages/shared-components/src/evaluation/SEEvaluation.tsx
  packages/shared-components/src/hooks/useCaseStudySolutionsObject.ts
  packages/shared-components/src/hooks/useEvaluationBarChartData.ts
  packages/shared-components/src/hooks/useEvaluationCaseStudyResults.ts
  packages/shared-components/src/hooks/useEvaluationHistogramData.ts
  packages/shared-components/src/hooks/useEvaluationTableData.ts
  packages/shared-components/src/questions/CSCase.tsx
  packages/shared-components/src/questions/CSSlider.tsx
  packages/transactional/package.json
  pnpm-lock.yaml
Labels: enhancement, dependencies, size:L

#4488 chore(cypress): extend test suite to cover case study elements in practice quizzes
  apps/frontend-manage/src/components/activities/creation/groupActivity/GroupActivityWizard.tsx
  apps/frontend-manage/src/components/activities/creation/liveQuiz/LiveQuizQuestionsStep.tsx
  apps/frontend-manage/src/components/activities/creation/microLearning/MicroLearningWizard.tsx
  apps/frontend-manage/src/components/activities/creation/practiceQuiz/PracticeQuizWizard.tsx
  cypress/cypress/e2e/H-practice-quiz-workflow.cy.ts
  cypress/cypress/fixtures/H-practice-quiz.json
  cypress/cypress/support/commands.ts
  packages/shared-components/src/evaluation/CSEvaluation.tsx
Labels: size:XL

#4490 enhance: add support for case study elements to microlearnings and enable reloading evaluation
  apps/frontend-pwa/src/components/practiceQuiz/ElementStack.tsx
  packages/graphql/src/graphql/ops/FStackFeedbackEvaluations.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/question.ts
  packages/graphql/src/services/stacks.ts
  packages/prisma/src/data/seedTEST.ts
  packages/shared-components/dist/utilities.css
  packages/types/src/index.ts
Labels: enhancement, size:L

#4491 chore(cypress): extend test suite to cover case study elements in microlearnings
  cypress/cypress/e2e/G-microlearning-workflow.cy.ts
  cypress/cypress/fixtures/G-microlearning.json
Labels: size:L

#4492 feat: support new case study elements on activity evaluation for asynchronous activities with scatter plots
  apps/auth/package.json
  apps/backend-docker/package.json
  apps/docs/package.json
  apps/frontend-control/package.json
  apps/frontend-manage/package.json
  apps/frontend-manage/src/components/evaluation/ElementChart.tsx
  apps/frontend-manage/src/components/evaluation/ElementEvaluation.tsx
  apps/frontend-manage/src/components/evaluation/elements/CSEvaluation.tsx
  apps/frontend-manage/src/components/evaluation/elements/CSEvaluationHistogram.tsx
  apps/frontend-manage/src/components/evaluation/elements/CSEvaluationScatter.tsx
  apps/frontend-manage/src/components/evaluation/elements/CSEvaluationScatterSidebar.tsx
  apps/frontend-manage/src/components/evaluation/elements/CSOneDimScatterPlot.tsx
  apps/frontend-manage/src/components/evaluation/elements/CSTwoDimScatterPlot.tsx
  apps/frontend-manage/src/components/evaluation/elements/CTEvaluation.tsx
  apps/frontend-manage/src/components/evaluation/elements/ChoicesEvaluation.tsx
  apps/frontend-manage/src/components/evaluation/elements/ChoicesSidebar.tsx
  apps/frontend-manage/src/components/evaluation/elements/FCEvaluation.tsx
  apps/frontend-manage/src/components/evaluation/elements/FTEvaluation.tsx
  apps/frontend-manage/src/components/evaluation/elements/FTSidebar.tsx
  apps/frontend-manage/src/components/evaluation/elements/NREvaluation.tsx
  apps/frontend-manage/src/components/evaluation/elements/NRSidebar.tsx
  apps/frontend-manage/src/components/evaluation/elements/QuestionCollapsible.tsx
  apps/frontend-manage/src/components/evaluation/elements/SEEvaluation.tsx
  apps/frontend-manage/src/components/evaluation/hooks/useCaseStudyScatterData.tsx
  apps/frontend-pwa/package.json
  apps/func-incoming-responses/package.json
  apps/func-response-processor/package.json
  apps/office-addin/package.json
  packages/graphql/src/graphql/ops/FEvaluationResults.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/evaluation.ts
  packages/graphql/src/services/stacks.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/markdown/package.json
  packages/prisma/src/data/data/TEST.ts
  packages/shared-components/package.json
  packages/shared-components/src/charts/ElementBarChart.tsx
  packages/shared-components/src/charts/ElementWordcloud.tsx
  packages/shared-components/src/constants.ts
  packages/shared-components/src/evaluation/MCKPRIMEvaluation.tsx
  packages/shared-components/src/evaluation/SCEvaluation.tsx
  packages/shared-components/src/hooks/useEvaluationBarChartData.ts
  packages/shared-components/src/hooks/useEvaluationTableData.ts
  packages/shared-components/src/questions/LiveQuizProgress.tsx
  packages/transactional/package.json
  pnpm-lock.yaml
Labels: feature, size:XXL

#4493 enhance: add histogram evaluation plots for case study elements
  apps/frontend-manage/src/components/evaluation/elements/CSCaseSelection.tsx
  apps/frontend-manage/src/components/evaluation/elements/CSEvaluation.tsx
  apps/frontend-manage/src/components/evaluation/elements/CSEvaluationHistogram.tsx
  apps/frontend-manage/src/components/evaluation/elements/CSEvaluationHistogramChart.tsx
  apps/frontend-manage/src/components/evaluation/elements/CSEvaluationHistogramSidebar.tsx
  apps/frontend-manage/src/components/evaluation/elements/CSEvaluationScatter.tsx
  apps/frontend-manage/src/components/evaluation/elements/CSEvaluationScatterSidebar.tsx
  apps/frontend-manage/src/components/evaluation/hooks/useCaseStudyHistogramData.ts
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyCollectionSelection.tsx
  packages/graphql/src/graphql/ops/FEvaluationResults.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/evaluation.ts
  packages/graphql/src/services/stacks.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:XL

#4494 feat: add support for case study elements in live quizzes
  apps/frontend-pwa/src/components/liveQuiz/QuestionArea.tsx
  apps/frontend-pwa/src/pages/session/[id].tsx
  apps/func-response-processor/src/index.ts
  packages/grading/src/index.ts
  packages/grading/test/index.test.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/prisma/src/data/data/TEST.ts
Labels: feature, size:L

#4495 chore(cypress): cover case study element usage in live quizzes in automated test suite
  cypress/cypress/e2e/F-live-quiz-workflow.cy.ts
  cypress/cypress/e2e/H-practice-quiz-workflow.cy.ts
  cypress/cypress/fixtures/F-live-quiz.json
Labels: size:L

#4497 chore(cypress): extend cypress test suite to cover case study elements in group activity
  cypress/cypress/e2e/D-questions-workflow.cy.ts
  cypress/cypress/e2e/J-group-activity-workflow.cy.ts
  cypress/cypress/fixtures/J-group-activity.json
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:L

#4498 fix: resolve caching issues related to answer collections and separate querying logic for improved efficiency
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyCollectionSelection.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/CaseStudyOptions.tsx
  apps/frontend-manage/src/components/questions/manipulation/options/useFormCollections.ts
  apps/frontend-manage/src/components/questions/manipulation/options/useSelectAnswerCollectionOptions.ts
  apps/frontend-manage/src/components/resources/AnswerCollections.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AddAnswerCollectionEntry.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionCreationForm.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionEditModal.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionItem.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionOption.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionViewingModal.tsx
  apps/frontend-manage/src/components/resources/answerCollections/CollectionDeletionModal.tsx
  apps/frontend-manage/src/components/resources/answerCollections/CollectionRemovalModal.tsx
  apps/frontend-manage/src/components/resources/answerCollections/RequestCancellationModal.tsx
  packages/graphql/src/graphql/ops/MCreateAnswerCollection.graphql
  packages/graphql/src/graphql/ops/QGetAnswerCollections.graphql
  packages/graphql/src/graphql/ops/QGetAnswerCollectionsInfo.graphql
  packages/graphql/src/graphql/ops/QGetSingleAnswerCollection.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/query.ts
  packages/graphql/src/schema/resource.ts
  packages/graphql/src/services/resources.ts
Labels: size:XL

#4499 fix(apps/frontend-pwa): ensure that inputs on case study element are correctly disabled after answer submission
  apps/auth/package.json
  apps/backend-docker/package.json
  apps/docs/package.json
  apps/frontend-control/package.json
  apps/frontend-manage/package.json
  apps/frontend-pwa/package.json
  apps/func-incoming-responses/package.json
  apps/func-response-processor/package.json
  apps/office-addin/package.json
  cypress/cypress/e2e/G-microlearning-workflow.cy.ts
  cypress/cypress/e2e/H-practice-quiz-workflow.cy.ts
  cypress/cypress/e2e/J-group-activity-workflow.cy.ts
  packages/markdown/package.json
  packages/shared-components/package.json
  packages/shared-components/src/CaseStudyQuestion.tsx
  packages/transactional/package.json
  pnpm-lock.yaml
Labels: dependencies, size:M

#4500 enhance(apps/frontend-pwa): show cases of case study sequentially in live quiz
  apps/frontend-pwa/src/components/liveQuiz/QuestionArea.tsx
  cypress/cypress/e2e/F-live-quiz-workflow.cy.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/shared-components/dist/utilities.css
  packages/shared-components/src/CaseStudyQuestion.tsx
  packages/shared-components/src/StudentElement.tsx
Labels: enhancement, size:L

#4501 chore(cypress): reduce duplication in cypress test suite and fix indices on cypress test attributes of student element
  cypress/cypress/e2e/D-questions-workflow.cy.ts
  cypress/cypress/e2e/F-live-quiz-workflow.cy.ts
  cypress/cypress/e2e/G-microlearning-workflow.cy.ts
  cypress/cypress/e2e/H-practice-quiz-workflow.cy.ts
  cypress/cypress/e2e/I-bookmarking-workflow.cy.ts
  cypress/cypress/e2e/J-group-activity-workflow.cy.ts
  cypress/cypress/support/commands.ts
  packages/shared-components/src/ContentElement.tsx
  packages/shared-components/src/Flashcard.tsx
  packages/shared-components/src/questions/CSCase.tsx
  packages/shared-components/src/questions/CSSlider.tsx
  packages/shared-components/src/questions/FREETextAnswerOptions.tsx
  packages/shared-components/src/questions/KPAnswerOptions.tsx
  packages/shared-components/src/questions/MCAnswerOptions.tsx
  packages/shared-components/src/questions/NUMERICALAnswerOptions.tsx
  packages/shared-components/src/questions/SCAnswerOptions.tsx
  packages/shared-components/src/questions/SELECTIONAnswerOptions.tsx
Labels: size:XXL

#4502 fix: resolve issues with live quiz wizard validation, update student UI components, and upgrade cypress
  apps/backend-docker/package.json
  apps/frontend-control/src/components/liveQuizzes/LiveQuizLists.tsx
  apps/frontend-manage/src/components/activities/creation/liveQuiz/LiveQuizQuestionsStep.tsx
  apps/frontend-manage/src/components/activities/creation/liveQuiz/LiveQuizWizard.tsx
  apps/frontend-pwa/src/components/participant/groups/PoolNotification.tsx
  apps/frontend-pwa/src/pages/session/[id].tsx
  cypress/cypress.config.ts
  cypress/cypress/e2e/A-login-workflow.cy.ts
  cypress/cypress/e2e/C-control-workflow.cy.ts
  cypress/cypress/e2e/E-course-workflow.cy.ts
  cypress/cypress/e2e/F-live-quiz-workflow.cy.ts
  cypress/cypress/e2e/G-microlearning-workflow.cy.ts
  cypress/cypress/e2e/H-practice-quiz-workflow.cy.ts
  cypress/cypress/support/commands.ts
  cypress/package.json
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/shared-components/src/CaseStudyQuestion.tsx
  packages/shared-components/src/ChoicesQuestion.tsx
  packages/shared-components/src/FreeTextQuestion.tsx
  packages/shared-components/src/NumericalQuestion.tsx
  packages/shared-components/src/SelectionQuestion.tsx
  pnpm-lock.yaml
Labels: dependencies, size:XL

#4503 fix(apps/frontend-manage): make sure that live quiz evaluation is shown for past completed live quizzes with feedbacks only
  apps/frontend-manage/src/components/evaluation/ActivityEvaluation.tsx
  apps/frontend-manage/src/components/evaluation/EvaluationFooter.tsx
  apps/frontend-manage/src/components/evaluation/navigation/InstanceNavigation.tsx
  apps/frontend-manage/src/components/evaluation/navigation/StackNavigation.tsx
  apps/frontend-manage/src/lib/hooks/useEvaluationInitialization.ts
  apps/frontend-manage/src/pages/quizzes/[id]/evaluation.tsx
Labels: size:L

#4505 enhance(apps/office-addin-v2): rework office adding for improved stability, add redirect from sessions to quizzes for manage frontend
  .windsurfrules
  apps/analytics/package.json
  apps/backend-docker/package.json
  apps/frontend-manage/next.config.mjs
  apps/lti/package.json
  apps/office-addin/.gitignore
  apps/office-addin/.prettierrc.json
  apps/office-addin/babel.config.json
  apps/office-addin/manifest-content.xml
  apps/office-addin/manifest-taskpane.xml
  apps/office-addin/package.json
  apps/office-addin/postcss.config.cjs
  apps/office-addin/rollup.config.js
  apps/office-addin/scripts/clean-cache.js
  apps/office-addin/scripts/clear.bat
  apps/office-addin/src/content/components/App.tsx
  apps/office-addin/src/content/components/URLForm.tsx
  apps/office-addin/src/content/content.html
  apps/office-addin/src/content/index.tsx
  apps/office-addin/src/content/office-utils/powerPointAPI.ts
  apps/office-addin/src/content/output.css
  apps/office-addin/src/manifest-content.xml
  apps/office-addin/src/manifest-taskpane.xml
  apps/office-addin/src/styles.css
  apps/office-addin/src/taskpane/index.tsx
  apps/office-addin/src/taskpane/taskpane.html
  apps/office-addin/tailwind.config.js
  apps/office-addin/tsconfig.json
  apps/office-addin/webpack.config.js
  packages/grading/package.json
  packages/graphql/package.json
  packages/markdown/package.json
  packages/types/package.json
  packages/util/package.json
  pnpm-lock.yaml
  scratchpad.md
Labels: enhancement, size:XXL

#4504 enhance: add list of activities affected by element instance update to UI and resolve logic issues
  apps/frontend-manage/src/components/questions/manipulation/ElementEditModal.tsx
  apps/frontend-manage/src/components/questions/manipulation/InstanceUpdateSwitch.tsx
  packages/graphql/src/graphql/ops/QGetInstanceUpdateActivities.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/query.ts
  packages/graphql/src/schema/question.ts
  packages/graphql/src/services/questions.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: size:XL

#4506 chore(cypress): extend test coverage to include element instance updates
  apps/frontend-manage/src/components/questions/manipulation/InstanceUpdateSwitch.tsx
  cypress/cypress/e2e/D-questions-workflow.cy.ts
  cypress/cypress/e2e/D1-questions-content-workflow.cy.ts
  cypress/cypress/e2e/D10-questions-operations-workflow.cy.ts
  cypress/cypress/e2e/D2-questions-flashcards-workflow.cy.ts
  cypress/cypress/e2e/D3-questions-sc-workflow.cy.ts
  cypress/cypress/e2e/D4-questions-mc-workflow.cy.ts
  cypress/cypress/e2e/D5-questions-kprim-workflow.cy.ts
  cypress/cypress/e2e/D6-questions-numerical-workflow.cy.ts
  cypress/cypress/e2e/D7-questions-free-text-workflow.cy.ts
  cypress/cypress/e2e/D8-questions-selection-workflow.cy.ts
  cypress/cypress/e2e/D9-questions-case-study-workflow.cy.ts
  cypress/cypress/e2e/F-live-quiz-workflow.cy.ts
  cypress/cypress/fixtures/D-questions.json
  cypress/cypress/support/commands.ts
  packages/shared-components/src/evaluation/ChoiceFeedback.tsx
  packages/shared-components/src/questions/KPAnswerOptions.tsx
  packages/shared-components/src/questions/MCAnswerOptions.tsx
  packages/shared-components/src/questions/SCAnswerOptions.tsx
Labels: size:XXL

#4507 fix(apps/frontend-manage): fix redirect from /sessions to /quizzes evaluation and resolve bug with undefined evaluation instance
  apps/frontend-manage/next.config.mjs
  apps/frontend-manage/src/components/evaluation/ActivityEvaluation.tsx
  apps/frontend-manage/src/components/evaluation/EvaluationUnavailableNotification.tsx
  apps/frontend-manage/src/pages/quizzes/[id]/evaluation.tsx
Labels: size:M

#4508 enhance(apps/frontend-manage): add QR modal to live quiz list for embedding
  apps/frontend-manage/src/components/liveQuiz/LiveQuiz.tsx
  apps/frontend-manage/src/components/liveQuiz/cockpit/LiveQuizQRModal.tsx
  apps/frontend-manage/src/components/liveQuiz/cockpit/LiveQuizTimeline.tsx
Labels: enhancement, size:M

#4509 enhance: set up data structure for student timeline tracking and update corresponding response mutations
  packages/graphql/src/services/groups.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/graphql/src/services/stacks.ts
  packages/prisma/src/prisma/migrations/20250217101018_student_timeline_entry/migration.sql
  packages/prisma/src/prisma/schema/course.prisma
  packages/prisma/src/prisma/schema/participant.prisma
  packages/prisma/src/prisma/schema/response.prisma
Labels: enhancement, size:L

#4510 refactor(packages/graphql): refactor live quiz ending and group activity grading finalization into clean transactions
  packages/graphql/src/services/groups.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/graphql/src/services/stacks.ts
Labels: enhancement, size:L

#4512 enhance: compute or update weekly timeline entries with daily cronjob
  apps/frontend-manage/src/components/courses/CourseGamificationInfos.tsx
  apps/frontend-manage/src/components/courses/IndividualLeaderboard.tsx
  deploy/charts/klicker-uzh-v2/templates/cron-daily-timeline-updates.yaml
  deploy/charts/klicker-uzh-v2/values.yaml
  packages/graphql/src/graphql/ops/MUpdateWeeklyTimelineEntries.graphql
  packages/graphql/src/graphql/ops/MUpdateWeeklyTimelineEntriesCourse.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/services/groups.ts
  packages/graphql/src/services/liveQuizzes.ts
  packages/graphql/src/services/participants.ts
  packages/graphql/src/services/stacks.ts
Labels: enhancement, size:XL

#4513 chore: add script to compute daily and weekly timeline entries based on past details data
  packages/graphql/src/scripts/2025-02-18_compute_past_timeline_entries.ts
Labels: size:L

#4514 enhance: implement weekly and bi-weekly custom leaderboard views
  apps/frontend-manage/src/components/courses/CourseGamificationInfos.tsx
  apps/frontend-manage/src/components/courses/IndividualLeaderboard.tsx
  apps/frontend-manage/src/components/courses/SuspendedCourseLeaderboard.tsx
  apps/frontend-manage/src/lib/hooks/useCourseWeeklyDates.ts
  packages/graphql/src/graphql/ops/QGetCourseLeaderboard.graphql
  packages/graphql/src/graphql/ops/QGetSingleCourse.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/course.ts
  packages/graphql/src/schema/query.ts
  packages/graphql/src/services/courses.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:XXL

#4516 fix(packages/shared-components): resolve issue with table resorting on live quiz evaluation re-fetch
  packages/shared-components/src/charts/ElementTableChart.tsx
Labels: size:XS

#4515 enhance: implement bi-weekly course leaderboard view on student frontend
  .github/workflows/v3_sonarcloud.yml
  apps/frontend-pwa/src/pages/course/[courseId]/index.tsx
  packages/graphql/src/graphql/ops/QGetCourseOverviewData.graphql
  packages/graphql/src/graphql/ops/QGetStudentCourseLeaderboard.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/participant.ts
  packages/graphql/src/schema/query.ts
  packages/graphql/src/services/courses.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/shared-components/src/Leaderboard.tsx
  packages/shared-components/src/Participant.tsx
Labels: enhancement, size:XL

#4517 enhance: add first version of student insights timeline and bi-weekly leaderboard
  apps/frontend-manage/src/components/courses/IndividualLeaderboard.tsx
  apps/frontend-pwa/src/components/insights/timeline/TimelineCourse.tsx
  apps/frontend-pwa/src/components/insights/timeline/TimelineCourseChart.tsx
  apps/frontend-pwa/src/components/insights/timeline/TimelineCourseInformation.tsx
  apps/frontend-pwa/src/pages/course/[courseId]/index.tsx
  apps/frontend-pwa/src/pages/index.tsx
  apps/frontend-pwa/src/pages/insights/timeline.tsx
  packages/graphql/src/graphql/ops/QGetCourseStudentTimelines.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/course.ts
  packages/graphql/src/schema/query.ts
  packages/graphql/src/services/participants.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/prisma/src/prisma/migrations/20250219140733_student_timeline_entry/migration.sql
  packages/prisma/src/prisma/schema/response.prisma
Labels: enhancement, size:XL

#4518 fix: resolve issues with weekly leaderboard computation and improve data updates
  apps/frontend-manage/src/components/courses/IndividualLeaderboard.tsx
  apps/frontend-manage/src/components/courses/SuspendedCourseLeaderboard.tsx
  apps/frontend-pwa/src/components/insights/timeline/TimelineCourse.tsx
  packages/graphql/src/graphql/ops/QGetCourseLeaderboard.graphql
  packages/graphql/src/lib/convertDateToUTCDatetime.ts
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/course.ts
  packages/graphql/src/services/courses.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: size:L

#4520 enhance(apps/frontend-manage): improve case study evaluation histogram component with extended logic
  apps/frontend-manage/src/components/evaluation/elements/CSEvaluationHistogramChart.tsx
  apps/frontend-manage/src/components/evaluation/hooks/useCaseStudyHistogramData.ts
Labels: enhancement, size:L

#4521 enhance: add lecturer course leaderboards containing collected points rolling over last 7 or 14 days
  apps/frontend-manage/src/components/courses/IndividualLeaderboard.tsx
  apps/frontend-manage/src/components/courses/SuspendedCourseLeaderboard.tsx
  packages/graphql/src/graphql/ops/QGetCourseLeaderboard.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/query.ts
  packages/graphql/src/services/courses.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:L

#4522 style(apps/auth): update already signed in view with improved labeling
  apps/auth/src/pages/index.tsx
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/shared-components/src/LanguageChanger.tsx
Labels: enhancement, size:M

#4524 fix(packages/graphql): make sure correct week start dates are used for timeline entry aggregation
  packages/graphql/src/services/participants.ts
Labels: size:S

#4523 chore(packages/prisma): update database schema for extended sharing functionalities
  packages/prisma/src/prisma/migrations/20250224192700_admin_access_group_admins/migration.sql
  packages/prisma/src/prisma/schema/resources.prisma
  packages/prisma/src/prisma/schema/user.prisma
Labels: size:M

#4526 chore: reorganize page structure and actions for resources
  apps/auth/package.json
  apps/backend-docker/package.json
  apps/docs/package.json
  apps/frontend-control/package.json
  apps/frontend-manage/package.json
  apps/frontend-manage/src/components/catalog/UserGroupsManagement.tsx
  apps/frontend-manage/src/components/catalog/import/CatalogObjectItem.tsx
  apps/frontend-manage/src/components/catalog/import/ObjectAccessRequestModal.tsx
  apps/frontend-manage/src/components/catalog/import/ObjectImportModal.tsx
  apps/frontend-manage/src/components/catalog/import/ObjectRequestCancellationModal.tsx.tsx
  apps/frontend-manage/src/components/common/Header.tsx
  apps/frontend-manage/src/components/resources/AnswerCollections.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionCreation.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionEditModal.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionItem.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionList.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionMetaForm.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionViewingModal.tsx
  apps/frontend-manage/src/components/resources/answerCollections/RequestCancellationModal.tsx
  apps/frontend-manage/src/pages/catalog.tsx
  apps/frontend-manage/src/pages/index.tsx
  apps/frontend-manage/src/pages/quizzes/[id]/evaluation.tsx
  apps/frontend-manage/src/pages/resources.tsx
  apps/frontend-manage/src/pages/resources/answerCollections.tsx
  apps/frontend-manage/src/pages/resources/catalog.tsx
  apps/frontend-manage/src/pages/resources/mediaLibrary.tsx
  apps/frontend-manage/src/pages/resources/userGroups.tsx
  apps/frontend-pwa/package.json
  apps/frontend-pwa/src/pages/insights/timeline.tsx
  apps/func-incoming-responses/package.json
  apps/func-response-processor/package.json
  apps/office-addin/package.json
  cypress/cypress/e2e/B-feature-access-workflow.cy.ts
  cypress/cypress/e2e/D8-questions-selection-workflow.cy.ts
  cypress/cypress/e2e/D9-questions-case-study-workflow.cy.ts
  cypress/cypress/e2e/F-live-quiz-workflow.cy.ts
  cypress/cypress/e2e/G-microlearning-workflow.cy.ts
  cypress/cypress/e2e/H-practice-quiz-workflow.cy.ts
  cypress/cypress/e2e/J-group-activity-workflow.cy.ts
  cypress/cypress/e2e/K-resources-workflow.cy.ts
  cypress/cypress/support/commands.ts
  packages/graphql/src/graphql/ops/QGetAnswerCollectionsInfo.graphql
  packages/graphql/src/graphql/ops/QGetSingleAnswerCollection.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/services/resources.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
  packages/markdown/package.json
  packages/shared-components/package.json
  packages/transactional/package.json
  pnpm-lock.yaml
Labels: size:XXL

#4527 feat: implement direct sharing functionality for answer collections
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionItem.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionList.tsx
  apps/frontend-manage/src/components/resources/answerCollections/CollectionSharingModal.tsx
  apps/frontend-manage/src/components/resources/sharing/CollectionSharingErrorToast.tsx
  apps/frontend-manage/src/components/resources/sharing/CollectionSharingSuccessToast.tsx
  apps/frontend-manage/src/components/resources/sharing/DirectSharingForm.tsx
  apps/frontend-manage/src/components/resources/sharing/ExistingPermissionEntries.tsx
  apps/frontend-manage/src/components/resources/sharing/GrantedPermissionsTable.tsx
  apps/frontend-manage/src/components/resources/sharing/PermissionsTable.tsx
  packages/graphql/src/graphql/ops/MShareAnswerCollection.graphql
  packages/graphql/src/graphql/ops/QGetAnswerCollectionPermissions.graphql
  packages/graphql/src/graphql/ops/QGetAnswerCollectionsInfo.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/schema/query.ts
  packages/graphql/src/schema/resource.ts
  packages/graphql/src/services/resources.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: feature, size:XXL

#4528 chore(cypress): extend test coverage to include direct sharing of answer collections
  apps/frontend-manage/src/components/resources/answerCollections/CollectionSharingModal.tsx
  cypress/cypress.config.ts
  cypress/cypress/e2e/K-resources-workflow.cy.ts
  cypress/cypress/fixtures/K-resources.json
  packages/graphql/src/services/resources.ts
Labels: enhancement, size:L

#4530 chore(cypress): extend test suite for different access levels and corresponding functionalities on answer collections
  apps/frontend-manage/src/components/resources/sharing/ExistingPermissionEntries.tsx
  cypress/cypress/e2e/K-resources-workflow.cy.ts
  cypress/cypress/fixtures/K-resources.json
  packages/graphql/src/services/resources.ts
Labels: size:XL

#4531 enhance: implement possibility to transfer ownership of an answer collection
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionItem.tsx
  apps/frontend-manage/src/components/resources/answerCollections/CollectionSharingModal.tsx
  apps/frontend-manage/src/components/resources/answerCollections/OwnershipTransferErrorToast.tsx
  apps/frontend-manage/src/components/resources/answerCollections/OwnershipTransferSuccessToast.tsx
  apps/frontend-manage/src/components/resources/answerCollections/TransferCollectionOwnershipModal.tsx
  apps/frontend-manage/src/components/resources/answerCollections/TransferOwnershipModal.tsx
  apps/frontend-manage/src/components/resources/sharing/GrantedPermissionsTable.tsx
  cypress/cypress/e2e/K-resources-workflow.cy.ts
  cypress/cypress/fixtures/K-resources.json
  packages/graphql/src/graphql/ops/MTransferCollectionOwnership.graphql
  packages/graphql/src/ops.schema.json
  packages/graphql/src/ops.ts
  packages/graphql/src/public/client.json
  packages/graphql/src/public/schema.graphql
  packages/graphql/src/public/server.json
  packages/graphql/src/schema/mutation.ts
  packages/graphql/src/services/resources.ts
  packages/i18n/messages/de.ts
  packages/i18n/messages/en.ts
Labels: enhancement, size:XL

#4534 chore(cypress): update test suite to be consistent with new catalog item management and update collection deletion logic
  apps/frontend-manage/src/components/catalog/administration/ObjectAccessSelection.tsx
  apps/frontend-manage/src/components/catalog/administration/ObjectTypeSelection.tsx
  apps/frontend-manage/src/components/catalog/import/CatalogObjectItem.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionCreationForm.tsx
  apps/frontend-manage/src/components/resources/answerCollections/AnswerCollectionMetaForm.tsx
  cypress/cypress/e2e/D8-questions-selection-workflow.cy.ts
  cypress/cypress/e2e/D9-questions-case-study-workflow.cy.ts
  cypress/cypress/e2e/F-live-quiz-workflow.cy.ts
  cypress/cypress/e2e/G-microlearning-workflow.cy.ts
  cypress/cypress/e2e/H-practice-quiz-workflow.cy.ts
  cypress/cypress/e2e/J-group-activity-workflow.cy.ts
  cypress/cypress/e2e/K-resources-workflow.cy.ts
  cypress/cypress/fixtures/K-resources.json
  cypress/cypress/support/commands.ts
  packages/graphql/src/services/resources.ts
  packages/i18n/messages/de.ts
Labels: size:XL
